// Copyright 2017 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Controller for the Tutor Card.
 */

oppia.animation('.conversation-skin-responses-animate-slide', function() {
  return {
    removeClass: function(element, className, done) {
      if (className !== 'ng-hide') {
        done();
        return;
      }
      element.hide().slideDown(400, done);
    },
    addClass: function(element, className, done) {
      if (className !== 'ng-hide') {
        done();
        return;
      }
      element.slideUp(400, done);
    }
  };
});

oppia.directive('tutorCard', [
  'UrlInterpolationService', function(UrlInterpolationService) {
    return {
      restrict: 'E',
      scope: {
        onClickContinueButton: '&',
        onSubmitAnswer: '&',
        onDismiss: '&',
        startCardChangeAnimation: '='
      },
      templateUrl: UrlInterpolationService.getDirectiveTemplateUrl(
        '/pages/exploration_player/' +
        'tutor_card_directive.html'),
      controller: [
        '$scope', '$timeout', '$rootScope', '$anchorScroll',
        'ExplorationPlayerService', 'HintManagerService',
        'PlayerPositionService', 'HintAndSolutionModalService',
        'PlayerTranscriptService', 'ExplorationPlayerStateService',
        'WindowDimensionsService', 'UrlService', 'AudioPlayerService',
        'AutogeneratedAudioPlayerService', 'AudioPreloaderService',
        'TWO_CARD_THRESHOLD_PX', 'CONTENT_FOCUS_LABEL_PREFIX',
        'CONTINUE_BUTTON_FOCUS_LABEL', 'EVENT_ACTIVE_CARD_CHANGED',
        'HINT_REQUEST_STRING_I18N_IDS', 'DELAY_FOR_HINT_FEEDBACK_MSEC',
        'SolutionManagerService', 'DeviceInfoService',
        function(
          $scope, $timeout, $rootScope, $anchorScroll,
          ExplorationPlayerService, HintManagerService,
          PlayerPositionService, HintAndSolutionModalService,
          PlayerTranscriptService, ExplorationPlayerStateService,
          WindowDimensionsService, UrlService, AudioPlayerService,
          AutogeneratedAudioPlayerService, AudioPreloaderService,
          TWO_CARD_THRESHOLD_PX, CONTENT_FOCUS_LABEL_PREFIX,
          CONTINUE_BUTTON_FOCUS_LABEL, EVENT_ACTIVE_CARD_CHANGED,
          HINT_REQUEST_STRING_I18N_IDS, DELAY_FOR_HINT_FEEDBACK_MSEC,
          SolutionManagerService, DeviceInfoService) {
          var updateActiveCard = function() {
            var index = PlayerPositionService.getActiveCardIndex();
            if (index === null) {
              return;
            }

            $scope.arePreviousResponsesShown = false;
            $scope.activeCard = PlayerTranscriptService.getCard(index);

            $scope.isInteractionInline = (
              ExplorationPlayerStateService.isInteractionInline(
                $scope.activeCard.stateName));

            $scope.interactionInstructions = (
              ExplorationPlayerStateService.getInteractionInstructions(
                $scope.activeCard.stateName));
            HintManagerService.reset(ExplorationPlayerService.getInteraction(
              $scope.activeCard.stateName).hints);

            $scope.hintsExist = Boolean(ExplorationPlayerService.getInteraction(
              $scope.activeCard.stateName).hints.length);

            var solution = ExplorationPlayerService.getSolution(
              $scope.activeCard.stateName);

            SolutionManagerService.reset(solution);
            $scope.solutionExists = Boolean(solution);

            $rootScope.$broadcast(
              'hintsAndSolutionReset', {
                numOfHints: ExplorationPlayerService.getInteraction(
                  $scope.activeCard.stateName).hints.length,
                solutionExists: $scope.solutionExists
              });

            $scope.contentAudioTranslations = (
              ExplorationPlayerService.getStateContentAudioTranslations(
                $scope.activeCard.stateName));

            AudioPlayerService.stop();
            AudioPreloaderService.clearMostRecentlyRequestedAudioFilename();
            AutogeneratedAudioPlayerService.cancel();
          };

          $scope.arePreviousResponsesShown = false;

          $scope.waitingForOppiaFeedback = false;

          $scope.consumeHint = function() {
            if (!HintManagerService.areAllHintsExhausted()) {
              HintAndSolutionModalService.displayHintModal();
            }
          };

          $scope.viewSolution = function() {
            HintAndSolutionModalService.displaySolutionModal();
            ExplorationPlayerService.recordSolutionHit(
              PlayerPositionService.getCurrentStateName());
          };

          $scope.isHintAvailable = function() {
            var hintIsAvailable = (
              HintManagerService.isCurrentHintAvailable() &&
              !HintManagerService.areAllHintsExhausted());
            return hintIsAvailable;
          };

          $scope.areAllHintsExhausted = function() {
            return HintManagerService.areAllHintsExhausted();
          };

          $scope.isCurrentSolutionAvailable = function () {
            return SolutionManagerService.isCurrentSolutionAvailable();
          };

          $scope.isIframed = UrlService.isIframed();

          $scope.CONTINUE_BUTTON_FOCUS_LABEL = CONTINUE_BUTTON_FOCUS_LABEL;

          $scope.OPPIA_AVATAR_IMAGE_URL = (
            UrlInterpolationService.getStaticImageUrl(
              '/avatar/oppia_avatar_100px.svg'));

          $scope.profilePicture = UrlInterpolationService.getStaticImageUrl(
            '/avatar/user_blue_72px.png');

          ExplorationPlayerService.getUserProfileImage().then(function(result) {
            $scope.profilePicture = result;
          });

          $scope.getContentFocusLabel = function(index) {
            return CONTENT_FOCUS_LABEL_PREFIX + index;
          };

          $scope.toggleShowPreviousResponses = function() {
            $scope.arePreviousResponsesShown =
             !$scope.arePreviousResponsesShown;
          };

          $scope.isViewportNarrow = function() {
            return WindowDimensionsService.getWidth() < TWO_CARD_THRESHOLD_PX;
          };

          $scope.submitAnswer = function(answer, interactionRulesService) {
            $scope.waitingForOppiaFeedback = true;
            $scope.onSubmitAnswer({
              answer: answer,
              rulesService: interactionRulesService
            });
          };

          $scope.isContentAudioTranslationAvailable = function() {
            return ExplorationPlayerService.isContentAudioTranslationAvailable(
                $scope.activeCard.stateName);
          };

          $scope.isCurrentCardAtEndOfTranscript = function() {
            return PlayerTranscriptService.isLastCard(
              PlayerPositionService.getActiveCardIndex());
          };

          $scope.isOnTerminalCard = function() {
            return $scope.activeCard &&
              ExplorationPlayerStateService.isStateTerminal(
                $scope.activeCard.stateName);
          };

          $scope.getInputResponsePairId = function(index) {
            return 'input-response-pair-' + index;
          };

          $scope.$on(EVENT_ACTIVE_CARD_CHANGED, function() {
            updateActiveCard();
          });

          $scope.$on('oppiaFeedbackAvailable', function() {
            $scope.waitingForOppiaFeedback = false;
            HintManagerService.makeCurrentHintAvailable();

            // Auto scroll to the new feedback on mobile device.
            if (DeviceInfoService.isMobileDevice()) {
              var index = PlayerPositionService.getActiveCardIndex();
              var activeCard = PlayerTranscriptService.getCard(index);
              var latestFeedbackIndex = (
                activeCard.inputResponsePairs.length - 1);
              $anchorScroll($scope.getInputResponsePairId(latestFeedbackIndex));
            }
          });

          updateActiveCard();
        }
      ]
    };
  }]);
