from typing import Any, Sequence, TypeVar

_T = TypeVar("_T")

__about__: str

def heapify(__heap: Sequence[Any]) -> None: ...
def heappop(__heap: Sequence[_T]) -> _T: ...
def heappush(__heap: Sequence[_T], __item: _T) -> None: ...
def heappushpop(__heap: Sequence[_T], __item: _T) -> _T: ...
def heapreplace(__heap: Sequence[_T], __item: _T) -> _T: ...
