# stubs/requests/__init__.pyi
from typing import Any, Mapping

class Response:
    status_code: int
    text: str
    content: bytes
    ok: bool
    headers: Mapping[str, str]
    def json(self) -> Any: ...
    def raise_for_status(self) -> None: ...

def get(url: str, **kwargs: Any) -> Response: ...
def post(url: str, **kwargs: Any) -> Response: ...
def put(url: str, **kwargs: Any) -> Response: ...
def delete(url: str, **kwargs: Any) -> Response: ...

def request(
    method: str,
    url: str,
    **kwargs: Any
) -> Response: ...
