runtime: python27
api_version: 1
threadsafe: false
instance_class: F2
# The "version" line is added here so that MR jobs can run locally (see issue
# #6534 on oppia/oppia).
version: default

builtins:
- appstats: on
- deferred: on
- remote_api: on

inbound_services:
- warmup
- mail

default_expiration: "10m"
handlers:
# PRODUCTION STATIC
- url: /favicon.ico
  static_files: assets/favicon.ico
  upload: assets/favicon.ico
  secure: always
- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt
  secure: always
- url: /sitemap.xml
  static_files: assets/sitemap.xml
  upload: assets/sitemap.xml
  secure: always
- url: /mapreduce/pipeline/images
  static_dir: third_party/gae-mapreduce-1.9.17.0/mapreduce/lib/pipeline/ui/images
  secure: always
- url: /build
  static_dir: build
  secure: always
  expiration: "90d"
- url: /third_party/static
  static_dir: third_party/static
  secure: always
  expiration: "90d"

# DEVELOPMENT STATIC
- url: /dist
  static_dir: core/templates/dev/head/dist
  secure: always
  application_readable: true
  expiration: "0"
- url: /assets
  static_dir: assets
  secure: always
  application_readable: true
  expiration: "0"
# Serve js scripts and css files under core/templates/dev/head.
# This regex allows us to recursively serve js scripts.
# "\1" inserts text captured by the capture group in the URL pattern.
- url: /templates/dev/head/(.*\.(css))$
  static_files: core/templates/dev/head/\1
  upload: core/templates/dev/head/(.*\.(css))$
  secure: always
  expiration: "0"
- url: /templates/dev/head/(.*\.(js))$
  static_files: local_compiled_js/core/templates/dev/head/\1
  upload: local_compiled_js/core/templates/dev/head/(.*\.(js))$
  secure: always
  expiration: "0"
- url: /templates/dev/head/(.*\.(html))$
  static_files: core/templates/dev/head/\1
  upload: core/templates/dev/head/(.*\.(html))$
  secure: always
  expiration: "0"
  application_readable: true
- url: /third_party/generated
  static_dir: third_party/generated
  secure: always
  expiration: "0"
- url: /extensions/interactions/(.*)/static/(.*\.(css|png))
  static_files: extensions/interactions/\1/static/\2
  upload: extensions/interactions/(.*)/static/(.*\.(css|png))
  secure: always
  expiration: "0"
- url: /extensions/interactions/(.*)/static/(.js)
  static_files: extensions/interactions/\1/static/\2
  upload: local_compiled_js/extensions/interactions/(.*)/static/(.js)
  secure: always
  expiration: "0"
- url: /extensions/(interactions|rich_text_components)/(.*)/directives/(.*\.(html))
  static_files: extensions/\1/\2/directives/\3
  upload: extensions/(interactions|rich_text_components)/(.*)/directives/(.*\.(html))
  secure: always
  expiration: "0"
# Serve js scripts for gadgets, interactions, rich_text_components, custom ckeditor plugins
# and objects under extensions in dev mode. This regex allows us to recursively serve js
# scripts under the three specified directories. "\1" and "\2" insert capture
# groups from the url pattern.
- url: /extensions/(interactions|rich_text_components|objects|classifiers|ckeditor_plugins)/(.*\.(png))$
  static_files: extensions/\1/\2
  upload: extensions/(interactions|rich_text_components|objects|classifiers|ckeditor_plugins)/(.*\.(png))$
  secure: always
  expiration: "0"
- url: /extensions/(interactions|rich_text_components|objects|classifiers|ckeditor_plugins)/(.*\.(js))$
  static_files: local_compiled_js/extensions/\1/\2
  upload: local_compiled_js/extensions/(interactions|rich_text_components|objects|classifiers|ckeditor_plugins)/(.*\.(js))$
  secure: always
  expiration: "0"
- url: /extensions/visualizations/(.*\.html)
  static_files: extensions/visualizations/\1
  upload: extensions/visualizations/(.*\.html)
  secure: always
  expiration: "0"
- url: /extensions/objects/templates/(.*\.html)
  static_files: extensions/objects/templates/\1
  upload: extensions/objects/templates/(.*\.html)
  secure: always
  expiration: "0"

# DYNAMIC
- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always
- url: /mapreduce/worker(/.*)?
  script: mapreduce.main.APP
  login: admin
  secure: always
- url: /cron/.*
  login: admin
  script: main_cron.app
  secure: always
- url: /task/.*
  login: admin
  script: main_taskqueue.app
  secure: always
- url: /_ah/mail/.*
  login: admin
  script: main_mail.app
  secure: always
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: '2.6'
- name: PIL
  version: '1.1.7'
# This is needed for sending requests to a mailgun HTTPS URL.
- name: ssl
  version: '2.7.11'
- name: webapp2
  version: '2.5.2'

env_variables:
  PYTHONHTTPSVERIFY: 1

skip_files:
# .pyc and .pyo files
- ^(.*/)?.*\.py[co]$
# Unix hidden files whose names begin with a dot
- ^(.*/)?\..*$
# Karma test files
- ^(.*/)Spec.js$
# Typescript files
- ^(.*/)?.*\.ts$
# Typescript output log file
- ^(.*/)tsc_output_log.txt$
# Other folders to ignore
- tests/
- scripts/
- integrations/
- integrations_dev/
- node_modules/
# Some third_party static scripts are directly imported, namely: jquery,
# jqueryui, angularjs, jqueryui-touch-punch, MathJax, code-mirror,
# ui-codemirror, d3js, midi-js, ui-map, guppy, skulpt, math-expressions.
# We exclude some of the scripts that are not directly imported in order to
# reduce deployed file count.
# TODO(sll): Find a more structured way of doing this.
- third_party/static/angular-audio-1.7.4
- third_party/static/angular-scroll-1.0.0
- third_party/static/angular-toastr-1.7.0
- third_party/static/bower-material-0.6.0-rc1
- third_party/static/font-awesome-4.7.0
- third_party/static/guppy-b5055b/site
- third_party/static/guppy-b5055b/test
- third_party/static/MathJax-2.7.5/docs
- third_party/static/MathJax-2.7.5/fonts
- third_party/static/MathJax-2.7.5/localization/ast
- third_party/static/MathJax-2.7.5/localization/bcc
- third_party/static/MathJax-2.7.5/localization/bg
- third_party/static/MathJax-2.7.5/localization/br
- third_party/static/MathJax-2.7.5/localization/ca
- third_party/static/MathJax-2.7.5/localization/cdo
- third_party/static/MathJax-2.7.5/localization/cs
- third_party/static/MathJax-2.7.5/localization/cy
- third_party/static/MathJax-2.7.5/localization/da
- third_party/static/MathJax-2.7.5/localization/de
- third_party/static/MathJax-2.7.5/localization/eo
- third_party/static/MathJax-2.7.5/localization/es
- third_party/static/MathJax-2.7.5/localization/fa
- third_party/static/MathJax-2.7.5/localization/fi
- third_party/static/MathJax-2.7.5/localization/fr
- third_party/static/MathJax-2.7.5/localization/gl
- third_party/static/MathJax-2.7.5/localization/he
- third_party/static/MathJax-2.7.5/localization/ia
- third_party/static/MathJax-2.7.5/localization/it
- third_party/static/MathJax-2.7.5/localization/ja
- third_party/static/MathJax-2.7.5/localization/kn
- third_party/static/MathJax-2.7.5/localization/ko
- third_party/static/MathJax-2.7.5/localization/lb
- third_party/static/MathJax-2.7.5/localization/lki
- third_party/static/MathJax-2.7.5/localization/lt
- third_party/static/MathJax-2.7.5/localization/mk
- third_party/static/MathJax-2.7.5/localization/nl
- third_party/static/MathJax-2.7.5/localization/oc
- third_party/static/MathJax-2.7.5/localization/pl
- third_party/static/MathJax-2.7.5/localization/pt
- third_party/static/MathJax-2.7.5/localization/pt-br
- third_party/static/MathJax-2.7.5/localization/qqq
- third_party/static/MathJax-2.7.5/localization/ru
- third_party/static/MathJax-2.7.5/localization/scn
- third_party/static/MathJax-2.7.5/localization/sco
- third_party/static/MathJax-2.7.5/localization/sl
- third_party/static/MathJax-2.7.5/localization/sv
- third_party/static/MathJax-2.7.5/localization/tr
- third_party/static/MathJax-2.7.5/localization/uk
- third_party/static/MathJax-2.7.5/localization/vi
- third_party/static/MathJax-2.7.5/localization/zh-hans
- third_party/static/MathJax-2.7.5/test
- third_party/static/MathJax-2.7.5/unpacked
- third_party/static/messageformat-0.3.1
- third_party/static/ng-img-crop-0.3.2
- third_party/static/nginfinitescroll-1.0.0
- third_party/static/perfectscrollbar-0.6.16
- third_party/static/rangy-1.3.0
- third_party/static/widget
