application: oppiaserver
version: 1
runtime: python27
api_version: 1
threadsafe: false

env_variables:
  DJANGO_SETTINGS_MODULE: 'oppiaserver.settings'
  OPPIA_VERSION: '1.0.4'

builtins:
- appstats: on
- remote_api: on

admin_console:
  pages:
  - name: Oppia Admin Page
    url: /admin

handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /images
  static_dir: static/images
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=600'
- url: /css
  # NB: not minified. TODO(sll): fix.
  static_dir: templates/dev/head/lib/css
  secure: always
- url: /img
  static_dir: third_party/bootstrap/img
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /third_party/static
  static_dir: third_party/static
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=2592000'
    Vary: Accept-Encoding
- url: /data/widgets/(.*)/static/(.*)
  static_files: data/widgets/\1/static/\2
  upload: data/widgets/(.*)/static/(.*)
  secure: always
  http_headers:
    Cache-Control: 'public, max-age=60'
- url: /.*
  script: main.app
  secure: always

libraries:
- name: jinja2
  version: '2.6'
- name: lxml
  version: '2.3'
- name: webapp2
  version: '2.5.2'
