steps:
  - id: lint-check
    name: python:2.7-jessie
    entrypoint: bash
    dir: mv 
    args: 
      - '-c'
      - | 
          apt-get update
          apt-get install lsb-release
          curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_77.0.3865.75-1_amd64.deb
          dpkg -i google-chrome.deb && apt-get install -f -y
          dpkg -i google-chrome.deb
          google-chrome --version
          python -m scripts.install_third_party_libs
          python -m scripts.third_party_size_check
          python -m scripts.pre_commit_linter --path=. --verbose

