steps:
  - id: build-oppia-base
    name: gcr.io/kaniko-project/executor:latest
    wait_for: ["-"]
    args: 
    - --destination=gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    - --cache=true
    - --cache-ttl=24h

  - id: install-dependencies
    wait_for: build-oppia-base
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    entrypoint: bash
    args: 
      - "-c"
      - |
          mkdir oppia
          shopt -s extglob
          mv !(oppia) oppia
          shopt -u extglob
          cd oppia
          python -m scripts.install_third_party_libs

  - id: third-party-size-check
    wait_for: install-dependencies
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    dir: oppia
    entrypoint: python
    args: ["-m", "scripts.third_party_size_check"]
