steps:
  - id: build-oppia-base
    name: gcr.io/kaniko-project/executor:latest
    wait_for: ["-"]
    args: 
    - --destination=gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    - --cache=true
    - --cache-ttl=24h

  - id: install-dependencies
    wait_for: ["build-oppia-base"]
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    volumes:
      - name: 'test'
        path: '/test'
    entrypoint: bash
    args: 
      - "-c"
      - |
          mkdir /test/oppia
          mv * /test/oppia
          cd /test/oppia
          git init
          python -m scripts.install_third_party_libs

  - id: third-party-size-check
    wait_for: ["install-dependencies"]
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: python
    args: ["-m", "scripts.third_party_size_check"]
