steps:
  - id: lint-check
    name: python:2.7-jessie
    entrypoint: bash
    args: 
      - '-c'
      - |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
          python -m scripts.install_third_party_libs
          python -m scripts.third_party_size_check
          python -m scripts.pre_commit_linter --path=. --verbose
