timeout: 1800s # 30 minutes
logsBucket: 'gs://oppia-cloudbuild-logs'
steps:
  - id: build-oppia-base
    name: gcr.io/kaniko-project/executor:latest
    wait_for: ["-"]
    args: 
    - --dockerfile=Dockerfile.base
    - --destination=gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    - --cache=true
    - --cache-ttl=24h

  - id: install-dependencies
    wait_for: ["build-oppia-base"]
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    volumes:
      - name: 'test'
        path: '/test'
    entrypoint: bash
    args: 
      - "-c"
      - |
          mkdir /test/oppia
          shopt -s dotglob
          mv * /test/oppia
          cd /test/oppia
          git init
          python -m scripts.install_third_party_libs

  - id: third-party-size-check
    wait_for: ["install-dependencies"]
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: python
    args: ["-m", "scripts.third_party_size_check"]

  - id: setup-and-typescript-tests
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["install-dependencies"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args: 
      - "-c"
      - |
          set -e
          python -m scripts.check_e2e_tests_are_captured_in_ci
          python -m scripts.typescript_checks
          python -m scripts.typescript_checks --strict_checks
 
  - id: e2e-additional-editor-player-features
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --suite="additionalEditorFeatures" --prod_env --skip-install
          xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="additionalPlayerFeatures" --prod_env
        

  - id: e2e-core-editor-player-features
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --suite="coreEditorAndPlayerFeatures" --prod_env --skip-install
    
  - id: e2e-creator-dashboard-improvements-tab
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="creatorDashboard" --prod_env
          xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationImprovementsTab" --prod_env
    
  - id: e2e-exploration-statistics-translation-tab
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="explorationStatisticsTab" --prod_env
          xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationTranslationTab" --prod_env
  
  - id: e2e-exploration-feedback-history-tab
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="explorationFeedbackTab" --prod_env
          xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationHistoryTab" --prod_env

  - id: e2e-extensions
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="extensions" --prod_env

  - id: e2e-learner-dashboard
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="learner" --prod_env
          xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="learnerDashboard" --prod_env

  - id: e2e-skill-editor
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="skillEditor" --prod_env

  - id: e2e-embedding
    name: gcr.io/oppia-jenkins-test-server/oppia-base:$SHORT_SHA
    wait_for: ["setup-and-typescript-tests"]
    volumes:
      - name: 'test'
        path: '/test'
    dir: /test/oppia
    entrypoint: bash
    args:
      - "-c"
      - |
          xvfb-run -a python -m scripts.run_e2e_tests --skip-install --suite="embedding" --prod_env
