// Copyright 2018 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Tests for SubtopicPageContentsObjectFactory.
 */

// TODO(#7222): Remove the following block of unnnecessary imports once
// SubtopicPageContentsObjectFactory.ts is upgraded to Angular 8.
import { AudioLanguageObjectFactory } from
  'domain/utilities/AudioLanguageObjectFactory.ts';
import { AutogeneratedAudioLanguageObjectFactory } from
  'domain/utilities/AutogeneratedAudioLanguageObjectFactory.ts';
import { VoiceoverObjectFactory } from
  'domain/exploration/VoiceoverObjectFactory.ts';
// ^^^ This block is to be removed.

require('domain/topic/SubtopicPageContentsObjectFactory.ts');

describe('Subtopic page contents object factory', function() {
  var SubtopicPageContentsObjectFactory = null;

  var expectedDefaultObject = {
    subtitled_html: {
      html: '',
      content_id: 'content'
    },
    recorded_voiceovers: {
      voiceovers_mapping: {
        content: {}
      }
    }
  };

  var backendDict = {
    subtitled_html: {
      html: 'test content',
      content_id: 'content'
    },
    recorded_voiceovers: {
      voiceovers_mapping: {
        content: {
          en: {
            filename: 'test.mp3',
            file_size_bytes: 100,
            needs_update: false
          }
        }
      }
    }
  };

  beforeEach(angular.mock.module('oppia'));
  beforeEach(angular.mock.module('oppia', function($provide) {
    $provide.value(
      'AudioLanguageObjectFactory', new AudioLanguageObjectFactory());
    $provide.value(
      'AutogeneratedAudioLanguageObjectFactory',
      new AutogeneratedAudioLanguageObjectFactory());
    $provide.value('VoiceoverObjectFactory', new VoiceoverObjectFactory());
  }));

  beforeEach(angular.mock.inject(function($injector) {
    SubtopicPageContentsObjectFactory =
      $injector.get('SubtopicPageContentsObjectFactory');
  }));

  it('should be able to create a default object', function() {
    var defaultObject = SubtopicPageContentsObjectFactory.createDefault();
    expect(defaultObject.toBackendDict()).toEqual(expectedDefaultObject);
  });

  it('should convert from a backend dictionary', function() {
    var sampleSubtopicPageContents =
      SubtopicPageContentsObjectFactory.createFromBackendDict(backendDict);
    expect(sampleSubtopicPageContents.getSubtitledHtml().getHtml())
      .toEqual('test content');
    expect(sampleSubtopicPageContents.getSubtitledHtml().getContentId())
      .toEqual('content');
    expect(sampleSubtopicPageContents.getRecordedVoiceovers().getVoiceover(
      'content', 'en').toBackendDict()).toEqual({
      filename: 'test.mp3',
      file_size_bytes: 100,
      needs_update: false
    });
  });

  it('should convert from a backend dictionary', function() {
    var sampleSubtopicPageContents =
      SubtopicPageContentsObjectFactory.createFromBackendDict(backendDict);
    expect(sampleSubtopicPageContents.toBackendDict()).toEqual(backendDict);
  });
});
