// Copyright 2017 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Unit tests to operate the playback of autogenerated audio
 * using the SpeechSynthesis API.
 */

import {async, TestBed} from '@angular/core/testing';
import {AutomaticVoiceoverHighlightService} from './automatic-voiceover-highlight-service';

describe('Automatic voiceover highlight service', () => {
  let automaticVoiceoverHighlightService: AutomaticVoiceoverHighlightService;

  beforeEach(async(() => {
    TestBed.configureTestingModule({});
    automaticVoiceoverHighlightService = TestBed.inject(
      AutomaticVoiceoverHighlightService
    );
  }));

  it('should set active content id', () => {
    automaticVoiceoverHighlightService.setActiveContentId('content_id');
    expect(automaticVoiceoverHighlightService.activeContentId).toBe(
      'content_id'
    );
  });

  it('should set automated voiceovers audio offsets', () => {
    let contentIdToVoiceoversAudioOffsetsMsecs = {
      content0: [
        {token: 'This', audioOffsetMsecs: 0.0},
        {token: 'is', audioOffsetMsecs: 100.0},
        {token: 'from', audioOffsetMsecs: 200.0},
        {token: 'cached', audioOffsetMsecs: 300.0},
        {token: 'model', audioOffsetMsecs: 400.0},
      ],
    };

    automaticVoiceoverHighlightService.setAutomatedVoiceoversAudioOffsets(
      contentIdToVoiceoversAudioOffsetsMsecs
    );
    expect(
      automaticVoiceoverHighlightService.automatedVoiceoversAudioOffsetsMsecs
    ).toEqual(contentIdToVoiceoversAudioOffsetsMsecs);
  });

  it('should be able to highlight ID to sentence map', () => {
    let highlightIdToSentenceMap = {
      highlightId1: 'This is first card!',
      highlightId2: 'Congratulations! You have completed the lesson.',
    };

    let highlightIdToSentenceWithoutSpacesMap = {
      highlightId1: 'Thisisfirstcard!',
      highlightId2: 'Congratulations!Youhavecompletedthelesson.',
    };

    expect(automaticVoiceoverHighlightService.highlightIdToSentenceMap).toEqual(
      {}
    );
    expect(
      automaticVoiceoverHighlightService.highlightIdToSentenceWithoutSpacesMap
    ).toEqual({});

    automaticVoiceoverHighlightService.setHighlightIdToSenetnceMap(
      highlightIdToSentenceMap
    );

    expect(automaticVoiceoverHighlightService.highlightIdToSentenceMap).toEqual(
      highlightIdToSentenceMap
    );
    expect(
      automaticVoiceoverHighlightService.highlightIdToSentenceWithoutSpacesMap
    ).toEqual(highlightIdToSentenceWithoutSpacesMap);
  });

  it('should get sentence to highlight interval list', () => {
    let automatedVoiceoversAudioOffsetsMsecs = {
      content0: [
        {token: 'Nic', audioOffsetMsecs: 0.0},
        {token: 'took', audioOffsetMsecs: 100.0},
        {token: 'Jaime', audioOffsetMsecs: 200.0},
        {token: 'to', audioOffsetMsecs: 300.0},
        {token: 'the', audioOffsetMsecs: 400.0},
        {token: 'arcade', audioOffsetMsecs: 500.0},
        {token: 'to', audioOffsetMsecs: 600.0},
        {token: 'take', audioOffsetMsecs: 700.0},
        {token: 'part', audioOffsetMsecs: 800.0},
        {token: 'in', audioOffsetMsecs: 900.0},
        {token: 'the', audioOffsetMsecs: 1000.0},
        {token: 'arcade’s', audioOffsetMsecs: 1100.0},
        {token: 'annual', audioOffsetMsecs: 1200.0},
        {token: 'game', audioOffsetMsecs: 1300.0},
        {token: 'competition', audioOffsetMsecs: 1400.0},
        {token: '.', audioOffsetMsecs: 1500.0},
        {token: 'The', audioOffsetMsecs: 1600.0},
        {token: 'winner', audioOffsetMsecs: 1700.0},
        {token: 'would', audioOffsetMsecs: 1800.0},
        {token: 'be', audioOffsetMsecs: 1900.0},
        {token: 'able', audioOffsetMsecs: 2000.0},
        {token: 'to', audioOffsetMsecs: 2100.0},
        {token: 'exchange', audioOffsetMsecs: 2200.0},
        {token: 'their', audioOffsetMsecs: 2300.0},
        {token: 'points', audioOffsetMsecs: 2400.0},
        {token: 'for', audioOffsetMsecs: 2500.0},
        {token: 'a', audioOffsetMsecs: 2600.0},
        {token: 'grand', audioOffsetMsecs: 2700.0},
        {token: 'prize', audioOffsetMsecs: 2800.0},
        {token: 'to', audioOffsetMsecs: 2900.0},
        {token: 'take', audioOffsetMsecs: 3000.0},
        {token: 'home', audioOffsetMsecs: 3100.0},
        {token: '!', audioOffsetMsecs: 3200.0},
      ],
    };

    let highlightIdToSentenceMap = {
      highlightId1:
        'Nic took Jaime to the arcade to take part in the arcade’s annual game competition.',
      highlightId2:
        'The winner would be able to exchange their points for a grand prize to take home!',
    };

    automaticVoiceoverHighlightService.setAutomatedVoiceoversAudioOffsets(
      automatedVoiceoversAudioOffsetsMsecs
    );
    automaticVoiceoverHighlightService.setHighlightIdToSenetnceMap(
      highlightIdToSentenceMap
    );
    automaticVoiceoverHighlightService.setActiveContentId('content0');
    automaticVoiceoverHighlightService.punctuationsForCurrentLanguage = '.!?';

    automaticVoiceoverHighlightService.getSentencesToHighlightForTimeRanges();

    let exptectedSentenceHighlightIntervalList = [
      {
        highlightSentenceId: 'highlightId1',
        startTimeInSecs: 0,
        endTimeInSecs: 2,
      },
      {
        highlightSentenceId: 'highlightId2',
        startTimeInSecs: 2,
        endTimeInSecs: 3,
      },
    ];

    expect(
      automaticVoiceoverHighlightService.sentenceHighlightIntervalList
    ).toEqual(exptectedSentenceHighlightIntervalList);
  });

  it('should get highlight sentence ID from given audio time interval', () => {
    let sentenceHighlightIntervalList = [
      {
        highlightSentenceId: 'highlightId1',
        startTimeInSecs: 0,
        endTimeInSecs: 2,
      },
      {
        highlightSentenceId: 'highlightId2',
        startTimeInSecs: 2,
        endTimeInSecs: 5,
      },
      {
        highlightSentenceId: 'highlightId3',
        startTimeInSecs: 6,
        endTimeInSecs: 7,
      },
    ];

    automaticVoiceoverHighlightService.sentenceHighlightIntervalList =
      sentenceHighlightIntervalList;

    expect(
      automaticVoiceoverHighlightService.getCurrentSentenceIdToHighlight(2)
    ).toBe('highlightId1');
    expect(
      automaticVoiceoverHighlightService.getCurrentSentenceIdToHighlight(3)
    ).toBe('highlightId2');
    expect(
      automaticVoiceoverHighlightService.getCurrentSentenceIdToHighlight(6)
    ).toBe('highlightId3');
  });
});
