"use strict";
// Copyright 2019 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
exports.__esModule = true;
/**
 * @fileoverview Service for storing all upgraded services
 */
var static_1 = require("@angular/upgrade/static");
var core_1 = require("@angular/core");
var platform_browser_1 = require("@angular/platform-browser");
var http_1 = require("@angular/common/http");
var admin_data_service_1 = require("pages/admin-page/services/admin-data.service");
var admin_router_service_ts_1 = require("pages/admin-page/services/admin-router.service.ts");
var admin_task_manager_service_1 = require("pages/admin-page/services/admin-task-manager.service");
var alerts_service_1 = require("services/alerts.service");
var angular_name_service_1 = require("pages/exploration-editor-page/services/angular-name.service");
var AnswerClassificationResultObjectFactory_1 = require("domain/classifier/AnswerClassificationResultObjectFactory");
var answer_classification_service_1 = require("pages/exploration-player-page/services/answer-classification.service");
var answer_groups_cache_service_1 = require("pages/exploration-editor-page/editor-tab/services/answer-groups-cache.service");
var AnswerGroupObjectFactory_1 = require("domain/exploration/AnswerGroupObjectFactory");
var AnswerStatsObjectFactory_1 = require("domain/exploration/AnswerStatsObjectFactory");
var app_service_1 = require("services/app.service");
var audio_bar_status_service_1 = require("services/audio-bar-status.service");
var AudioFileObjectFactory_1 = require("domain/utilities/AudioFileObjectFactory");
var AudioLanguageObjectFactory_1 = require("domain/utilities/AudioLanguageObjectFactory");
var audio_translation_language_service_1 = require("pages/exploration-player-page/services/audio-translation-language.service");
var audio_translation_manager_service_1 = require("pages/exploration-player-page/services/audio-translation-manager.service");
var AutogeneratedAudioLanguageObjectFactory_1 = require("domain/utilities/AutogeneratedAudioLanguageObjectFactory");
var autogenerated_audio_player_service_1 = require("services/autogenerated-audio-player.service");
var autoplayed_videos_service_1 = require("services/autoplayed-videos.service");
var background_mask_service_1 = require("services/stateful/background-mask.service");
var base_interaction_validation_service_1 = require("interactions/base-interaction-validation.service");
var browser_checker_service_1 = require("domain/utilities/browser-checker.service");
var camel_case_to_hyphens_pipe_1 = require("filters/string-utility-filters/camel-case-to-hyphens.pipe");
var ChangeObjectFactory_1 = require("domain/editor/undo_redo/ChangeObjectFactory");
var ClassifierObjectFactory_1 = require("domain/classifier/ClassifierObjectFactory");
var classroom_backend_api_service_1 = require("domain/classroom/classroom-backend-api.service");
var code_normalizer_service_1 = require("services/code-normalizer.service");
var code_repl_prediction_service_1 = require("interactions/CodeRepl/code-repl-prediction.service");
var code_repl_rules_service_1 = require("interactions/CodeRepl/directives/code-repl-rules.service");
var code_repl_validation_service_1 = require("interactions/CodeRepl/directives/code-repl-validation.service");
var collection_creation_backend_api_service_1 = require("components/entity-creation-services/collection-creation-backend-api.service");
var collection_creation_service_1 = require("components/entity-creation-services/collection-creation.service");
var CollectionNodeObjectFactory_1 = require("domain/collection/CollectionNodeObjectFactory");
var CollectionObjectFactory_1 = require("domain/collection/CollectionObjectFactory");
var CollectionPlaythroughObjectFactory_1 = require("domain/collection/CollectionPlaythroughObjectFactory");
var collection_rights_backend_api_service_1 = require("domain/collection/collection-rights-backend-api.service");
var CollectionRightsObjectFactory_1 = require("domain/collection/CollectionRightsObjectFactory");
var collection_validation_service_1 = require("domain/collection/collection-validation.service");
var compute_graph_service_1 = require("services/compute-graph.service");
var ConceptCardObjectFactory_1 = require("domain/skill/ConceptCardObjectFactory");
var context_service_1 = require("services/context.service");
var continue_validation_service_1 = require("interactions/Continue/directives/continue-validation.service");
var contribution_opportunities_backend_api_service_1 = require("pages/community-dashboard-page/services/contribution-opportunities-backend-api.service");
var construct_translation_ids_service_1 = require("services/construct-translation-ids.service");
var count_vectorizer_service_1 = require("classifiers/count-vectorizer.service");
var creator_dashboard_backend_api_service_1 = require("domain/creator_dashboard/creator-dashboard-backend-api.service");
var csrf_token_service_1 = require("services/csrf-token.service");
var current_interaction_service_1 = require("pages/exploration-player-page/services/current-interaction.service");
var date_time_format_service_1 = require("services/date-time-format.service");
var debouncer_service_1 = require("services/debouncer.service");
var device_info_service_1 = require("services/contextual/device-info.service");
var document_attribute_customization_service_1 = require("services/contextual/document-attribute-customization.service");
var drag_and_drop_sort_input_rules_service_1 = require("interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-rules.service");
var drag_and_drop_sort_input_validation_service_1 = require("interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-validation.service");
var editable_collection_backend_api_service_1 = require("domain/collection/editable-collection-backend-api.service");
var editability_service_1 = require("services/editability.service");
var editor_first_time_events_service_1 = require("pages/exploration-editor-page/services/editor-first-time-events.service");
var end_exploration_validation_service_1 = require("interactions/EndExploration/directives/end-exploration-validation.service");
var email_dashboard_data_service_1 = require("pages/email-dashboard-pages/email-dashboard-data.service");
var EntityContextObjectFactory_1 = require("domain/utilities/EntityContextObjectFactory");
var exploration_diff_service_1 = require("pages/exploration-editor-page/services/exploration-diff.service");
var ExplorationDraftObjectFactory_1 = require("domain/exploration/ExplorationDraftObjectFactory");
var exploration_features_backend_api_service_1 = require("services/exploration-features-backend-api.service");
var exploration_features_service_1 = require("services/exploration-features.service");
var exploration_html_formatter_service_1 = require("services/exploration-html-formatter.service");
var ExplorationMetadataObjectFactory_1 = require("domain/exploration/ExplorationMetadataObjectFactory");
var ExplorationObjectFactory_1 = require("domain/exploration/ExplorationObjectFactory");
var ExplorationOpportunitySummaryObjectFactory_1 = require("domain/opportunity/ExplorationOpportunitySummaryObjectFactory");
var expression_parser_service_1 = require("expressions/expression-parser.service");
var expression_syntax_tree_service_1 = require("expressions/expression-syntax-tree.service");
var extension_tag_assembler_service_1 = require("services/extension-tag-assembler.service");
var extract_image_filenames_from_state_service_1 = require("pages/exploration-player-page/services/extract-image-filenames-from-state.service");
var FeedbackMessageSummaryObjectFactory_1 = require("domain/feedback_message/FeedbackMessageSummaryObjectFactory");
var FeedbackThreadObjectFactory_1 = require("domain/feedback_thread/FeedbackThreadObjectFactory");
var FeedbackThreadSummaryObjectFactory_1 = require("domain/feedback_thread/FeedbackThreadSummaryObjectFactory");
var FileDownloadRequestObjectFactory_1 = require("domain/utilities/FileDownloadRequestObjectFactory");
var fraction_input_validation_service_1 = require("interactions/FractionInput/directives/fraction-input-validation.service");
var FractionObjectFactory_1 = require("domain/objects/FractionObjectFactory");
var generate_content_id_service_1 = require("services/generate-content-id.service");
var graph_input_validation_service_1 = require("interactions/GraphInput/directives/graph-input-validation.service");
var graph_utils_service_1 = require("interactions/GraphInput/directives/graph-utils.service");
var GuestCollectionProgressObjectFactory_1 = require("domain/collection/GuestCollectionProgressObjectFactory");
var guest_collection_progress_service_1 = require("domain/collection/guest-collection-progress.service");
var HintObjectFactory_1 = require("domain/exploration/HintObjectFactory");
var html_escaper_service_1 = require("services/html-escaper.service");
var id_generation_service_1 = require("services/id-generation.service");
var image_click_input_validation_service_1 = require("interactions/ImageClickInput/directives/image-click-input-validation.service");
var ImageFileObjectFactory_1 = require("domain/utilities/ImageFileObjectFactory");
var ImprovementActionButtonObjectFactory_1 = require("domain/statistics/ImprovementActionButtonObjectFactory");
var improvements_service_1 = require("services/improvements.service");
var interaction_details_cache_service_1 = require("pages/exploration-editor-page/editor-tab/services/interaction-details-cache.service");
var InteractionObjectFactory_1 = require("domain/exploration/InteractionObjectFactory");
var interaction_rules_registry_service_1 = require("services/interaction-rules-registry.service");
var interaction_specs_service_1 = require("services/interaction-specs.service");
var interactive_map_validation_service_1 = require("interactions/InteractiveMap/directives/interactive-map-validation.service");
var item_selection_input_validation_service_1 = require("interactions/ItemSelectionInput/directives/item-selection-input-validation.service");
var language_util_service_1 = require("domain/utilities/language-util.service");
var LearnerActionObjectFactory_1 = require("domain/statistics/LearnerActionObjectFactory");
var learner_answer_details_backend_api_service_1 = require("domain/statistics/learner-answer-details-backend-api.service");
var LearnerAnswerDetailsObjectFactory_1 = require("domain/statistics/LearnerAnswerDetailsObjectFactory");
var LearnerAnswerInfoObjectFactory_1 = require("domain/statistics/LearnerAnswerInfoObjectFactory");
var LearnerDashboardActivityIdsObjectFactory_1 = require("domain/learner_dashboard/LearnerDashboardActivityIdsObjectFactory");
var learner_dashboard_backend_api_service_1 = require("domain/learner_dashboard/learner-dashboard-backend-api.service");
var learner_dashboard_ids_backend_api_service_1 = require("domain/learner_dashboard/learner-dashboard-ids-backend-api.service");
var learner_params_service_1 = require("pages/exploration-player-page/services/learner-params.service");
var local_storage_service_1 = require("services/local-storage.service");
var loader_service_1 = require("services/loader.service");
var logger_service_1 = require("services/contextual/logger.service");
var logic_proof_validation_service_1 = require("interactions/LogicProof/directives/logic-proof-validation.service");
var LostChangeObjectFactory_1 = require("domain/exploration/LostChangeObjectFactory");
var math_expression_input_validation_service_1 = require("interactions/MathExpressionInput/directives/math-expression-input-validation.service");
var meta_tag_customization_service_1 = require("services/contextual/meta-tag-customization.service");
var MisconceptionObjectFactory_1 = require("domain/skill/MisconceptionObjectFactory");
var multiple_choice_input_validation_service_1 = require("interactions/MultipleChoiceInput/directives/multiple-choice-input-validation.service");
var music_notes_input_validation_service_1 = require("interactions/MusicNotesInput/directives/music-notes-input-validation.service");
var music_phrase_player_service_1 = require("interactions/MusicNotesInput/directives/music-phrase-player.service");
var NewlyCreatedTopicObjectFactory_1 = require("domain/topics_and_skills_dashboard/NewlyCreatedTopicObjectFactory");
var normalize_whitespace_pipe_1 = require("filters/string-utility-filters/normalize-whitespace.pipe");
var normalize_whitespace_punctuation_and_case_pipe_1 = require("filters/string-utility-filters/normalize-whitespace-punctuation-and-case.pipe");
var number_attempts_service_1 = require("pages/exploration-player-page/services/number-attempts.service");
var numeric_input_validation_service_1 = require("interactions/NumericInput/directives/numeric-input-validation.service");
var NumberWithUnitsObjectFactory_1 = require("domain/objects/NumberWithUnitsObjectFactory");
var OutcomeObjectFactory_1 = require("domain/exploration/OutcomeObjectFactory");
var page_title_service_1 = require("services/page-title.service");
var ParamChangeObjectFactory_1 = require("domain/exploration/ParamChangeObjectFactory");
var ParamChangesObjectFactory_1 = require("domain/exploration/ParamChangesObjectFactory");
var ParamMetadataObjectFactory_1 = require("domain/exploration/ParamMetadataObjectFactory");
var ParamSpecObjectFactory_1 = require("domain/exploration/ParamSpecObjectFactory");
var ParamSpecsObjectFactory_1 = require("domain/exploration/ParamSpecsObjectFactory");
var ParamTypeObjectFactory_1 = require("domain/exploration/ParamTypeObjectFactory");
var pencil_code_editor_rules_service_1 = require("interactions/PencilCodeEditor/directives/pencil-code-editor-rules.service");
var pencil_code_editor_validation_service_1 = require("interactions/PencilCodeEditor/directives/pencil-code-editor-validation.service");
var player_correctness_feedback_enabled_service_1 = require("pages/exploration-player-page/services/player-correctness-feedback-enabled.service");
var player_position_service_1 = require("pages/exploration-player-page/services/player-position.service");
var player_transcript_service_1 = require("pages/exploration-player-page/services/player-transcript.service");
var PlaythroughIssueObjectFactory_1 = require("domain/statistics/PlaythroughIssueObjectFactory");
var playthrough_issues_backend_api_service_1 = require("services/playthrough-issues-backend-api.service");
var PlaythroughObjectFactory_1 = require("domain/statistics/PlaythroughObjectFactory");
var playthrough_backend_api_service_1 = require("services/playthrough-backend-api.service");
var playthrough_service_1 = require("services/playthrough.service");
var prediction_algorithm_registry_service_1 = require("pages/exploration-player-page/services/prediction-algorithm-registry.service");
var PredictionResultObjectFactory_1 = require("domain/classifier/PredictionResultObjectFactory");
var pretest_question_backend_api_service_1 = require("domain/question/pretest-question-backend-api.service");
var python_program_tokenizer_1 = require("classifiers/python-program.tokenizer");
var question_backend_api_service_ts_1 = require("domain/question/question-backend-api.service.ts");
var question_creation_service_1 = require("components/entity-creation-services/question-creation.service");
var QuestionSummaryForOneSkillObjectFactory_1 = require("domain/question/QuestionSummaryForOneSkillObjectFactory");
var QuestionSummaryObjectFactory_1 = require("domain/question/QuestionSummaryObjectFactory");
var read_only_collection_backend_api_service_1 = require("domain/collection/read-only-collection-backend-api.service");
var rating_computation_service_1 = require("components/ratings/rating-computation/rating-computation.service");
var ReadOnlyStoryNodeObjectFactory_1 = require("domain/story_viewer/ReadOnlyStoryNodeObjectFactory");
var ReadOnlySubtopicPageObjectFactory_1 = require("domain/subtopic_viewer/ReadOnlySubtopicPageObjectFactory");
var read_only_topic_object_factory_1 = require("domain/topic_viewer/read-only-topic-object.factory");
var RecordedVoiceoversObjectFactory_1 = require("domain/exploration/RecordedVoiceoversObjectFactory");
var review_test_backend_api_service_1 = require("domain/review_test/review-test-backend-api.service");
var review_test_engine_service_ts_1 = require("pages/review-test-page/review-test-engine.service.ts");
var RubricObjectFactory_1 = require("domain/skill/RubricObjectFactory");
var RuleObjectFactory_1 = require("domain/exploration/RuleObjectFactory");
var schema_default_value_service_1 = require("services/schema-default-value.service");
var schema_undefined_last_element_service_1 = require("services/schema-undefined-last-element.service");
var search_explorations_backend_api_service_1 = require("domain/collection/search-explorations-backend-api.service");
var set_input_validation_service_1 = require("interactions/SetInput/directives/set-input-validation.service");
var svm_prediction_service_1 = require("classifiers/svm-prediction.service");
var sidebar_status_service_1 = require("domain/sidebar/sidebar-status.service");
var site_analytics_service_1 = require("services/site-analytics.service");
var skill_creation_backend_api_service_1 = require("domain/skill/skill-creation-backend-api.service");
var SkillDifficultyObjectFactory_1 = require("domain/skill/SkillDifficultyObjectFactory");
var skill_mastery_backend_api_service_1 = require("domain/skill/skill-mastery-backend-api.service");
var SkillObjectFactory_1 = require("domain/skill/SkillObjectFactory");
var SkillOpportunityObjectFactory_1 = require("domain/opportunity/SkillOpportunityObjectFactory");
var skill_rights_backend_api_service_ts_1 = require("domain/skill/skill-rights-backend-api.service.ts");
var SkillRightsObjectFactory_1 = require("domain/skill/SkillRightsObjectFactory");
var SkillSummaryObjectFactory_1 = require("domain/skill/SkillSummaryObjectFactory");
var SolutionObjectFactory_1 = require("domain/exploration/SolutionObjectFactory");
var solution_validity_service_1 = require("pages/exploration-editor-page/editor-tab/services/solution-validity.service");
var speech_synthesis_chunker_service_1 = require("services/speech-synthesis-chunker.service");
var StateCardObjectFactory_1 = require("domain/state_card/StateCardObjectFactory");
var state_classifier_mapping_service_1 = require("pages/exploration-player-page/services/state-classifier-mapping.service");
var state_content_service_1 = require("components/state-editor/state-editor-properties-services/state-content.service");
var state_customization_args_service_1 = require("components/state-editor/state-editor-properties-services/state-customization-args.service");
var state_editor_service_1 = require("components/state-editor/state-editor-properties-services/state-editor.service");
var graph_layout_service_1 = require("components/graph-services/graph-layout.service");
var state_hints_service_1 = require("components/state-editor/state-editor-properties-services/state-hints.service");
var state_improvement_suggestion_service_1 = require("pages/exploration-editor-page/statistics-tab/services/state-improvement-suggestion.service");
var state_interaction_id_service_1 = require("components/state-editor/state-editor-properties-services/state-interaction-id.service");
var state_interaction_stats_service_1 = require("services/state-interaction-stats.service");
var state_name_service_1 = require("components/state-editor/state-editor-properties-services/state-name.service");
var StateObjectFactory_1 = require("domain/state/StateObjectFactory");
var state_param_changes_service_1 = require("components/state-editor/state-editor-properties-services/state-param-changes.service");
var state_property_service_1 = require("components/state-editor/state-editor-properties-services/state-property.service");
var state_recorded_voiceovers_service_1 = require("components/state-editor/state-editor-properties-services/state-recorded-voiceovers.service");
var state_solicit_answer_details_service_1 = require("components/state-editor/state-editor-properties-services/state-solicit-answer-details.service");
var state_solution_service_1 = require("components/state-editor/state-editor-properties-services/state-solution.service");
var state_top_answers_stats_backend_api_service_1 = require("services/state-top-answers-stats-backend-api.service");
var state_written_translations_service_1 = require("components/state-editor/state-editor-properties-services/state-written-translations.service");
var StatesObjectFactory_1 = require("domain/exploration/StatesObjectFactory");
var StopwatchObjectFactory_1 = require("domain/utilities/StopwatchObjectFactory");
var StoryContentsObjectFactory_1 = require("domain/story/StoryContentsObjectFactory");
var StoryNodeObjectFactory_1 = require("domain/story/StoryNodeObjectFactory");
var StoryObjectFactory_1 = require("domain/story/StoryObjectFactory");
var StoryPlaythroughObjectFactory_1 = require("domain/story_viewer/StoryPlaythroughObjectFactory");
var StoryReferenceObjectFactory_1 = require("domain/topic/StoryReferenceObjectFactory");
var StorySummaryObjectFactory_1 = require("domain/story/StorySummaryObjectFactory");
var story_viewer_backend_api_service_1 = require("domain/story_viewer/story-viewer-backend-api.service");
var SubtitledHtmlObjectFactory_1 = require("domain/exploration/SubtitledHtmlObjectFactory");
var SubtopicObjectFactory_1 = require("domain/topic/SubtopicObjectFactory");
var SubtopicPageContentsObjectFactory_1 = require("domain/topic/SubtopicPageContentsObjectFactory");
var SubtopicPageObjectFactory_1 = require("domain/topic/SubtopicPageObjectFactory");
var subtopic_viewer_backend_api_service_1 = require("domain/subtopic_viewer/subtopic-viewer-backend-api.service");
var suggestion_modal_service_1 = require("services/suggestion-modal.service");
var SuggestionObjectFactory_1 = require("domain/suggestion/SuggestionObjectFactory");
var SuggestionThreadObjectFactory_1 = require("domain/suggestion/SuggestionThreadObjectFactory");
var suggestions_service_1 = require("services/suggestions.service");
var text_input_prediction_service_1 = require("interactions/TextInput/text-input-prediction.service");
var text_input_rules_service_1 = require("interactions/TextInput/directives/text-input-rules.service");
var text_input_tokenizer_1 = require("classifiers/text-input.tokenizer");
var text_input_validation_service_1 = require("interactions/TextInput/directives/text-input-validation.service");
var ThreadMessageObjectFactory_1 = require("domain/feedback_message/ThreadMessageObjectFactory");
var ThreadMessageSummaryObjectFactory_1 = require("domain/feedback_message/ThreadMessageSummaryObjectFactory");
var thread_status_display_service_1 = require("pages/exploration-editor-page/feedback-tab/services/thread-status-display.service");
var topic_creation_backend_api_service_ts_1 = require("domain/topic/topic-creation-backend-api.service.ts");
var TopicObjectFactory_1 = require("domain/topic/TopicObjectFactory");
var TopicRightsObjectFactory_1 = require("domain/topic/TopicRightsObjectFactory");
var topics_and_skills_dashboard_backend_api_service_1 = require("domain/topics_and_skills_dashboard/topics-and-skills-dashboard-backend-api.service");
var TopicSummaryObjectFactory_1 = require("domain/topic/TopicSummaryObjectFactory");
var TopicsAndSkillsDashboardFilterObjectFactory_1 = require("domain/topics_and_skills_dashboard/TopicsAndSkillsDashboardFilterObjectFactory");
var topics_and_skills_dashboard_page_service_1 = require("pages/topics-and-skills-dashboard-page/topics-and-skills-dashboard-page.service");
var topic_viewer_backend_api_service_1 = require("domain/topic_viewer/topic-viewer-backend-api.service");
var UnitsObjectFactory_1 = require("domain/objects/UnitsObjectFactory");
var url_interpolation_service_1 = require("domain/utilities/url-interpolation.service");
var url_service_1 = require("services/contextual/url.service");
var user_exploration_permissions_service_1 = require("pages/exploration-editor-page/services/user-exploration-permissions.service");
var UserInfoObjectFactory_1 = require("domain/user/UserInfoObjectFactory");
var utils_service_1 = require("services/utils.service");
var validators_service_1 = require("services/validators.service");
var version_tree_service_1 = require("pages/exploration-editor-page/history-tab/services/version-tree.service");
var VoiceoverObjectFactory_1 = require("domain/exploration/VoiceoverObjectFactory");
var window_dimensions_service_1 = require("services/contextual/window-dimensions.service");
var window_ref_service_1 = require("services/contextual/window-ref.service");
var winnowing_preprocessing_service_1 = require("classifiers/winnowing-preprocessing.service");
var WorkedExampleObjectFactory_1 = require("domain/skill/WorkedExampleObjectFactory");
var WrittenTranslationObjectFactory_1 = require("domain/exploration/WrittenTranslationObjectFactory");
var WrittenTranslationsObjectFactory_1 = require("domain/exploration/WrittenTranslationsObjectFactory");
var UpgradedServices = /** @class */ (function () {
    function UpgradedServices() {
    }
    UpgradedServices.prototype.getUpgradedServices = function () {
        var upgradedServices = {};
        /* eslint-disable dot-notation */
        // Topological level: 0.
        upgradedServices['AdminRouterService'] = new admin_router_service_ts_1.AdminRouterService();
        upgradedServices['AdminTaskManagerService'] =
            new admin_task_manager_service_1.AdminTaskManagerService();
        upgradedServices['AngularNameService'] = new angular_name_service_1.AngularNameService();
        upgradedServices['AnswerClassificationResultObjectFactory'] =
            new AnswerClassificationResultObjectFactory_1.AnswerClassificationResultObjectFactory();
        upgradedServices['AnswerGroupsCacheService'] =
            new answer_groups_cache_service_1.AnswerGroupsCacheService();
        upgradedServices['AnswerStatsObjectFactory'] =
            new AnswerStatsObjectFactory_1.AnswerStatsObjectFactory();
        upgradedServices['AppService'] = new app_service_1.AppService();
        upgradedServices['AudioBarStatusService'] = new audio_bar_status_service_1.AudioBarStatusService();
        upgradedServices['AudioFileObjectFactory'] = new AudioFileObjectFactory_1.AudioFileObjectFactory();
        upgradedServices['AudioLanguageObjectFactory'] =
            new AudioLanguageObjectFactory_1.AudioLanguageObjectFactory();
        upgradedServices['AudioTranslationManagerService'] =
            new audio_translation_manager_service_1.AudioTranslationManagerService();
        upgradedServices['AutogeneratedAudioLanguageObjectFactory'] =
            new AutogeneratedAudioLanguageObjectFactory_1.AutogeneratedAudioLanguageObjectFactory();
        upgradedServices['AutoplayedVideosService'] = new autoplayed_videos_service_1.AutoplayedVideosService();
        upgradedServices['BackgroundMaskService'] = new background_mask_service_1.BackgroundMaskService();
        upgradedServices['baseInteractionValidationService'] =
            new base_interaction_validation_service_1.baseInteractionValidationService();
        upgradedServices['BrowserCheckerService'] =
            new browser_checker_service_1.BrowserCheckerService(new window_ref_service_1.WindowRef());
        upgradedServices['CamelCaseToHyphensPipe'] = new camel_case_to_hyphens_pipe_1.CamelCaseToHyphensPipe();
        upgradedServices['ChangeObjectFactory'] = new ChangeObjectFactory_1.ChangeObjectFactory();
        upgradedServices['ClassifierObjectFactory'] = new ClassifierObjectFactory_1.ClassifierObjectFactory();
        upgradedServices['CodeNormalizerService'] = new code_normalizer_service_1.CodeNormalizerService();
        upgradedServices['CollectionNodeObjectFactory'] =
            new CollectionNodeObjectFactory_1.CollectionNodeObjectFactory();
        upgradedServices['CollectionPlaythroughObjectFactory'] =
            new CollectionPlaythroughObjectFactory_1.CollectionPlaythroughObjectFactory();
        upgradedServices['CollectionRightsObjectFactory'] =
            new CollectionRightsObjectFactory_1.CollectionRightsObjectFactory();
        upgradedServices['CollectionValidationService'] =
            new collection_validation_service_1.CollectionValidationService();
        upgradedServices['ComputeGraphService'] = new compute_graph_service_1.ComputeGraphService();
        upgradedServices['ConstructTranslationIdsService'] =
            new construct_translation_ids_service_1.ConstructTranslationIdsService();
        upgradedServices['CountVectorizerService'] = new count_vectorizer_service_1.CountVectorizerService();
        upgradedServices['CsrfTokenService'] = new csrf_token_service_1.CsrfTokenService();
        upgradedServices['DateTimeFormatService'] = new date_time_format_service_1.DateTimeFormatService();
        upgradedServices['DebouncerService'] = new debouncer_service_1.DebouncerService();
        upgradedServices['DragAndDropSortInputRulesService'] =
            new drag_and_drop_sort_input_rules_service_1.DragAndDropSortInputRulesService();
        upgradedServices['EditabilityService'] = new editability_service_1.EditabilityService();
        upgradedServices['EmailDashboardDataService'] =
            new email_dashboard_data_service_1.EmailDashboardDataService(new http_1.HttpClient(new http_1.HttpXhrBackend(new http_1.ɵangular_packages_common_http_http_d())));
        upgradedServices['EntityContextObjectFactory'] =
            new EntityContextObjectFactory_1.EntityContextObjectFactory();
        upgradedServices['ExplorationDiffService'] = new exploration_diff_service_1.ExplorationDiffService();
        upgradedServices['ExplorationDraftObjectFactory'] =
            new ExplorationDraftObjectFactory_1.ExplorationDraftObjectFactory();
        upgradedServices['ExplorationFeaturesService'] =
            new exploration_features_service_1.ExplorationFeaturesService();
        upgradedServices['ExplorationMetadataObjectFactory'] =
            new ExplorationMetadataObjectFactory_1.ExplorationMetadataObjectFactory();
        upgradedServices['ExplorationOpportunitySummaryObjectFactory'] =
            new ExplorationOpportunitySummaryObjectFactory_1.ExplorationOpportunitySummaryObjectFactory();
        upgradedServices['ExpressionParserService'] = new expression_parser_service_1.ExpressionParserService();
        upgradedServices['FeedbackMessageSummaryObjectFactory'] =
            new FeedbackMessageSummaryObjectFactory_1.FeedbackMessageSummaryObjectFactory();
        upgradedServices['FeedbackThreadSummaryObjectFactory'] =
            new FeedbackThreadSummaryObjectFactory_1.FeedbackThreadSummaryObjectFactory();
        upgradedServices['FileDownloadRequestObjectFactory'] =
            new FileDownloadRequestObjectFactory_1.FileDownloadRequestObjectFactory();
        upgradedServices['FractionObjectFactory'] = new FractionObjectFactory_1.FractionObjectFactory();
        upgradedServices['GenerateContentIdService'] =
            new generate_content_id_service_1.GenerateContentIdService();
        upgradedServices['GraphUtilsService'] = new graph_utils_service_1.GraphUtilsService();
        upgradedServices['GuestCollectionProgressObjectFactory'] =
            new GuestCollectionProgressObjectFactory_1.GuestCollectionProgressObjectFactory();
        upgradedServices['IdGenerationService'] = new id_generation_service_1.IdGenerationService();
        upgradedServices['ImageFileObjectFactory'] = new ImageFileObjectFactory_1.ImageFileObjectFactory();
        upgradedServices['ImprovementActionButtonObjectFactory'] =
            new ImprovementActionButtonObjectFactory_1.ImprovementActionButtonObjectFactory();
        upgradedServices['ImprovementsService'] = new improvements_service_1.ImprovementsService();
        upgradedServices['InteractionDetailsCacheService'] =
            new interaction_details_cache_service_1.InteractionDetailsCacheService();
        upgradedServices['InteractionSpecsService'] = new interaction_specs_service_1.InteractionSpecsService();
        upgradedServices['LearnerActionObjectFactory'] =
            new LearnerActionObjectFactory_1.LearnerActionObjectFactory();
        upgradedServices['LearnerAnswerDetailsObjectFactory'] =
            new LearnerAnswerDetailsObjectFactory_1.LearnerAnswerDetailsObjectFactory();
        upgradedServices['LearnerAnswerInfoObjectFactory'] =
            new LearnerAnswerInfoObjectFactory_1.LearnerAnswerInfoObjectFactory();
        upgradedServices['LearnerDashboardActivityIdsObjectFactory'] =
            new LearnerDashboardActivityIdsObjectFactory_1.LearnerDashboardActivityIdsObjectFactory();
        upgradedServices['LearnerParamsService'] = new learner_params_service_1.LearnerParamsService();
        upgradedServices['LoaderService'] = new loader_service_1.LoaderService();
        upgradedServices['LoggerService'] = new logger_service_1.LoggerService();
        upgradedServices['LostChangeObjectFactory'] = new LostChangeObjectFactory_1.LostChangeObjectFactory(new utils_service_1.UtilsService);
        upgradedServices['MisconceptionObjectFactory'] =
            new MisconceptionObjectFactory_1.MisconceptionObjectFactory();
        upgradedServices['MusicPhrasePlayerService'] =
            new music_phrase_player_service_1.MusicPhrasePlayerService();
        upgradedServices['NormalizeWhitespacePunctuationAndCasePipe'] =
            new normalize_whitespace_punctuation_and_case_pipe_1.NormalizeWhitespacePunctuationAndCasePipe();
        upgradedServices['NumberAttemptsService'] = new number_attempts_service_1.NumberAttemptsService();
        upgradedServices['NewlyCreatedTopicObjectFactory'] =
            new NewlyCreatedTopicObjectFactory_1.NewlyCreatedTopicObjectFactory();
        upgradedServices['ParamChangeObjectFactory'] =
            new ParamChangeObjectFactory_1.ParamChangeObjectFactory();
        upgradedServices['ParamMetadataObjectFactory'] =
            new ParamMetadataObjectFactory_1.ParamMetadataObjectFactory();
        upgradedServices['ParamTypeObjectFactory'] = new ParamTypeObjectFactory_1.ParamTypeObjectFactory();
        upgradedServices['PlayerCorrectnessFeedbackEnabledService'] =
            new player_correctness_feedback_enabled_service_1.PlayerCorrectnessFeedbackEnabledService();
        upgradedServices['PlaythroughIssueObjectFactory'] =
            new PlaythroughIssueObjectFactory_1.PlaythroughIssueObjectFactory();
        upgradedServices['PredictionResultObjectFactory'] =
            new PredictionResultObjectFactory_1.PredictionResultObjectFactory();
        upgradedServices['QuestionSummaryObjectFactory'] =
            new QuestionSummaryObjectFactory_1.QuestionSummaryObjectFactory();
        upgradedServices['RatingComputationService'] =
            new rating_computation_service_1.RatingComputationService();
        upgradedServices['ReadOnlyStoryNodeObjectFactory'] =
            new ReadOnlyStoryNodeObjectFactory_1.ReadOnlyStoryNodeObjectFactory();
        upgradedServices['ReviewTestEngineService'] = new review_test_engine_service_ts_1.ReviewTestEngineService();
        upgradedServices['RubricObjectFactory'] =
            new RubricObjectFactory_1.RubricObjectFactory();
        upgradedServices['RuleObjectFactory'] = new RuleObjectFactory_1.RuleObjectFactory();
        upgradedServices['SchemaUndefinedLastElementService'] =
            new schema_undefined_last_element_service_1.SchemaUndefinedLastElementService();
        upgradedServices['SkillDifficultyObjectFactory'] =
            new SkillDifficultyObjectFactory_1.SkillDifficultyObjectFactory();
        upgradedServices['SkillOpportunityObjectFactory'] =
            new SkillOpportunityObjectFactory_1.SkillOpportunityObjectFactory();
        upgradedServices['SkillRightsObjectFactory'] =
            new SkillRightsObjectFactory_1.SkillRightsObjectFactory();
        upgradedServices['SkillSummaryObjectFactory'] =
            new SkillSummaryObjectFactory_1.SkillSummaryObjectFactory();
        upgradedServices['SpeechSynthesisChunkerService'] =
            new speech_synthesis_chunker_service_1.SpeechSynthesisChunkerService();
        upgradedServices['SolutionValidityService'] = new solution_validity_service_1.SolutionValidityService();
        upgradedServices['StateGraphLayoutService'] = new graph_layout_service_1.StateGraphLayoutService();
        upgradedServices['StateImprovementSuggestionService'] =
            new state_improvement_suggestion_service_1.StateImprovementSuggestionService();
        upgradedServices['StateNameService'] = new state_name_service_1.StateNameService();
        upgradedServices['StopwatchObjectFactory'] = new StopwatchObjectFactory_1.StopwatchObjectFactory();
        upgradedServices['StoryNodeObjectFactory'] = new StoryNodeObjectFactory_1.StoryNodeObjectFactory();
        upgradedServices['StoryReferenceObjectFactory'] =
            new StoryReferenceObjectFactory_1.StoryReferenceObjectFactory();
        upgradedServices['StorySummaryObjectFactory'] =
            new StorySummaryObjectFactory_1.StorySummaryObjectFactory();
        upgradedServices['SubtitledHtmlObjectFactory'] =
            new SubtitledHtmlObjectFactory_1.SubtitledHtmlObjectFactory();
        upgradedServices['SuggestionModalService'] = new suggestion_modal_service_1.SuggestionModalService();
        upgradedServices['SuggestionsService'] = new suggestions_service_1.SuggestionsService();
        upgradedServices['TextInputTokenizer'] = new text_input_tokenizer_1.TextInputTokenizer();
        upgradedServices['ThreadMessageSummaryObjectFactory'] =
            new ThreadMessageSummaryObjectFactory_1.ThreadMessageSummaryObjectFactory();
        upgradedServices['ThreadStatusDisplayService'] =
            new thread_status_display_service_1.ThreadStatusDisplayService();
        upgradedServices['Title'] = new platform_browser_1.Title({});
        upgradedServices['TopicsAndSkillsDashboardFilterObjectFactory'] =
            new TopicsAndSkillsDashboardFilterObjectFactory_1.TopicsAndSkillsDashboardFilterObjectFactory();
        upgradedServices['TopicsAndSkillsDashboardPageService'] =
            new topics_and_skills_dashboard_page_service_1.TopicsAndSkillsDashboardPageService();
        upgradedServices['TopicRightsObjectFactory'] =
            new TopicRightsObjectFactory_1.TopicRightsObjectFactory();
        upgradedServices['TopicSummaryObjectFactory'] =
            new TopicSummaryObjectFactory_1.TopicSummaryObjectFactory();
        upgradedServices['UnitsObjectFactory'] = new UnitsObjectFactory_1.UnitsObjectFactory();
        upgradedServices['UserInfoObjectFactory'] = new UserInfoObjectFactory_1.UserInfoObjectFactory();
        upgradedServices['UtilsService'] = new utils_service_1.UtilsService();
        upgradedServices['VersionTreeService'] = new version_tree_service_1.VersionTreeService();
        upgradedServices['VoiceoverObjectFactory'] = new VoiceoverObjectFactory_1.VoiceoverObjectFactory();
        upgradedServices['WindowRef'] = new window_ref_service_1.WindowRef();
        upgradedServices['WinnowingPreprocessingService'] =
            new winnowing_preprocessing_service_1.WinnowingPreprocessingService();
        upgradedServices['WrittenTranslationObjectFactory'] =
            new WrittenTranslationObjectFactory_1.WrittenTranslationObjectFactory();
        upgradedServices['baseInteractionValidationService'] =
            new base_interaction_validation_service_1.baseInteractionValidationService();
        upgradedServices['ɵangular_packages_common_http_http_d'] =
            new http_1.ɵangular_packages_common_http_http_d();
        // Topological level: 1.
        upgradedServices['AlertsService'] = new alerts_service_1.AlertsService(upgradedServices['LoggerService']);
        upgradedServices['AutogeneratedAudioPlayerService'] =
            new autogenerated_audio_player_service_1.AutogeneratedAudioPlayerService(upgradedServices['SpeechSynthesisChunkerService']);
        upgradedServices['BrowserCheckerService'] = new browser_checker_service_1.BrowserCheckerService(upgradedServices['WindowRef']);
        upgradedServices['CodeReplValidationService'] =
            new code_repl_validation_service_1.CodeReplValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['CollectionObjectFactory'] =
            new CollectionObjectFactory_1.CollectionObjectFactory(upgradedServices['CollectionNodeObjectFactory']);
        upgradedServices['ContinueValidationService'] =
            new continue_validation_service_1.ContinueValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['DeviceInfoService'] = new device_info_service_1.DeviceInfoService(upgradedServices['WindowRef']);
        upgradedServices['DocumentAttributeCustomizationService'] =
            new document_attribute_customization_service_1.DocumentAttributeCustomizationService(upgradedServices['WindowRef']);
        upgradedServices['DragAndDropSortInputValidationService'] =
            new drag_and_drop_sort_input_validation_service_1.DragAndDropSortInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['EndExplorationValidationService'] =
            new end_exploration_validation_service_1.EndExplorationValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['ExpressionSyntaxTreeService'] =
            new expression_syntax_tree_service_1.ExpressionSyntaxTreeService(upgradedServices['ExpressionParserService']);
        upgradedServices['FeedbackThreadObjectFactory'] =
            new FeedbackThreadObjectFactory_1.FeedbackThreadObjectFactory(upgradedServices['ThreadMessageSummaryObjectFactory']);
        upgradedServices['FractionInputValidationService'] =
            new fraction_input_validation_service_1.FractionInputValidationService(upgradedServices['FractionObjectFactory'], upgradedServices['baseInteractionValidationService']);
        upgradedServices['GraphInputValidationService'] =
            new graph_input_validation_service_1.GraphInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['GuestCollectionProgressService'] =
            new guest_collection_progress_service_1.GuestCollectionProgressService(upgradedServices['GuestCollectionProgressObjectFactory'], upgradedServices['WindowRef']);
        upgradedServices['HintObjectFactory'] = new HintObjectFactory_1.HintObjectFactory(upgradedServices['SubtitledHtmlObjectFactory']);
        upgradedServices['HtmlEscaperService'] = new html_escaper_service_1.HtmlEscaperService(upgradedServices['LoggerService']);
        upgradedServices['HttpXhrBackend'] = new http_1.HttpXhrBackend(upgradedServices['ɵangular_packages_common_http_http_d']);
        upgradedServices['ImageClickInputValidationService'] =
            new image_click_input_validation_service_1.ImageClickInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['InteractiveMapValidationService'] =
            new interactive_map_validation_service_1.InteractiveMapValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['ItemSelectionInputValidationService'] =
            new item_selection_input_validation_service_1.ItemSelectionInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['LocalStorageService'] = new local_storage_service_1.LocalStorageService(upgradedServices['ExplorationDraftObjectFactory']);
        upgradedServices['LogicProofValidationService'] =
            new logic_proof_validation_service_1.LogicProofValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['MathExpressionInputValidationService'] =
            new math_expression_input_validation_service_1.MathExpressionInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['MetaTagCustomizationService'] =
            new meta_tag_customization_service_1.MetaTagCustomizationService(upgradedServices['WindowRef']);
        upgradedServices['MultipleChoiceInputValidationService'] =
            new multiple_choice_input_validation_service_1.MultipleChoiceInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['MusicNotesInputValidationService'] =
            new music_notes_input_validation_service_1.MusicNotesInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['NormalizeWhitespacePipe'] = new normalize_whitespace_pipe_1.NormalizeWhitespacePipe(upgradedServices['UtilsService']);
        upgradedServices['NumericInputValidationService'] =
            new numeric_input_validation_service_1.NumericInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['NumberWithUnitsObjectFactory'] =
            new NumberWithUnitsObjectFactory_1.NumberWithUnitsObjectFactory(upgradedServices['UnitsObjectFactory'], upgradedServices['FractionObjectFactory']);
        upgradedServices['OutcomeObjectFactory'] =
            new OutcomeObjectFactory_1.OutcomeObjectFactory(upgradedServices['SubtitledHtmlObjectFactory']);
        upgradedServices['PageTitleService'] = new page_title_service_1.PageTitleService(upgradedServices['Title']);
        upgradedServices['ParamChangesObjectFactory'] =
            new ParamChangesObjectFactory_1.ParamChangesObjectFactory(upgradedServices['ParamChangeObjectFactory']);
        upgradedServices['ParamMetadataObjectFactory'] =
            new ParamMetadataObjectFactory_1.ParamMetadataObjectFactory();
        upgradedServices['ParamSpecObjectFactory'] = new ParamSpecObjectFactory_1.ParamSpecObjectFactory(upgradedServices['ParamTypeObjectFactory']);
        upgradedServices['PencilCodeEditorValidationService'] =
            new pencil_code_editor_validation_service_1.PencilCodeEditorValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['PlayerTranscriptService'] = new player_transcript_service_1.PlayerTranscriptService(upgradedServices['LoggerService']);
        upgradedServices['PlaythroughObjectFactory'] = new PlaythroughObjectFactory_1.PlaythroughObjectFactory(upgradedServices['LearnerActionObjectFactory']);
        upgradedServices['PythonProgramTokenizer'] = new python_program_tokenizer_1.PythonProgramTokenizer(upgradedServices['LoggerService']);
        upgradedServices['QuestionSummaryForOneSkillObjectFactory'] =
            new QuestionSummaryForOneSkillObjectFactory_1.QuestionSummaryForOneSkillObjectFactory(upgradedServices['QuestionSummaryObjectFactory']);
        upgradedServices['RecordedVoiceoversObjectFactory'] =
            new RecordedVoiceoversObjectFactory_1.RecordedVoiceoversObjectFactory(upgradedServices['VoiceoverObjectFactory']);
        upgradedServices['SetInputValidationService'] =
            new set_input_validation_service_1.SetInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['SkillCreationBackendApiService'] =
            new skill_creation_backend_api_service_1.SkillCreationBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['SVMPredictionService'] = new svm_prediction_service_1.SVMPredictionService(upgradedServices['PredictionResultObjectFactory']);
        upgradedServices['SchemaDefaultValueService'] =
            new schema_default_value_service_1.SchemaDefaultValueService(upgradedServices['LoggerService']);
        upgradedServices['SiteAnalyticsService'] = new site_analytics_service_1.SiteAnalyticsService(upgradedServices['WindowRef']);
        upgradedServices['StateClassifierMappingService'] =
            new state_classifier_mapping_service_1.StateClassifierMappingService(upgradedServices['ClassifierObjectFactory']);
        upgradedServices['StateEditorService'] = new state_editor_service_1.StateEditorService(upgradedServices['SolutionValidityService']);
        upgradedServices['StoryContentsObjectFactory'] =
            new StoryContentsObjectFactory_1.StoryContentsObjectFactory(upgradedServices['StoryNodeObjectFactory']);
        upgradedServices['StoryPlaythroughObjectFactory'] =
            new StoryPlaythroughObjectFactory_1.StoryPlaythroughObjectFactory(upgradedServices['ReadOnlyStoryNodeObjectFactory']);
        upgradedServices['SubtopicObjectFactory'] = new SubtopicObjectFactory_1.SubtopicObjectFactory(upgradedServices['SkillSummaryObjectFactory']);
        upgradedServices['SuggestionObjectFactory'] = new SuggestionObjectFactory_1.SuggestionObjectFactory(upgradedServices['SuggestionsService']);
        upgradedServices['TextInputValidationService'] =
            new text_input_validation_service_1.TextInputValidationService(upgradedServices['baseInteractionValidationService']);
        upgradedServices['ThreadMessageObjectFactory'] =
            new ThreadMessageObjectFactory_1.ThreadMessageObjectFactory(upgradedServices['ThreadMessageSummaryObjectFactory']);
        upgradedServices['TopicsAndSkillsDashboardBackendApiService'] =
            new topics_and_skills_dashboard_backend_api_service_1.TopicsAndSkillsDashboardBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['TopicCreationBackendApiService'] =
            new topic_creation_backend_api_service_ts_1.TopicCreationBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['UrlService'] = new url_service_1.UrlService(upgradedServices['WindowRef']);
        upgradedServices['WindowDimensionsService'] = new window_dimensions_service_1.WindowDimensionsService(upgradedServices['WindowRef']);
        upgradedServices['WorkedExampleObjectFactory'] =
            new WorkedExampleObjectFactory_1.WorkedExampleObjectFactory(upgradedServices['SubtitledHtmlObjectFactory']);
        upgradedServices['WrittenTranslationsObjectFactory'] =
            new WrittenTranslationsObjectFactory_1.WrittenTranslationsObjectFactory(upgradedServices['WrittenTranslationObjectFactory']);
        // Topological level: 2.
        upgradedServices['AnswerGroupObjectFactory'] = new AnswerGroupObjectFactory_1.AnswerGroupObjectFactory(upgradedServices['OutcomeObjectFactory'], upgradedServices['RuleObjectFactory']);
        upgradedServices['CodeReplPredictionService'] =
            new code_repl_prediction_service_1.CodeReplPredictionService(upgradedServices['CountVectorizerService'], upgradedServices['PythonProgramTokenizer'], upgradedServices['SVMPredictionService'], upgradedServices['WinnowingPreprocessingService']);
        upgradedServices['CodeReplRulesService'] = new code_repl_rules_service_1.CodeReplRulesService(upgradedServices['NormalizeWhitespacePipe'], upgradedServices['CodeNormalizerService']);
        upgradedServices['ConceptCardObjectFactory'] = new ConceptCardObjectFactory_1.ConceptCardObjectFactory(upgradedServices['SubtitledHtmlObjectFactory'], upgradedServices['RecordedVoiceoversObjectFactory'], upgradedServices['WorkedExampleObjectFactory']);
        upgradedServices['ContextService'] = new context_service_1.ContextService(upgradedServices['UrlService'], upgradedServices['EntityContextObjectFactory']);
        upgradedServices['EditorFirstTimeEventsService'] =
            new editor_first_time_events_service_1.EditorFirstTimeEventsService(upgradedServices['SiteAnalyticsService']);
        upgradedServices['ExtensionTagAssemblerService'] =
            new extension_tag_assembler_service_1.ExtensionTagAssemblerService(upgradedServices['HtmlEscaperService'], upgradedServices['CamelCaseToHyphensPipe']);
        upgradedServices['ExtractImageFilenamesFromStateService'] =
            new extract_image_filenames_from_state_service_1.ExtractImageFilenamesFromStateService(upgradedServices['HtmlEscaperService']);
        upgradedServices['HttpClient'] = new http_1.HttpClient(upgradedServices['HttpXhrBackend']);
        upgradedServices['LanguageUtilService'] = new language_util_service_1.LanguageUtilService(upgradedServices['AudioLanguageObjectFactory'], upgradedServices['AutogeneratedAudioLanguageObjectFactory'], upgradedServices['BrowserCheckerService']);
        upgradedServices['NumberWithUnitsValidationService'] =
            new NumberWithUnitsObjectFactory_1.NumberWithUnitsObjectFactory(upgradedServices['NumberWithUnitsObjectFactory'], upgradedServices['baseInteractionValidationService']);
        upgradedServices['ParamSpecsObjectFactory'] = new ParamSpecsObjectFactory_1.ParamSpecsObjectFactory(upgradedServices['ParamSpecObjectFactory']);
        upgradedServices['PencilCodeEditorRulesService'] =
            new pencil_code_editor_rules_service_1.PencilCodeEditorRulesService(upgradedServices['NormalizeWhitespacePipe'], upgradedServices['NormalizeWhitespacePunctuationAndCasePipe'], upgradedServices['CodeNormalizerService']);
        upgradedServices['SidebarStatusService'] = new sidebar_status_service_1.SidebarStatusService(upgradedServices['WindowDimensionsService']);
        upgradedServices['StateContentService'] = new state_content_service_1.StateContentService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateCustomizationArgsService'] =
            new state_customization_args_service_1.StateCustomizationArgsService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateHintsService'] = new state_hints_service_1.StateHintsService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateInteractionIdService'] =
            new state_interaction_id_service_1.StateInteractionIdService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StatePropertyService'] = new state_property_service_1.StatePropertyService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateRecordedVoiceoversService'] =
            new state_recorded_voiceovers_service_1.StateRecordedVoiceoversService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateSolicitAnswerDetailsService'] =
            new state_solicit_answer_details_service_1.StateSolicitAnswerDetailsService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateSolutionService'] = new state_solution_service_1.StateSolutionService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StateWrittenTranslationsService'] =
            new state_written_translations_service_1.StateWrittenTranslationsService(upgradedServices['AlertsService'], upgradedServices['UtilsService']);
        upgradedServices['StoryObjectFactory'] =
            new StoryObjectFactory_1.StoryObjectFactory(upgradedServices['StoryContentsObjectFactory']);
        upgradedServices['SuggestionThreadObjectFactory'] =
            new SuggestionThreadObjectFactory_1.SuggestionThreadObjectFactory(upgradedServices['SuggestionObjectFactory'], upgradedServices['ThreadMessageSummaryObjectFactory']);
        upgradedServices['TextInputRulesService'] = new text_input_rules_service_1.TextInputRulesService(upgradedServices['NormalizeWhitespacePipe']);
        upgradedServices['TopicObjectFactory'] = new TopicObjectFactory_1.TopicObjectFactory(upgradedServices['SubtopicObjectFactory'], upgradedServices['StoryReferenceObjectFactory'], upgradedServices['SkillSummaryObjectFactory']);
        upgradedServices['UrlInterpolationService'] = new url_interpolation_service_1.UrlInterpolationService(upgradedServices['AlertsService'], upgradedServices['UrlService'], upgradedServices['UtilsService']);
        upgradedServices['ValidatorsService'] = new validators_service_1.ValidatorsService(upgradedServices['AlertsService'], upgradedServices['NormalizeWhitespacePipe']);
        // Topological level: 3.
        upgradedServices['AdminDataService'] = new admin_data_service_1.AdminDataService(upgradedServices['HttpClient']);
        upgradedServices['InteractionRulesRegistryService'] =
            new interaction_rules_registry_service_1.InteractionRulesRegistryService(upgradedServices['CodeReplRulesService'], upgradedServices['ContinueRulesService'], upgradedServices['DragAndDropSortInputRulesService'], upgradedServices['EndExplorationRulesService'], upgradedServices['FractionInputRulesService'], upgradedServices['GraphInputRulesService'], upgradedServices['ImageClickInputRulesService'], upgradedServices['InteractiveMapRulesService'], upgradedServices['ItemSelectionInputRulesService'], upgradedServices['LogicProofRulesService'], upgradedServices['MathExpressionInputRulesService'], upgradedServices['MultipleChoiceInputRulesService'], upgradedServices['MusicNotesInputRulesService'], upgradedServices['NumberWithUnitsRulesService'], upgradedServices['NumericInputRulesService'], upgradedServices['PencilCodeEditorRulesService'], upgradedServices['SetInputRulesService'], upgradedServices['TextInputRulesService']);
        upgradedServices['AudioTranslationLanguageService'] =
            new audio_translation_language_service_1.AudioTranslationLanguageService(upgradedServices['BrowserCheckerService'], upgradedServices['LanguageUtilService']);
        upgradedServices['ClassroomBackendApiService'] =
            new classroom_backend_api_service_1.ClassroomBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient'], upgradedServices['TopicSummaryObjectFactory']);
        upgradedServices['CollectionCreationBackendService'] = (new collection_creation_backend_api_service_1.CollectionCreationBackendService(upgradedServices['HttpClient']));
        upgradedServices['CollectionRightsBackendApiService'] =
            new collection_rights_backend_api_service_1.CollectionRightsBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['ContributionOpportunitiesBackendApiService'] =
            new contribution_opportunities_backend_api_service_1.ContributionOpportunitiesBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['CreatorDashboardBackendApiService'] =
            new creator_dashboard_backend_api_service_1.CreatorDashboardBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['CurrentInteractionService'] =
            new current_interaction_service_1.CurrentInteractionService(upgradedServices['ContextService'], upgradedServices['PlayerPositionService'], upgradedServices['PlayerTranscriptService']);
        upgradedServices['EmailDashboardDataService'] =
            new email_dashboard_data_service_1.EmailDashboardDataService(upgradedServices['HttpClient']);
        upgradedServices['ExplorationFeaturesBackendApiService'] =
            new exploration_features_backend_api_service_1.ExplorationFeaturesBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['ExplorationHtmlFormatterService'] =
            new exploration_html_formatter_service_1.ExplorationHtmlFormatterService(upgradedServices['CamelCaseToHyphensPipe'], upgradedServices['ExtensionTagAssemblerService'], upgradedServices['HtmlEscaperService']);
        upgradedServices['LearnerAnswerDetailsBackendApiService'] =
            new learner_answer_details_backend_api_service_1.LearnerAnswerDetailsBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['LearnerDashboardBackendApiService'] =
            new learner_dashboard_backend_api_service_1.LearnerDashboardBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['LearnerDashboardIdsBackendApiService'] =
            new learner_dashboard_ids_backend_api_service_1.LearnerDashboardIdsBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['PlayerPositionService'] = new player_position_service_1.PlayerPositionService(upgradedServices['ContextService'], upgradedServices['PlayerTranscriptService']);
        upgradedServices['PlaythroughBackendApiService'] =
            new playthrough_backend_api_service_1.PlaythroughBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['PlaythroughIssuesBackendApiService'] =
            new playthrough_issues_backend_api_service_1.PlaythroughIssuesBackendApiService(upgradedServices['HttpClient'], upgradedServices['PlaythroughIssuesBackendApiService'], upgradedServices['UrlInterpolationService']);
        upgradedServices['PretestQuestionBackendApiService'] =
            new pretest_question_backend_api_service_1.PretestQuestionBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['QuestionBackendApiService'] =
            new question_backend_api_service_ts_1.QuestionBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['QuestionCreationService'] =
            new question_creation_service_1.QuestionCreationService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['ReadOnlyCollectionBackendApiService'] =
            new read_only_collection_backend_api_service_1.ReadOnlyCollectionBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['ReadOnlyTopicObjectFactory'] =
            new read_only_topic_object_factory_1.ReadOnlyTopicObjectFactory(upgradedServices['SubtopicObjectFactory'], upgradedServices['SkillSummaryObjectFactory']);
        upgradedServices['ReviewTestBackendApiService'] =
            new review_test_backend_api_service_1.ReviewTestBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['SearchExplorationsBackendApiService'] =
            new search_explorations_backend_api_service_1.SearchExplorationsBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['SkillCreationBackendApiService'] =
            new skill_creation_backend_api_service_1.SkillCreationBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['SkillMasteryBackendApiService'] =
            new skill_mastery_backend_api_service_1.SkillMasteryBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['SkillObjectFactory'] =
            new SkillObjectFactory_1.SkillObjectFactory(upgradedServices['ConceptCardObjectFactory'], upgradedServices['MisconceptionObjectFactory'], upgradedServices['RubricObjectFactory'], upgradedServices['ValidatorsService']);
        upgradedServices['SkillRightsBackendApiService'] =
            new skill_rights_backend_api_service_ts_1.SkillRightsBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['StateCardObjectFactory'] =
            new StateCardObjectFactory_1.StateCardObjectFactory(upgradedServices['AudioTranslationLanguageService']);
        upgradedServices['StateParamChangesService'] =
            new state_param_changes_service_1.StateParamChangesService(upgradedServices['AlertsService'], upgradedServices['UrlInterpolationService']);
        upgradedServices['StateTopAnswersStatsBackendApiService'] =
            new state_top_answers_stats_backend_api_service_1.StateTopAnswersStatsBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['StoryViewerBackendApiService'] =
            new story_viewer_backend_api_service_1.StoryViewerBackendApiService(upgradedServices['UrlInterpolationService'], upgradedServices['HttpClient']);
        upgradedServices['SubtopicPageContentsObjectFactory'] =
            new SubtopicPageContentsObjectFactory_1.SubtopicPageContentsObjectFactory(upgradedServices['RecordedVoiceoversObjectFactory'], upgradedServices['SubtitledHtmlObjectFactory']);
        upgradedServices['TextInputPredictionService'] =
            new text_input_prediction_service_1.TextInputPredictionService(upgradedServices['CountVectorizerService'], upgradedServices['SVMPredictionService'], upgradedServices['TextInputTokenizer']);
        upgradedServices['TopicObjectFactory'] = new TopicObjectFactory_1.TopicObjectFactory(upgradedServices['SubtopicObjectFactory'], upgradedServices['StoryReferenceObjectFactory'], upgradedServices['SkillSummaryObjectFactory']);
        upgradedServices['TopicCreationBackendApiService'] =
            new topic_creation_backend_api_service_ts_1.TopicCreationBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['TopicsAndSkillsDashboardBackendApiService'] =
            new topics_and_skills_dashboard_backend_api_service_1.TopicsAndSkillsDashboardBackendApiService(upgradedServices['HttpClient']);
        upgradedServices['TopicViewerBackendApiService'] =
            new topic_viewer_backend_api_service_1.TopicViewerBackendApiService(upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']);
        upgradedServices['UserExplorationPermissionsService'] = (new user_exploration_permissions_service_1.UserExplorationPermissionsService(upgradedServices['ContextService'], upgradedServices['HttpClient'], upgradedServices['UrlInterpolationService']));
        // Topological level: 4.
        upgradedServices['CollectionCreationService'] =
            new collection_creation_service_1.CollectionCreationService(upgradedServices['CollectionCreationBackendService'], upgradedServices['AlertsService'], upgradedServices['SiteAnalyticsService'], upgradedServices['UrlInterpolationService'], upgradedServices['LoaderService'], upgradedServices['WindowRef']);
        upgradedServices['EditableCollectionBackendApiService'] =
            new editable_collection_backend_api_service_1.EditableCollectionBackendApiService(upgradedServices['HttpClient'], upgradedServices['ReadOnlyCollectionBackendApiService'], upgradedServices['UrlInterpolationService']);
        upgradedServices['PlaythroughService'] =
            new playthrough_service_1.PlaythroughService(upgradedServices['ExplorationFeaturesService'], upgradedServices['LearnerActionObjectFactory'], upgradedServices['PlaythroughBackendApiService'], upgradedServices['PlaythroughObjectFactory'], upgradedServices['StopwatchObjectFactory']);
        upgradedServices['PredictionAlgorithmRegistryService'] =
            new prediction_algorithm_registry_service_1.PredictionAlgorithmRegistryService(upgradedServices['CodeReplPredictionService'], upgradedServices['TextInputPredictionService']);
        upgradedServices['ReadOnlySubtopicPageObjectFactory'] =
            new ReadOnlySubtopicPageObjectFactory_1.ReadOnlySubtopicPageObjectFactory(upgradedServices['SubtopicPageContentsObjectFactory']);
        upgradedServices['SolutionObjectFactory'] = new SolutionObjectFactory_1.SolutionObjectFactory(upgradedServices['SubtitledHtmlObjectFactory'], upgradedServices['ExplorationHtmlFormatterService']);
        upgradedServices['StateCardObjectFactory'] = new StateCardObjectFactory_1.StateCardObjectFactory(upgradedServices['AudioTranslationLanguageService']);
        upgradedServices['SubtopicPageObjectFactory'] =
            new SubtopicPageObjectFactory_1.SubtopicPageObjectFactory(upgradedServices['SubtopicPageContentsObjectFactory']);
        // Topological level: 5.
        upgradedServices['AnswerClassificationService'] =
            new answer_classification_service_1.AnswerClassificationService(upgradedServices['AlertsService'], upgradedServices['AnswerClassificationResultObjectFactory'], upgradedServices['AppService'], upgradedServices['InteractionSpecsService'], upgradedServices['PredictionAlgorithmRegistryService'], upgradedServices['StateClassifierMappingService']);
        upgradedServices['InteractionObjectFactory'] = new InteractionObjectFactory_1.InteractionObjectFactory(upgradedServices['AnswerGroupObjectFactory'], upgradedServices['HintObjectFactory'], upgradedServices['SolutionObjectFactory'], upgradedServices['OutcomeObjectFactory']);
        upgradedServices['SubtopicViewerBackendApiService'] =
            new subtopic_viewer_backend_api_service_1.SubtopicViewerBackendApiService(upgradedServices['HttpClient'], upgradedServices['ReadOnlySubtopicPageObjectFactory'], upgradedServices['UrlInterpolationService']);
        // Topological level: 6.
        upgradedServices['StateObjectFactory'] = new StateObjectFactory_1.StateObjectFactory(upgradedServices['InteractionObjectFactory'], upgradedServices['ParamChangesObjectFactory'], upgradedServices['RecordedVoiceoversObjectFactory'], upgradedServices['SubtitledHtmlObjectFactory'], upgradedServices['WrittenTranslationsObjectFactory']);
        upgradedServices['StateInteractionStatsService'] =
            new state_interaction_stats_service_1.StateInteractionStatsService(upgradedServices['AngularNameService'], upgradedServices['AnswerClassificationService'], upgradedServices['ContextService'], upgradedServices['FractionObjectFactory'], upgradedServices['HttpClient'], upgradedServices['InteractionRulesRegistryService'], upgradedServices['UrlInterpolationService']);
        // Topological level: 7.
        upgradedServices['StatesObjectFactory'] = new StatesObjectFactory_1.StatesObjectFactory(upgradedServices['StateObjectFactory']);
        // Topological level: 8.
        upgradedServices['ExplorationObjectFactory'] = new ExplorationObjectFactory_1.ExplorationObjectFactory(upgradedServices['LoggerService'], upgradedServices['ParamChangesObjectFactory'], upgradedServices['ParamSpecsObjectFactory'], upgradedServices['StatesObjectFactory'], upgradedServices['UrlInterpolationService']);
        /* eslint-enable dot-notation */
        return upgradedServices;
    };
    UpgradedServices = __decorate([
        core_1.Injectable({
            providedIn: 'root'
        })
    ], UpgradedServices);
    return UpgradedServices;
}());
exports.UpgradedServices = UpgradedServices;
angular.module('oppia').factory('UpgradedServices', static_1.downgradeInjectable(UpgradedServices));
