name: 'Install Dependencies'
description: 'Installs wheel and third-party dependencies.'
runs:
  using: 'composite'
  steps:
    - name: Setup python by installing wheel
      run: pip install wheel==0.35.0
      shell: bash
    - name: Install python 2 for GAE
      run: |
        sudo apt update
        sudo apt install python2 -y
      shell: bash
    - name: Check Yarn Cache
      run: |
        # Move outside repository root to ignore the configs in
        # oppia/.yarnrc. These configs specify that yarn should use the
        # Oppia-managed yarn executable, which hasn't been downloaded
        # yet.
        cd ..
        # Create a new .yarnrc file to check what is already in the
        # Oppia-managed yarn cache.
        echo 'cache-folder "yarn_cache"' > .yarnrc
        yarn cache list
        # Delete the .yarnrc file that we just created.
        rm .yarnrc
        # Move back to the repository root.
        cd -
      shell: bash
    - name: Install third party
      run: python -m scripts.install_third_party_libs
      shell: bash
    - name: Check Yarn Cache
      # Check the yarn cache again to see what packages were just
      # installed.
      run: yarn cache list
      shell: bash
