name: 'Install Dependencies'
description: 'Installs wheel, third-party python libs, and loads yarn cache.'
runs:
  using: 'composite'
  steps:
    - name: Setup python by installing wheel
      run: pip install wheel==0.35.0
      shell: bash
    - name: Check Yarn Cache
      run: |
        pwd
        cd ..
        pwd
        echo 'cache-folder "yarn_cache"' > .yarnrc
        yarn cache list
        rm .yarnrc
        cd -
      shell: bash
    - name: Install third party
      run: python -m scripts.install_third_party_libs
      shell: bash
    - name: Check Yarn Cache
      run: yarn cache list
      shell: bash
