title: "GSoC’23 Proposal Review | {{Project Name}} ({{Your Name}})"
body:
- type: input
  attributes:
    label: Google doc link to Proposal
    description: "Please paste the google doc link to the proposal here."
  validations:
    required: true
- type: checkboxes
  id: sharing
  attributes:
    label: I confirm that I set the sharing options of the document to “anyone with the link can comment”.
    options:
        - label: "Yes"
          required: true
- type: dropdown
  id: review-section
  attributes:
    label: Which section should the reviewer take a look at?
    options:
      - "3.1: WHAT"
      - "3.2: HOW"
  validations:
    required: true
- type: textarea
  id: additional
  attributes:
    label: Additional information
    description: |
        Add any other information about the proposal here.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
