# coding: utf-8
#
# Copyright 2024 The Oppia Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Unit tests for core.jobs.batch_jobs.voiceover_audit_jobs."""

from __future__ import annotations

from core import feconf
from core.domain import state_domain
from core.jobs import job_test_utils
from core.jobs.batch_jobs import voiceover_audit_jobs
from core.platform import models

MYPY = False
if MYPY:  # pragma: no cover
    from mypy_imports import (
        classroom_models, exp_models, story_models, topic_models, voiceover_models)

(
    classroom_models, exp_models, story_models, topic_models, voiceover_models
) = models.Registry.import_models([
    models.Names.CLASSROOM, models.Names.EXPLORATION, models.Names.STORY,
    models.Names.TOPIC, models.Names.VOICEOVER
])


class AuditMissingVoiceoversJobTests(job_test_utils.JobTestBase):
    """Tests for AuditMissingVoiceoversJob."""

    JOB_CLASS = voiceover_audit_jobs.AuditMissingVoiceoversJob

    def setUp(self) -> None:
        super().setUp()
        
        # Setup Policy.
        self.policy_model = voiceover_models.VoiceoverAutogenerationPolicyModel(
            id=voiceover_models.VOICEOVER_AUTOGENERATION_POLICY_ID,
            language_codes_mapping={'hi': {'hi-IN': True}},
            autogenerated_voiceovers_are_enabled=True
        )
        self.policy_model.update_timestamps()
        self.policy_model.put()

    def test_empty_storage(self) -> None:
        self.assert_job_output_is_empty()

    def test_non_curated_exploration_is_ignored(self) -> None:
        exp_model = self.create_model(
            exp_models.ExplorationModel,
            id='exp_1',
            title='Title',
            category='Category',
            objective='Objective',
            language_code='en',
            init_state_name='Introduction',
            states={
                'Introduction': state_domain.State.create_default_state(
                    'Introduction', 'content_0', 'Introduction'
                ).to_dict()
            },
            states_schema_version=feconf.CURRENT_STATES_SCHEMA_VERSION,
            version=1
        )
        exp_model.update_timestamps()
        exp_model.put()
        
        self.assert_job_output_is_empty()

    def test_curated_exploration_with_missing_voiceover_is_reported(self) -> None:
        # 1. Setup Classroom.
        classroom = self.create_model(
            classroom_models.ClassroomModel,
            id='class_1',
            name='Classroom',
            url_fragment='class',
            is_published=True,
            topic_id_to_prerequisite_topic_ids={'topic_1': []}
        )
        classroom.update_timestamps()
        classroom.put()
        
        # 2. Setup Topic.
        topic_rights = self.create_model(
            topic_models.TopicRightsModel,
            id='topic_1',
            topic_is_published=True
        )
        topic_rights.update_timestamps()
        topic_rights.put()
        
        topic = self.create_model(
            topic_models.TopicModel,
            id='topic_1',
            name='Topic Name',
            canonical_name='topic name',
            url_fragment='topic',
            canonical_story_references=[{'story_id': 'story_1', 'story_is_published': True}],
            next_subtopic_id=1,
            language_code='en',
            version=1
        )
        topic.update_timestamps()
        topic.put()
        
        # 3. Setup Story.
        story = self.create_model(
            story_models.StoryModel,
            id='story_1',
            title='Story Title',
            url_fragment='story',
            story_contents_schema_version=feconf.CURRENT_STORY_CONTENTS_SCHEMA_VERSION,
            story_contents={
                'nodes': [{
                    'id': 'node_1',
                    'title': 'Lesson Name',
                    'exploration_id': 'exp_1',
                    'destination_node_ids': [],
                    'prerequisite_skill_ids': [],
                    'acquired_skill_ids': [],
                    'outline': 'Outline',
                    'exploration_context_ids': []
                }],
                'initial_node_id': 'node_1',
                'next_node_id': 2
            },
            notes='Notes',
            description='Description',
            language_code='en',
            corresponding_topic_id='topic_1',
            version=1
        )
        story.update_timestamps()
        story.put()
        
        # 4. Setup Exploration.
        state_dict = state_domain.State.create_default_state(
            'Introduction', 'content_0', 'Introduction'
        ).to_dict()
        exp_model = self.create_model(
            exp_models.ExplorationModel,
            id='exp_1',
            title='Exp Title',
            category='Category',
            objective='Objective',
            language_code='en',
            init_state_name='Introduction',
            states={'Introduction': state_dict},
            states_schema_version=feconf.CURRENT_STATES_SCHEMA_VERSION,
            version=1
        )
        exp_model.update_timestamps()
        exp_model.put()
        
        # Initially, no voiceover model exists for exp_1 in hi-IN.
        # So it should be missing.
        
        expected_output = [
            'Total missing voiceovers found: 1',
            'Missing: Topic Name > Lesson Name > hi-IN > Introduction > content_0'
        ]
        self.assert_job_output_is(expected_output)

    def test_stale_voiceover_is_reported(self) -> None:
        # Re-use setup from above or similar.
        self.test_curated_exploration_with_missing_voiceover_is_reported()
        
        # Add a stale manual voiceover.
        voc_model = self.create_model(
            voiceover_models.EntityVoiceoversModel,
            id='exploration-exp_1-1-hi-IN',
            entity_type=feconf.ENTITY_TYPE_EXPLORATION,
            entity_id='exp_1',
            entity_version=1,
            language_accent_code='hi-IN',
            voiceovers_mapping={
                'content_0': {
                    'manual': {
                        'filename': 'hi.mp3',
                        'file_size_bytes': 100,
                        'needs_update': True, # STALE
                        'duration_secs': 1.0
                    },
                    'auto': None
                }
            },
            automated_voiceovers_audio_offsets_msecs={}
        )
        voc_model.update_timestamps()
        voc_model.put()
        
        # Still reported as missing because manual is stale and no auto.
        expected_output = [
            'Total missing voiceovers found: 1',
            'Missing: Topic Name > Lesson Name > hi-IN > Introduction > content_0'
        ]
        self.assert_job_output_is(expected_output)

    def test_valid_voiceover_is_not_reported(self) -> None:
        # Re-use setup.
        self.test_curated_exploration_with_missing_voiceover_is_reported()
        
        # Add a valid manual voiceover.
        voc_model = self.create_model(
            voiceover_models.EntityVoiceoversModel,
            id='exploration-exp_1-1-hi-IN',
            entity_type=feconf.ENTITY_TYPE_EXPLORATION,
            entity_id='exp_1',
            entity_version=1,
            language_accent_code='hi-IN',
            voiceovers_mapping={
                'content_0': {
                    'manual': {
                        'filename': 'hi.mp3',
                        'file_size_bytes': 100,
                        'needs_update': False,
                        'duration_secs': 1.0
                    },
                    'auto': None
                }
            },
            automated_voiceovers_audio_offsets_msecs={}
        )
        voc_model.update_timestamps()
        voc_model.put()
        
        self.assert_job_output_is(['Total missing voiceovers found: 0'])

    def test_auto_voiceover_is_not_reported_as_missing(self) -> None:
        self.test_curated_exploration_with_missing_voiceover_is_reported()
        
        # Add a valid auto voiceover.
        voc_model = self.create_model(
            voiceover_models.EntityVoiceoversModel,
            id='exploration-exp_1-1-hi-IN',
            entity_type=feconf.ENTITY_TYPE_EXPLORATION,
            entity_id='exp_1',
            entity_version=1,
            language_accent_code='hi-IN',
            voiceovers_mapping={
                'content_0': {
                    'manual': None,
                    'auto': {
                        'filename': 'hi_auto.mp3',
                        'file_size_bytes': 100,
                        'needs_update': False,
                        'duration_secs': 1.0
                    }
                }
            },
            automated_voiceovers_audio_offsets_msecs={}
        )
        voc_model.update_timestamps()
        voc_model.put()
        
        self.assert_job_output_is(['Total missing voiceovers found: 0'])
