// Copyright 2020 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview The root component for angular application.
 */

/**
 * This file contains a component that "informs" the oppia-root directive that
 * angular has finished loading. This also contains services that are written
 * in angular but have to be accessed in ajs code.
 *
 * To have a new angular service accesible in ajs do the following:
 *   - import the service here.
 *   - create a static variable with the name of the service class in camelCase.
 *   - inject the service by providing it as an argument in the constructor.
 *   - in the ngAfterViewInit assign the serivce to the static varible
 *
 * Example:
 *   Let us assume that the service class is called MyService.
 *   - First import the service.
 *     import { MyService } from './path';
 *   - Then we create a static variable with the name of the service class.
 *     static myService: MyService;
 *   - Then we add it to the constructor
 *     constructor(
 *      ...
 *      private myService: MyService
 *     ...) {}
 *   - Then we assign the serivce to the static varible in ngAfterViewInit
 *     ngAfterViewInit() {
 *       ...
 *       OppiaAngularRootComponent.myService = this.myService
 *       ...
 *     }
 *
 * In case the above explanation was not clear or in case of doubts over what
 * is done here, please look at the description of the PR #9479.
 * https://github.com/oppia/oppia/pull/9479#issue-432536289
 * You can also find this example there under the "How does it solve the
 * Interceptor problem?" heading.
 *
 * File Structure:
 *   1 - imports
 *   2 - component declaration
 *   3 - static declaration of service-variables
 *   4 - constructor having all the services injected
 *   5 - ngAfterViewInit function assigning the injected service to static class
 *       variables and emitting an event to inform that angular has finished
 *       loading
 */

/* eslint-disable max-len */
import { Component, Output, AfterViewInit, EventEmitter } from '@angular/core';
import { AdminDataService } from
  'pages/admin-page/services/admin-data.service';
import { AdminRouterService } from
  'pages/admin-page/services/admin-router.service.ts';
import { AdminTaskManagerService } from
  'pages/admin-page/services/admin-task-manager.service';
import { AlertsService } from 'services/alerts.service';
import { AngularNameService } from
  'pages/exploration-editor-page/services/angular-name.service';
import { AnswerClassificationResultObjectFactory } from
  'domain/classifier/AnswerClassificationResultObjectFactory';
import { AnswerClassificationService } from
  'pages/exploration-player-page/services/answer-classification.service';
import { AnswerGroupsCacheService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/editor-tab/services/answer-groups-cache.service';
import { AnswerGroupObjectFactory } from
  'domain/exploration/AnswerGroupObjectFactory';
import { AnswerStatsObjectFactory } from
  'domain/exploration/AnswerStatsObjectFactory';
import { AppService } from 'services/app.service';
import { AudioBarStatusService } from 'services/audio-bar-status.service';
import { AudioFileObjectFactory } from
  'domain/utilities/AudioFileObjectFactory';
import { AudioLanguageObjectFactory } from
  'domain/utilities/AudioLanguageObjectFactory';
import { AudioTranslationLanguageService } from
  'pages/exploration-player-page/services/audio-translation-language.service';
import { AudioTranslationManagerService } from
  'pages/exploration-player-page/services/audio-translation-manager.service';
import { AutogeneratedAudioLanguageObjectFactory } from
  'domain/utilities/AutogeneratedAudioLanguageObjectFactory';
import { AutogeneratedAudioPlayerService } from
  'services/autogenerated-audio-player.service';
import { AutoplayedVideosService } from 'services/autoplayed-videos.service';
import { BackgroundMaskService } from
  'services/stateful/background-mask.service';
import { baseInteractionValidationService } from
  'interactions/base-interaction-validation.service';
import { BrowserCheckerService } from
  'domain/utilities/browser-checker.service';
import { CamelCaseToHyphensPipe } from
  'filters/string-utility-filters/camel-case-to-hyphens.pipe';
import { ChangeObjectFactory } from
  'domain/editor/undo_redo/ChangeObjectFactory';
import { ClassifierObjectFactory } from
  'domain/classifier/ClassifierObjectFactory';
import { ClassroomBackendApiService } from
  'domain/classroom/classroom-backend-api.service';
import { CodeNormalizerService } from 'services/code-normalizer.service';
import { CodeReplPredictionService } from
  'interactions/CodeRepl/code-repl-prediction.service';
import { CodeReplRulesService } from
  'interactions/CodeRepl/directives/code-repl-rules.service';
import { CodeReplValidationService } from
  'interactions/CodeRepl/directives/code-repl-validation.service';
import { CollectionCreationBackendService } from
  'components/entity-creation-services/collection-creation-backend-api.service';
import { CollectionCreationService } from
  'components/entity-creation-services/collection-creation.service';
import { CollectionNodeObjectFactory } from
  'domain/collection/CollectionNodeObjectFactory';
import { CollectionObjectFactory } from
  'domain/collection/CollectionObjectFactory';
import { CollectionPlaythroughObjectFactory } from
  'domain/collection/CollectionPlaythroughObjectFactory';
import { CollectionRightsBackendApiService } from
  'domain/collection/collection-rights-backend-api.service';
import { CollectionRightsObjectFactory } from
  'domain/collection/CollectionRightsObjectFactory';
import { CollectionValidationService } from
  'domain/collection/collection-validation.service';
import { ComputeGraphService } from 'services/compute-graph.service';
import { ConceptCardObjectFactory } from
  'domain/skill/ConceptCardObjectFactory';
import { ContextService } from 'services/context.service';
import { ContinueValidationService } from
  'interactions/Continue/directives/continue-validation.service';
import { ContributionOpportunitiesBackendApiService } from
  // eslint-disable-next-line max-len
  'pages/community-dashboard-page/services/contribution-opportunities-backend-api.service';
import { ConstructTranslationIdsService } from
  'services/construct-translation-ids.service';
import { CountVectorizerService } from 'classifiers/count-vectorizer.service';
import { CreatorDashboardBackendApiService } from
  'domain/creator_dashboard/creator-dashboard-backend-api.service';
import { CsrfTokenService } from 'services/csrf-token.service';
import { CurrentInteractionService } from
  'pages/exploration-player-page/services/current-interaction.service';
import { DateTimeFormatService } from 'services/date-time-format.service';
import { DebouncerService } from 'services/debouncer.service';
import { DeviceInfoService } from 'services/contextual/device-info.service';
import { DocumentAttributeCustomizationService } from
  'services/contextual/document-attribute-customization.service';
import { DragAndDropSortInputRulesService } from
  // eslint-disable-next-line max-len
  'interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-rules.service';
import { DragAndDropSortInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-validation.service';
import { EditableCollectionBackendApiService } from
  'domain/collection/editable-collection-backend-api.service';
import { EditabilityService } from 'services/editability.service';
import { EditorFirstTimeEventsService } from
  'pages/exploration-editor-page/services/editor-first-time-events.service';
import { EndExplorationValidationService } from
  'interactions/EndExploration/directives/end-exploration-validation.service';
import { EmailDashboardDataService } from
  'pages/email-dashboard-pages/email-dashboard-data.service';
import { EntityContextObjectFactory } from
  'domain/utilities/EntityContextObjectFactory';
import { ExplorationDiffService } from
  'pages/exploration-editor-page/services/exploration-diff.service';
import { ExplorationDraftObjectFactory } from
  'domain/exploration/ExplorationDraftObjectFactory';
import { ExplorationFeaturesBackendApiService } from
  'services/exploration-features-backend-api.service';
import { ExplorationFeaturesService } from
  'services/exploration-features.service';
import { ExplorationHtmlFormatterService } from
  'services/exploration-html-formatter.service';
import { ExplorationMetadataObjectFactory } from
  'domain/exploration/ExplorationMetadataObjectFactory';
import { ExplorationObjectFactory } from
  'domain/exploration/ExplorationObjectFactory';
import { ExplorationOpportunitySummaryObjectFactory } from
  'domain/opportunity/ExplorationOpportunitySummaryObjectFactory';
import { ExpressionParserService } from 'expressions/expression-parser.service';
import { ExplorationRecommendationsService } from
  'pages/exploration-player-page/services/exploration-recommendations.service';
import { ExpressionSyntaxTreeService } from
  'expressions/expression-syntax-tree.service';
import { ExtensionTagAssemblerService } from
  'services/extension-tag-assembler.service';
import { ExtractImageFilenamesFromStateService } from
  // eslint-disable-next-line max-len
  'pages/exploration-player-page/services/extract-image-filenames-from-state.service';
import { FeedbackMessageSummaryObjectFactory } from
  'domain/feedback_message/FeedbackMessageSummaryObjectFactory';
import { FeedbackThreadObjectFactory } from
  'domain/feedback_thread/FeedbackThreadObjectFactory';
import { FeedbackThreadSummaryObjectFactory } from
  'domain/feedback_thread/FeedbackThreadSummaryObjectFactory';
import { FileDownloadRequestObjectFactory } from
  'domain/utilities/FileDownloadRequestObjectFactory';
import { FormatTimePipe } from 'filters/format-timer.pipe';
import { FractionInputValidationService } from
  'interactions/FractionInput/directives/fraction-input-validation.service';
import { FractionObjectFactory } from 'domain/objects/FractionObjectFactory';
import { GenerateContentIdService } from 'services/generate-content-id.service';
import { GraphDetailService } from
  'interactions/GraphInput/directives/graph-detail.service';
import { GraphInputValidationService } from
  'interactions/GraphInput/directives/graph-input-validation.service';
import { GraphUtilsService } from
  'interactions/GraphInput/directives/graph-utils.service';
import { GuestCollectionProgressObjectFactory } from
  'domain/collection/GuestCollectionProgressObjectFactory';
import { GuestCollectionProgressService } from
  'domain/collection/guest-collection-progress.service';
import { HintObjectFactory } from 'domain/exploration/HintObjectFactory';
import { HtmlEscaperService } from 'services/html-escaper.service';
import { I18nLanguageCodeService } from 'services/i18n-language-code.service';
import { IdGenerationService } from 'services/id-generation.service';
import { ImageClickInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/ImageClickInput/directives/image-click-input-validation.service';
import { ImageFileObjectFactory } from
  'domain/utilities/ImageFileObjectFactory';
import { ImprovementActionButtonObjectFactory } from
  'domain/statistics/ImprovementActionButtonObjectFactory';
import { ImprovementsService } from 'services/improvements.service';
import { InteractionDetailsCacheService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/editor-tab/services/interaction-details-cache.service';
import { InteractionObjectFactory } from
  'domain/exploration/InteractionObjectFactory';
import { InteractionRulesRegistryService } from
  'services/interaction-rules-registry.service';
import { InteractionSpecsService } from 'services/interaction-specs.service';
import { InteractiveMapValidationService } from
  'interactions/InteractiveMap/directives/interactive-map-validation.service';
import { ItemSelectionInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/ItemSelectionInput/directives/item-selection-input-validation.service';
import { LanguageUtilService } from 'domain/utilities/language-util.service';
import { LearnerActionObjectFactory } from
  'domain/statistics/LearnerActionObjectFactory';
import { LearnerAnswerDetailsBackendApiService } from
  'domain/statistics/learner-answer-details-backend-api.service';
import { LearnerAnswerDetailsObjectFactory } from
  'domain/statistics/LearnerAnswerDetailsObjectFactory';
import { LearnerAnswerInfoObjectFactory } from
  'domain/statistics/LearnerAnswerInfoObjectFactory';
import { LearnerDashboardActivityIdsObjectFactory } from
  'domain/learner_dashboard/LearnerDashboardActivityIdsObjectFactory';
import { LearnerDashboardBackendApiService } from
  'domain/learner_dashboard/learner-dashboard-backend-api.service';
import { LearnerDashboardIdsBackendApiService } from
  'domain/learner_dashboard/learner-dashboard-ids-backend-api.service';
import { LearnerParamsService } from
  'pages/exploration-player-page/services/learner-params.service';
import { LocalStorageService } from 'services/local-storage.service';
import { LoaderService } from 'services/loader.service';
import { LoggerService } from 'services/contextual/logger.service';
import { LogicProofValidationService } from
  'interactions/LogicProof/directives/logic-proof-validation.service';
import { LostChangeObjectFactory } from
  'domain/exploration/LostChangeObjectFactory';
import { MathExpressionInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MathExpressionInput/directives/math-expression-input-validation.service';
import { MessengerService } from 'services/messenger.service';
import { MetaTagCustomizationService } from
  'services/contextual/meta-tag-customization.service';
import { MisconceptionObjectFactory } from
  'domain/skill/MisconceptionObjectFactory';
import { MultipleChoiceInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MultipleChoiceInput/directives/multiple-choice-input-validation.service';
import { MusicNotesInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MusicNotesInput/directives/music-notes-input-validation.service';
import { MusicPhrasePlayerService } from
  // eslint-disable-next-line max-len
  'interactions/MusicNotesInput/directives/music-phrase-player.service';
import { NewlyCreatedTopicObjectFactory } from
  'domain/topics_and_skills_dashboard/NewlyCreatedTopicObjectFactory';
import { NormalizeWhitespacePipe } from
  'filters/string-utility-filters/normalize-whitespace.pipe';
import { NormalizeWhitespacePunctuationAndCasePipe } from
  // eslint-disable-next-line max-len
  'filters/string-utility-filters/normalize-whitespace-punctuation-and-case.pipe';
import { NumberAttemptsService } from
  'pages/exploration-player-page/services/number-attempts.service';
import { NumericInputValidationService } from
  'interactions/NumericInput/directives/numeric-input-validation.service';
import { NumberWithUnitsObjectFactory } from
  'domain/objects/NumberWithUnitsObjectFactory';
import { NumberWithUnitsValidationService } from
  // eslint-disable-next-line max-len
  'interactions/NumberWithUnits/directives/number-with-units-validation.service.ts';
import { OutcomeObjectFactory } from 'domain/exploration/OutcomeObjectFactory';
import { PageTitleService } from 'services/page-title.service';
import { ParamChangeObjectFactory } from
  'domain/exploration/ParamChangeObjectFactory';
import { ParamChangesObjectFactory } from
  'domain/exploration/ParamChangesObjectFactory';
import { ParamMetadataObjectFactory } from
  'domain/exploration/ParamMetadataObjectFactory';
import { ParamSpecObjectFactory } from
  'domain/exploration/ParamSpecObjectFactory';
import { ParamSpecsObjectFactory } from
  'domain/exploration/ParamSpecsObjectFactory';
import { ParamTypeObjectFactory } from
  'domain/exploration/ParamTypeObjectFactory';
import { PencilCodeEditorRulesService } from
  'interactions/PencilCodeEditor/directives/pencil-code-editor-rules.service';
import { PencilCodeEditorValidationService } from
  'interactions/PencilCodeEditor/directives/pencil-code-editor-validation.service';
import { PlayerCorrectnessFeedbackEnabledService } from
  'pages/exploration-player-page/services/player-correctness-feedback-enabled.service';
import { PlayerPositionService } from
  'pages/exploration-player-page/services/player-position.service';
import { PlayerTranscriptService } from
  'pages/exploration-player-page/services/player-transcript.service';
import { PlaythroughIssueObjectFactory } from
  'domain/statistics/PlaythroughIssueObjectFactory';
import { PlaythroughIssuesBackendApiService } from
  'services/playthrough-issues-backend-api.service';
import { PlaythroughObjectFactory } from
  'domain/statistics/PlaythroughObjectFactory';
import { PlaythroughService } from 'services/playthrough.service';
import { PredictionAlgorithmRegistryService } from
  'pages/exploration-player-page/services/prediction-algorithm-registry.service';
import { PredictionResultObjectFactory } from
  'domain/classifier/PredictionResultObjectFactory';
import { PretestQuestionBackendApiService } from
  'domain/question/pretest-question-backend-api.service';
import { ProfilePageBackendApiService } from
  'pages/profile-page/profile-page-backend-api.service';
import { PythonProgramTokenizer } from 'classifiers/python-program.tokenizer';
import { QuestionBackendApiService } from
  'domain/question/question-backend-api.service.ts';
import { QuestionCreationService } from
  'components/entity-creation-services/question-creation.service';
import { QuestionSummaryForOneSkillObjectFactory }
  from 'domain/question/QuestionSummaryForOneSkillObjectFactory';
import { QuestionSummaryObjectFactory } from
  'domain/question/QuestionSummaryObjectFactory';
import { ReadOnlyCollectionBackendApiService } from
  'domain/collection/read-only-collection-backend-api.service';
import { RatingComputationService } from
  'components/ratings/rating-computation/rating-computation.service';
import { ReadOnlyStoryNodeObjectFactory } from
  'domain/story_viewer/ReadOnlyStoryNodeObjectFactory';
import { ReadOnlySubtopicPageObjectFactory } from
  'domain/subtopic_viewer/ReadOnlySubtopicPageObjectFactory';
import { ReadOnlyTopicObjectFactory } from
  'domain/topic_viewer/read-only-topic-object.factory';
import { RecordedVoiceoversObjectFactory } from
  'domain/exploration/RecordedVoiceoversObjectFactory';
import { ReviewTestBackendApiService } from
  'domain/review_test/review-test-backend-api.service';
import { ReviewTestEngineService } from
  'pages/review-test-page/review-test-engine.service.ts';
import { RubricObjectFactory } from
  'domain/skill/RubricObjectFactory';
import { RuleObjectFactory } from 'domain/exploration/RuleObjectFactory';
import { SchemaDefaultValueService } from
  'services/schema-default-value.service';
import { SchemaUndefinedLastElementService } from
  'services/schema-undefined-last-element.service';
import { SearchExplorationsBackendApiService } from
  'domain/collection/search-explorations-backend-api.service';
import { SetInputValidationService } from
  'interactions/SetInput/directives/set-input-validation.service';
import { SVMPredictionService } from 'classifiers/svm-prediction.service';
import { SidebarStatusService } from 'domain/sidebar/sidebar-status.service';
import { SiteAnalyticsService } from 'services/site-analytics.service';
import { SkillCreationBackendApiService } from
  'domain/skill/skill-creation-backend-api.service';
import { SkillDifficultyObjectFactory } from
  'domain/skill/SkillDifficultyObjectFactory';
import { SkillMasteryBackendApiService } from
  'domain/skill/skill-mastery-backend-api.service';
import { SkillObjectFactory } from 'domain/skill/SkillObjectFactory';
import { SkillOpportunityObjectFactory } from
  'domain/opportunity/SkillOpportunityObjectFactory';
import { SkillRightsBackendApiService} from
  'domain/skill/skill-rights-backend-api.service.ts';
import { SkillRightsObjectFactory } from
  'domain/skill/SkillRightsObjectFactory';
import { SkillSummaryObjectFactory } from
  'domain/skill/SkillSummaryObjectFactory';
import { SolutionObjectFactory } from
  'domain/exploration/SolutionObjectFactory';
import { SolutionValidityService } from
  'pages/exploration-editor-page/editor-tab/services/solution-validity.service';
import { SpeechSynthesisChunkerService } from
  'services/speech-synthesis-chunker.service';
import { StateCardObjectFactory } from
  'domain/state_card/StateCardObjectFactory';
import { StateClassifierMappingService } from
  'pages/exploration-player-page/services/state-classifier-mapping.service';
import { StateContentService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-content.service';
import { StateCustomizationArgsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-customization-args.service';
import { StateEditorService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-editor.service';
import { StateGraphLayoutService } from
  'components/graph-services/graph-layout.service';
import { StateHintsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-hints.service';
import { StateImprovementSuggestionService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/statistics-tab/services/state-improvement-suggestion.service';
import { StateInteractionIdService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-interaction-id.service';
import { StateInteractionStatsService } from
  'services/state-interaction-stats.service';
import { StateNameService } from
  'components/state-editor/state-editor-properties-services/state-name.service';
import { StateObjectFactory } from 'domain/state/StateObjectFactory';
import { StateParamChangesService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-param-changes.service';
import { StatePropertyService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-property.service';
import { StateRecordedVoiceoversService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-recorded-voiceovers.service';
import { StateSolicitAnswerDetailsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-solicit-answer-details.service';
import { StateSolutionService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-solution.service';
import { StateTopAnswersStatsBackendApiService } from
  'services/state-top-answers-stats-backend-api.service';
import { StateWrittenTranslationsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-written-translations.service';
import { StatesObjectFactory } from 'domain/exploration/StatesObjectFactory';
import { StatsReportingService } from
  'pages/exploration-player-page/services/stats-reporting.service';
import { StopwatchObjectFactory } from
  'domain/utilities/StopwatchObjectFactory';
import { StoryContentsObjectFactory } from
  'domain/story/StoryContentsObjectFactory';
import { StoryNodeObjectFactory } from
  'domain/story/StoryNodeObjectFactory';
import { StoryObjectFactory } from 'domain/story/StoryObjectFactory';
import { StoryPlaythroughObjectFactory } from
  'domain/story_viewer/StoryPlaythroughObjectFactory';
import { StoryReferenceObjectFactory } from
  'domain/topic/StoryReferenceObjectFactory';
import { StorySummaryObjectFactory } from
  'domain/story/StorySummaryObjectFactory';
import { StoryViewerBackendApiService } from
  'domain/story_viewer/story-viewer-backend-api.service';
import { SubtitledHtmlObjectFactory } from
  'domain/exploration/SubtitledHtmlObjectFactory';
import { SubtopicObjectFactory } from 'domain/topic/SubtopicObjectFactory';
import { SubtopicPageContentsObjectFactory } from
  'domain/topic/SubtopicPageContentsObjectFactory';
import { SubtopicPageObjectFactory } from
  'domain/topic/SubtopicPageObjectFactory';
import { SubtopicViewerBackendApiService } from
  'domain/subtopic_viewer/subtopic-viewer-backend-api.service';
import { SuggestionModalService } from 'services/suggestion-modal.service';
import { SuggestionObjectFactory } from
  'domain/suggestion/SuggestionObjectFactory';
import { SuggestionThreadObjectFactory } from
  'domain/suggestion/SuggestionThreadObjectFactory';
import { SuggestionsService } from 'services/suggestions.service';
import { TextInputPredictionService } from
  'interactions/TextInput/text-input-prediction.service';
import { TextInputRulesService } from
  'interactions/TextInput/directives/text-input-rules.service';
import { TextInputTokenizer } from 'classifiers/text-input.tokenizer';
import { TextInputValidationService } from
  'interactions/TextInput/directives/text-input-validation.service';
import { ThreadMessageObjectFactory } from
  'domain/feedback_message/ThreadMessageObjectFactory';
import { ThreadMessageSummaryObjectFactory } from
  'domain/feedback_message/ThreadMessageSummaryObjectFactory';
import { ThreadStatusDisplayService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/feedback-tab/services/thread-status-display.service';
import { TopicCreationBackendApiService } from
  'domain/topic/topic-creation-backend-api.service.ts';
import { TopicObjectFactory } from 'domain/topic/TopicObjectFactory';
import { TopicRightsObjectFactory } from
  'domain/topic/TopicRightsObjectFactory';
import { TopicsAndSkillsDashboardBackendApiService } from
  // eslint-disable-next-line max-len
  'domain/topics_and_skills_dashboard/topics-and-skills-dashboard-backend-api.service';
import { TopicSummaryObjectFactory } from
  'domain/topic/TopicSummaryObjectFactory';
import { TopicsAndSkillsDashboardFilterObjectFactory } from
  // eslint-disable-next-line max-len
  'domain/topics_and_skills_dashboard/TopicsAndSkillsDashboardFilterObjectFactory';
import { TopicsAndSkillsDashboardPageService } from
  // eslint-disable-next-line max-len
  'pages/topics-and-skills-dashboard-page/topics-and-skills-dashboard-page.service';
import { TopicViewerBackendApiService } from
  'domain/topic_viewer/topic-viewer-backend-api.service';
import { UnitsObjectFactory } from 'domain/objects/UnitsObjectFactory';
import { UrlInterpolationService } from
  'domain/utilities/url-interpolation.service';
import { UrlService } from 'services/contextual/url.service';
import { UserExplorationPermissionsService } from
  'pages/exploration-editor-page/services/user-exploration-permissions.service';
import { UserInfoObjectFactory } from 'domain/user/UserInfoObjectFactory';
import { UtilsService } from 'services/utils.service';
import { ValidatorsService } from 'services/validators.service';
import { VersionTreeService } from
  'pages/exploration-editor-page/history-tab/services/version-tree.service';
import { VoiceoverObjectFactory } from
  'domain/exploration/VoiceoverObjectFactory';
import { WindowDimensionsService } from
  'services/contextual/window-dimensions.service';
import { WindowRef } from 'services/contextual/window-ref.service';
import { WinnowingPreprocessingService } from
  'classifiers/winnowing-preprocessing.service';
import { WorkedExampleObjectFactory } from
  'domain/skill/WorkedExampleObjectFactory';
import { WrittenTranslationObjectFactory } from
  'domain/exploration/WrittenTranslationObjectFactory';
import { WrittenTranslationsObjectFactory } from
  'domain/exploration/WrittenTranslationsObjectFactory';

@Component({
  selector: 'oppia-angular-root',
  template: ''
})
export class OppiaAngularRootComponent implements AfterViewInit {
  @Output()
    public initialized: EventEmitter<void> = new EventEmitter();

  static adminDataService: AdminDataService;
  static adminRouterService: AdminRouterService;
  static adminTaskManagerService: AdminTaskManagerService;
  static alertsService: AlertsService;
  static angularNameService: AngularNameService;
  static answerClassificationResultObjectFactory: AnswerClassificationResultObjectFactory;
  static answerClassificationService: AnswerClassificationService;
  static answerGroupsCacheService: AnswerGroupsCacheService;
  static answerGroupObjectFactory: AnswerGroupObjectFactory;
  static answerStatsObjectFactory: AnswerStatsObjectFactory;
  static appService: AppService;
  static audioBarStatusService: AudioBarStatusService;
  static audioFileObjectFactory: AudioFileObjectFactory;
  static audioLanguageObjectFactory: AudioLanguageObjectFactory;
  static audioTranslationLanguageService: AudioTranslationLanguageService;
  static audioTranslationManagerService: AudioTranslationManagerService;
  static autogeneratedAudioLanguageObjectFactory: AutogeneratedAudioLanguageObjectFactory;
  static autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService;
  static autoplayedVideosService: AutoplayedVideosService;
  static backgroundMaskService: BackgroundMaskService;
  static baseInteractionValidationService: baseInteractionValidationService;
  static browserCheckerService: BrowserCheckerService;
  static camelCaseToHyphensPipe: CamelCaseToHyphensPipe;
  static changeObjectFactory: ChangeObjectFactory;
  static classifierObjectFactory: ClassifierObjectFactory;
  static classroomBackendApiService: ClassroomBackendApiService;
  static codeNormalizerService: CodeNormalizerService;
  static codeReplPredictionService: CodeReplPredictionService;
  static codeReplRulesService: CodeReplRulesService;
  static codeReplValidationService: CodeReplValidationService;
  static collectionCreationBackendService: CollectionCreationBackendService;
  static collectionCreationService: CollectionCreationService;
  static collectionNodeObjectFactory: CollectionNodeObjectFactory;
  static collectionObjectFactory: CollectionObjectFactory;
  static collectionPlaythroughObjectFactory: CollectionPlaythroughObjectFactory;
  static collectionRightsBackendApiService: CollectionRightsBackendApiService;
  static collectionRightsObjectFactory: CollectionRightsObjectFactory;
  static collectionValidationService: CollectionValidationService;
  static computeGraphService: ComputeGraphService;
  static conceptCardObjectFactory: ConceptCardObjectFactory;
  static contextService: ContextService;
  static continueValidationService: ContinueValidationService;
  static contributionOpportunitiesBackendApiService: ContributionOpportunitiesBackendApiService;
  static constructTranslationIdsService: ConstructTranslationIdsService;
  static countVectorizerService: CountVectorizerService;
  static creatorDashboardBackendApiService: CreatorDashboardBackendApiService;
  static csrfTokenService: CsrfTokenService;
  static currentInteractionService: CurrentInteractionService;
  static dateTimeFormatService: DateTimeFormatService;
  static debouncerService: DebouncerService;
  static deviceInfoService: DeviceInfoService;
  static documentAttributeCustomizationService: DocumentAttributeCustomizationService;
  static dragAndDropSortInputRulesService: DragAndDropSortInputRulesService;
  static dragAndDropSortInputValidationService: DragAndDropSortInputValidationService;
  static editableCollectionBackendApiService: EditableCollectionBackendApiService;
  static editabilityService: EditabilityService;
  static editorFirstTimeEventsService: EditorFirstTimeEventsService;
  static endExplorationValidationService: EndExplorationValidationService;
  static emailDashboardDataService: EmailDashboardDataService;
  static entityContextObjectFactory: EntityContextObjectFactory;
  static explorationDiffService: ExplorationDiffService;
  static explorationDraftObjectFactory: ExplorationDraftObjectFactory;
  static explorationFeaturesBackendApiService: ExplorationFeaturesBackendApiService;
  static explorationFeaturesService: ExplorationFeaturesService;
  static explorationHtmlFormatterService: ExplorationHtmlFormatterService;
  static explorationMetadataObjectFactory: ExplorationMetadataObjectFactory;
  static explorationObjectFactory: ExplorationObjectFactory;
  static explorationOpportunitySummaryObjectFactory: ExplorationOpportunitySummaryObjectFactory;
  static expressionParserService: ExpressionParserService;
  static explorationRecommendationsService: ExplorationRecommendationsService;
  static expressionSyntaxTreeService: ExpressionSyntaxTreeService;
  static extensionTagAssemblerService: ExtensionTagAssemblerService;
  static extractImageFilenamesFromStateService: ExtractImageFilenamesFromStateService;
  static feedbackMessageSummaryObjectFactory: FeedbackMessageSummaryObjectFactory;
  static feedbackThreadObjectFactory: FeedbackThreadObjectFactory;
  static feedbackThreadSummaryObjectFactory: FeedbackThreadSummaryObjectFactory;
  static fileDownloadRequestObjectFactory: FileDownloadRequestObjectFactory;
  static formatTimePipe: FormatTimePipe;
  static fractionInputValidationService: FractionInputValidationService;
  static fractionObjectFactory: FractionObjectFactory;
  static generateContentIdService: GenerateContentIdService;
  static graphDetailService: GraphDetailService;
  static graphInputValidationService: GraphInputValidationService;
  static graphUtilsService: GraphUtilsService;
  static guestCollectionProgressObjectFactory: GuestCollectionProgressObjectFactory;
  static guestCollectionProgressService: GuestCollectionProgressService;
  static hintObjectFactory: HintObjectFactory;
  static htmlEscaperService: HtmlEscaperService;
  static i18nLanguageCodeService: I18nLanguageCodeService;
  static idGenerationService: IdGenerationService;
  static imageClickInputValidationService: ImageClickInputValidationService;
  static imageFileObjectFactory: ImageFileObjectFactory;
  static improvementActionButtonObjectFactory: ImprovementActionButtonObjectFactory;
  static improvementsService: ImprovementsService;
  static interactionDetailsCacheService: InteractionDetailsCacheService;
  static interactionObjectFactory: InteractionObjectFactory;
  static interactionRulesRegistryService: InteractionRulesRegistryService;
  static interactionSpecsService: InteractionSpecsService;
  static interactiveMapValidationService: InteractiveMapValidationService;
  static itemSelectionInputValidationService: ItemSelectionInputValidationService;
  static languageUtilService: LanguageUtilService;
  static learnerActionObjectFactory: LearnerActionObjectFactory;
  static learnerAnswerDetailsBackendApiService: LearnerAnswerDetailsBackendApiService;
  static learnerAnswerDetailsObjectFactory: LearnerAnswerDetailsObjectFactory;
  static learnerAnswerInfoObjectFactory: LearnerAnswerInfoObjectFactory;
  static learnerDashboardActivityIdsObjectFactory: LearnerDashboardActivityIdsObjectFactory;
  static learnerDashboardBackendApiService: LearnerDashboardBackendApiService;
  static learnerDashboardIdsBackendApiService: LearnerDashboardIdsBackendApiService;
  static learnerParamsService: LearnerParamsService;
  static localStorageService: LocalStorageService;
  static loaderService: LoaderService;
  static loggerService: LoggerService;
  static logicProofValidationService: LogicProofValidationService;
  static lostChangeObjectFactory: LostChangeObjectFactory;
  static mathExpressionInputValidationService: MathExpressionInputValidationService;
  static messengerService: MessengerService;
  static metaTagCustomizationService: MetaTagCustomizationService;
  static misconceptionObjectFactory: MisconceptionObjectFactory;
  static multipleChoiceInputValidationService: MultipleChoiceInputValidationService;
  static musicNotesInputValidationService: MusicNotesInputValidationService;
  static musicPhrasePlayerService: MusicPhrasePlayerService;
  static newlyCreatedTopicObjectFactory: NewlyCreatedTopicObjectFactory;
  static normalizeWhitespacePipe: NormalizeWhitespacePipe;
  static normalizeWhitespacePunctuationAndCasePipe: NormalizeWhitespacePunctuationAndCasePipe;
  static numberAttemptsService: NumberAttemptsService;
  static numericInputValidationService: NumericInputValidationService;
  static numberWithUnitsObjectFactory: NumberWithUnitsObjectFactory;
  static numberWithUnitsValidationService: NumberWithUnitsValidationService;
  static outcomeObjectFactory: OutcomeObjectFactory;
  static pageTitleService: PageTitleService;
  static paramChangeObjectFactory: ParamChangeObjectFactory;
  static paramChangesObjectFactory: ParamChangesObjectFactory;
  static paramMetadataObjectFactory: ParamMetadataObjectFactory;
  static paramSpecObjectFactory: ParamSpecObjectFactory;
  static paramSpecsObjectFactory: ParamSpecsObjectFactory;
  static paramTypeObjectFactory: ParamTypeObjectFactory;
  static pencilCodeEditorRulesService: PencilCodeEditorRulesService;
  static pencilCodeEditorValidationService: PencilCodeEditorValidationService;
  static playerCorrectnessFeedbackEnabledService: PlayerCorrectnessFeedbackEnabledService;
  static playerPositionService: PlayerPositionService;
  static playerTranscriptService: PlayerTranscriptService;
  static playthroughIssueObjectFactory: PlaythroughIssueObjectFactory;
  static playthroughIssuesBackendApiService: PlaythroughIssuesBackendApiService;
  static playthroughObjectFactory: PlaythroughObjectFactory;
  static playthroughService: PlaythroughService;
  static predictionAlgorithmRegistryService: PredictionAlgorithmRegistryService;
  static predictionResultObjectFactory: PredictionResultObjectFactory;
  static pretestQuestionBackendApiService: PretestQuestionBackendApiService;
  static profilePageBackendApiService: ProfilePageBackendApiService;
  static pythonProgramTokenizer: PythonProgramTokenizer;
  static questionBackendApiService: QuestionBackendApiService;
  static questionCreationService: QuestionCreationService;
  static questionSummaryForOneSkillObjectFactory: QuestionSummaryForOneSkillObjectFactory;
  static questionSummaryObjectFactory: QuestionSummaryObjectFactory;
  static readOnlyCollectionBackendApiService: ReadOnlyCollectionBackendApiService;
  static ratingComputationService: RatingComputationService;
  static readOnlyStoryNodeObjectFactory: ReadOnlyStoryNodeObjectFactory;
  static readOnlySubtopicPageObjectFactory: ReadOnlySubtopicPageObjectFactory;
  static readOnlyTopicObjectFactory: ReadOnlyTopicObjectFactory;
  static recordedVoiceoversObjectFactory: RecordedVoiceoversObjectFactory;
  static reviewTestBackendApiService: ReviewTestBackendApiService;
  static reviewTestEngineService: ReviewTestEngineService;
  static rubricObjectFactory: RubricObjectFactory;
  static ruleObjectFactory: RuleObjectFactory;
  static schemaDefaultValueService: SchemaDefaultValueService;
  static schemaUndefinedLastElementService: SchemaUndefinedLastElementService;
  static searchExplorationsBackendApiService: SearchExplorationsBackendApiService;
  static setInputValidationService: SetInputValidationService;
  static sVMPredictionService: SVMPredictionService;
  static sidebarStatusService: SidebarStatusService;
  static siteAnalyticsService: SiteAnalyticsService;
  static skillCreationBackendApiService: SkillCreationBackendApiService;
  static skillDifficultyObjectFactory: SkillDifficultyObjectFactory;
  static skillMasteryBackendApiService: SkillMasteryBackendApiService;
  static skillObjectFactory: SkillObjectFactory;
  static skillOpportunityObjectFactory: SkillOpportunityObjectFactory;
  static skillRightsBackendApiService: SkillRightsBackendApiService;
  static skillRightsObjectFactory: SkillRightsObjectFactory;
  static skillSummaryObjectFactory: SkillSummaryObjectFactory;
  static solutionObjectFactory: SolutionObjectFactory;
  static solutionValidityService: SolutionValidityService;
  static speechSynthesisChunkerService: SpeechSynthesisChunkerService;
  static stateCardObjectFactory: StateCardObjectFactory;
  static stateClassifierMappingService: StateClassifierMappingService;
  static stateContentService: StateContentService;
  static stateCustomizationArgsService: StateCustomizationArgsService;
  static stateEditorService: StateEditorService;
  static stateGraphLayoutService: StateGraphLayoutService;
  static stateHintsService: StateHintsService;
  static stateImprovementSuggestionService: StateImprovementSuggestionService;
  static stateInteractionIdService: StateInteractionIdService;
  static stateInteractionStatsService: StateInteractionStatsService;
  static stateNameService: StateNameService;
  static stateObjectFactory: StateObjectFactory;
  static stateParamChangesService: StateParamChangesService;
  static statePropertyService: StatePropertyService;
  static stateRecordedVoiceoversService: StateRecordedVoiceoversService;
  static stateSolicitAnswerDetailsService: StateSolicitAnswerDetailsService;
  static stateSolutionService: StateSolutionService;
  static stateTopAnswersStatsBackendApiService: StateTopAnswersStatsBackendApiService;
  static stateWrittenTranslationsService: StateWrittenTranslationsService;
  static statesObjectFactory: StatesObjectFactory;
  static statsReportingService: StatsReportingService;
  static stopwatchObjectFactory: StopwatchObjectFactory;
  static storyContentsObjectFactory: StoryContentsObjectFactory;
  static storyNodeObjectFactory: StoryNodeObjectFactory;
  static storyObjectFactory: StoryObjectFactory;
  static storyPlaythroughObjectFactory: StoryPlaythroughObjectFactory;
  static storyReferenceObjectFactory: StoryReferenceObjectFactory;
  static storySummaryObjectFactory: StorySummaryObjectFactory;
  static storyViewerBackendApiService: StoryViewerBackendApiService;
  static subtitledHtmlObjectFactory: SubtitledHtmlObjectFactory;
  static subtopicObjectFactory: SubtopicObjectFactory;
  static subtopicPageContentsObjectFactory: SubtopicPageContentsObjectFactory;
  static subtopicPageObjectFactory: SubtopicPageObjectFactory;
  static subtopicViewerBackendApiService: SubtopicViewerBackendApiService;
  static suggestionModalService: SuggestionModalService;
  static suggestionObjectFactory: SuggestionObjectFactory;
  static suggestionThreadObjectFactory: SuggestionThreadObjectFactory;
  static suggestionsService: SuggestionsService;
  static textInputPredictionService: TextInputPredictionService;
  static textInputRulesService: TextInputRulesService;
  static textInputTokenizer: TextInputTokenizer;
  static textInputValidationService: TextInputValidationService;
  static threadMessageObjectFactory: ThreadMessageObjectFactory;
  static threadMessageSummaryObjectFactory: ThreadMessageSummaryObjectFactory;
  static threadStatusDisplayService: ThreadStatusDisplayService;
  static topicCreationBackendApiService: TopicCreationBackendApiService;
  static topicObjectFactory: TopicObjectFactory;
  static topicRightsObjectFactory: TopicRightsObjectFactory;
  static topicsAndSkillsDashboardBackendApiService: TopicsAndSkillsDashboardBackendApiService;
  static topicSummaryObjectFactory: TopicSummaryObjectFactory;
  static topicsAndSkillsDashboardFilterObjectFactory: TopicsAndSkillsDashboardFilterObjectFactory;
  static topicsAndSkillsDashboardPageService: TopicsAndSkillsDashboardPageService;
  static topicViewerBackendApiService: TopicViewerBackendApiService;
  static unitsObjectFactory: UnitsObjectFactory;
  static urlInterpolationService: UrlInterpolationService;
  static urlService: UrlService;
  static userExplorationPermissionsService: UserExplorationPermissionsService;
  static userInfoObjectFactory: UserInfoObjectFactory;
  static utilsService: UtilsService;
  static validatorsService: ValidatorsService;
  static versionTreeService: VersionTreeService;
  static voiceoverObjectFactory: VoiceoverObjectFactory;
  static windowDimensionsService: WindowDimensionsService;
  static windowRef: WindowRef;
  static winnowingPreprocessingService: WinnowingPreprocessingService;
  static workedExampleObjectFactory: WorkedExampleObjectFactory;
  static writtenTranslationObjectFactory: WrittenTranslationObjectFactory;
  static writtenTranslationsObjectFactory: WrittenTranslationsObjectFactory;

  constructor(
    private adminDataService: AdminDataService,
private adminRouterService: AdminRouterService,
private adminTaskManagerService: AdminTaskManagerService,
private alertsService: AlertsService,
private angularNameService: AngularNameService,
private answerClassificationResultObjectFactory: AnswerClassificationResultObjectFactory,
private answerClassificationService: AnswerClassificationService,
private answerGroupsCacheService: AnswerGroupsCacheService,
private answerGroupObjectFactory: AnswerGroupObjectFactory,
private answerStatsObjectFactory: AnswerStatsObjectFactory,
private appService: AppService,
private audioBarStatusService: AudioBarStatusService,
private audioFileObjectFactory: AudioFileObjectFactory,
private audioLanguageObjectFactory: AudioLanguageObjectFactory,
private audioTranslationLanguageService: AudioTranslationLanguageService,
private audioTranslationManagerService: AudioTranslationManagerService,
private autogeneratedAudioLanguageObjectFactory: AutogeneratedAudioLanguageObjectFactory,
private autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService,
private autoplayedVideosService: AutoplayedVideosService,
private backgroundMaskService: BackgroundMaskService,
private baseInteractionValidationService: baseInteractionValidationService,
private browserCheckerService: BrowserCheckerService,
private camelCaseToHyphensPipe: CamelCaseToHyphensPipe,
private changeObjectFactory: ChangeObjectFactory,
private classifierObjectFactory: ClassifierObjectFactory,
private classroomBackendApiService: ClassroomBackendApiService,
private codeNormalizerService: CodeNormalizerService,
private codeReplPredictionService: CodeReplPredictionService,
private codeReplRulesService: CodeReplRulesService,
private codeReplValidationService: CodeReplValidationService,
private collectionCreationBackendService: CollectionCreationBackendService,
private collectionCreationService: CollectionCreationService,
private collectionNodeObjectFactory: CollectionNodeObjectFactory,
private collectionObjectFactory: CollectionObjectFactory,
private collectionPlaythroughObjectFactory: CollectionPlaythroughObjectFactory,
private collectionRightsBackendApiService: CollectionRightsBackendApiService,
private collectionRightsObjectFactory: CollectionRightsObjectFactory,
private collectionValidationService: CollectionValidationService,
private computeGraphService: ComputeGraphService,
private conceptCardObjectFactory: ConceptCardObjectFactory,
private contextService: ContextService,
private continueValidationService: ContinueValidationService,
private contributionOpportunitiesBackendApiService: ContributionOpportunitiesBackendApiService,
private constructTranslationIdsService: ConstructTranslationIdsService,
private countVectorizerService: CountVectorizerService,
private creatorDashboardBackendApiService: CreatorDashboardBackendApiService,
private csrfTokenService: CsrfTokenService,
private currentInteractionService: CurrentInteractionService,
private dateTimeFormatService: DateTimeFormatService,
private debouncerService: DebouncerService,
private deviceInfoService: DeviceInfoService,
private documentAttributeCustomizationService: DocumentAttributeCustomizationService,
private dragAndDropSortInputRulesService: DragAndDropSortInputRulesService,
private dragAndDropSortInputValidationService: DragAndDropSortInputValidationService,
private editableCollectionBackendApiService: EditableCollectionBackendApiService,
private editabilityService: EditabilityService,
private editorFirstTimeEventsService: EditorFirstTimeEventsService,
private endExplorationValidationService: EndExplorationValidationService,
private emailDashboardDataService: EmailDashboardDataService,
private entityContextObjectFactory: EntityContextObjectFactory,
private explorationDiffService: ExplorationDiffService,
private explorationDraftObjectFactory: ExplorationDraftObjectFactory,
private explorationFeaturesBackendApiService: ExplorationFeaturesBackendApiService,
private explorationFeaturesService: ExplorationFeaturesService,
private explorationHtmlFormatterService: ExplorationHtmlFormatterService,
private explorationMetadataObjectFactory: ExplorationMetadataObjectFactory,
private explorationObjectFactory: ExplorationObjectFactory,
private explorationOpportunitySummaryObjectFactory: ExplorationOpportunitySummaryObjectFactory,
private expressionParserService: ExpressionParserService,
private explorationRecommendationsService: ExplorationRecommendationsService,
private expressionSyntaxTreeService: ExpressionSyntaxTreeService,
private extensionTagAssemblerService: ExtensionTagAssemblerService,
private extractImageFilenamesFromStateService: ExtractImageFilenamesFromStateService,
private feedbackMessageSummaryObjectFactory: FeedbackMessageSummaryObjectFactory,
private feedbackThreadObjectFactory: FeedbackThreadObjectFactory,
private feedbackThreadSummaryObjectFactory: FeedbackThreadSummaryObjectFactory,
private fileDownloadRequestObjectFactory: FileDownloadRequestObjectFactory,
private formatTimePipe: FormatTimePipe,
private fractionInputValidationService: FractionInputValidationService,
private fractionObjectFactory: FractionObjectFactory,
private generateContentIdService: GenerateContentIdService,
private graphDetailService: GraphDetailService,
private graphInputValidationService: GraphInputValidationService,
private graphUtilsService: GraphUtilsService,
private guestCollectionProgressObjectFactory: GuestCollectionProgressObjectFactory,
private guestCollectionProgressService: GuestCollectionProgressService,
private hintObjectFactory: HintObjectFactory,
private htmlEscaperService: HtmlEscaperService,
private i18nLanguageCodeService: I18nLanguageCodeService,
private idGenerationService: IdGenerationService,
private imageClickInputValidationService: ImageClickInputValidationService,
private imageFileObjectFactory: ImageFileObjectFactory,
private improvementActionButtonObjectFactory: ImprovementActionButtonObjectFactory,
private improvementsService: ImprovementsService,
private interactionDetailsCacheService: InteractionDetailsCacheService,
private interactionObjectFactory: InteractionObjectFactory,
private interactionRulesRegistryService: InteractionRulesRegistryService,
private interactionSpecsService: InteractionSpecsService,
private interactiveMapValidationService: InteractiveMapValidationService,
private itemSelectionInputValidationService: ItemSelectionInputValidationService,
private languageUtilService: LanguageUtilService,
private learnerActionObjectFactory: LearnerActionObjectFactory,
private learnerAnswerDetailsBackendApiService: LearnerAnswerDetailsBackendApiService,
private learnerAnswerDetailsObjectFactory: LearnerAnswerDetailsObjectFactory,
private learnerAnswerInfoObjectFactory: LearnerAnswerInfoObjectFactory,
private learnerDashboardActivityIdsObjectFactory: LearnerDashboardActivityIdsObjectFactory,
private learnerDashboardBackendApiService: LearnerDashboardBackendApiService,
private learnerDashboardIdsBackendApiService: LearnerDashboardIdsBackendApiService,
private learnerParamsService: LearnerParamsService,
private localStorageService: LocalStorageService,
private loaderService: LoaderService,
private loggerService: LoggerService,
private logicProofValidationService: LogicProofValidationService,
private lostChangeObjectFactory: LostChangeObjectFactory,
private mathExpressionInputValidationService: MathExpressionInputValidationService,
private messengerService: MessengerService,
private metaTagCustomizationService: MetaTagCustomizationService,
private misconceptionObjectFactory: MisconceptionObjectFactory,
private multipleChoiceInputValidationService: MultipleChoiceInputValidationService,
private musicNotesInputValidationService: MusicNotesInputValidationService,
private musicPhrasePlayerService: MusicPhrasePlayerService,
private newlyCreatedTopicObjectFactory: NewlyCreatedTopicObjectFactory,
private normalizeWhitespacePipe: NormalizeWhitespacePipe,
private normalizeWhitespacePunctuationAndCasePipe: NormalizeWhitespacePunctuationAndCasePipe,
private numberAttemptsService: NumberAttemptsService,
private numericInputValidationService: NumericInputValidationService,
private numberWithUnitsObjectFactory: NumberWithUnitsObjectFactory,
private numberWithUnitsValidationService: NumberWithUnitsValidationService,
private outcomeObjectFactory: OutcomeObjectFactory,
private pageTitleService: PageTitleService,
private paramChangeObjectFactory: ParamChangeObjectFactory,
private paramChangesObjectFactory: ParamChangesObjectFactory,
private paramMetadataObjectFactory: ParamMetadataObjectFactory,
private paramSpecObjectFactory: ParamSpecObjectFactory,
private paramSpecsObjectFactory: ParamSpecsObjectFactory,
private paramTypeObjectFactory: ParamTypeObjectFactory,
private pencilCodeEditorRulesService: PencilCodeEditorRulesService,
private pencilCodeEditorValidationService: PencilCodeEditorValidationService,
private playerCorrectnessFeedbackEnabledService: PlayerCorrectnessFeedbackEnabledService,
private playerPositionService: PlayerPositionService,
private playerTranscriptService: PlayerTranscriptService,
private playthroughIssueObjectFactory: PlaythroughIssueObjectFactory,
private playthroughIssuesBackendApiService: PlaythroughIssuesBackendApiService,
private playthroughObjectFactory: PlaythroughObjectFactory,
private playthroughService: PlaythroughService,
private predictionAlgorithmRegistryService: PredictionAlgorithmRegistryService,
private predictionResultObjectFactory: PredictionResultObjectFactory,
private pretestQuestionBackendApiService: PretestQuestionBackendApiService,
private profilePageBackendApiService: ProfilePageBackendApiService,
private pythonProgramTokenizer: PythonProgramTokenizer,
private questionBackendApiService: QuestionBackendApiService,
private questionCreationService: QuestionCreationService,
private questionSummaryForOneSkillObjectFactory: QuestionSummaryForOneSkillObjectFactory,
private questionSummaryObjectFactory: QuestionSummaryObjectFactory,
private readOnlyCollectionBackendApiService: ReadOnlyCollectionBackendApiService,
private ratingComputationService: RatingComputationService,
private readOnlyStoryNodeObjectFactory: ReadOnlyStoryNodeObjectFactory,
private readOnlySubtopicPageObjectFactory: ReadOnlySubtopicPageObjectFactory,
private readOnlyTopicObjectFactory: ReadOnlyTopicObjectFactory,
private recordedVoiceoversObjectFactory: RecordedVoiceoversObjectFactory,
private reviewTestBackendApiService: ReviewTestBackendApiService,
private reviewTestEngineService: ReviewTestEngineService,
private rubricObjectFactory: RubricObjectFactory,
private ruleObjectFactory: RuleObjectFactory,
private schemaDefaultValueService: SchemaDefaultValueService,
private schemaUndefinedLastElementService: SchemaUndefinedLastElementService,
private searchExplorationsBackendApiService: SearchExplorationsBackendApiService,
private setInputValidationService: SetInputValidationService,
private sVMPredictionService: SVMPredictionService,
private sidebarStatusService: SidebarStatusService,
private siteAnalyticsService: SiteAnalyticsService,
private skillCreationBackendApiService: SkillCreationBackendApiService,
private skillDifficultyObjectFactory: SkillDifficultyObjectFactory,
private skillMasteryBackendApiService: SkillMasteryBackendApiService,
private skillObjectFactory: SkillObjectFactory,
private skillOpportunityObjectFactory: SkillOpportunityObjectFactory,
private skillRightsBackendApiService: SkillRightsBackendApiService,
private skillRightsObjectFactory: SkillRightsObjectFactory,
private skillSummaryObjectFactory: SkillSummaryObjectFactory,
private solutionObjectFactory: SolutionObjectFactory,
private solutionValidityService: SolutionValidityService,
private speechSynthesisChunkerService: SpeechSynthesisChunkerService,
private stateCardObjectFactory: StateCardObjectFactory,
private stateClassifierMappingService: StateClassifierMappingService,
private stateContentService: StateContentService,
private stateCustomizationArgsService: StateCustomizationArgsService,
private stateEditorService: StateEditorService,
private stateGraphLayoutService: StateGraphLayoutService,
private stateHintsService: StateHintsService,
private stateImprovementSuggestionService: StateImprovementSuggestionService,
private stateInteractionIdService: StateInteractionIdService,
private stateInteractionStatsService: StateInteractionStatsService,
private stateNameService: StateNameService,
private stateObjectFactory: StateObjectFactory,
private stateParamChangesService: StateParamChangesService,
private statePropertyService: StatePropertyService,
private stateRecordedVoiceoversService: StateRecordedVoiceoversService,
private stateSolicitAnswerDetailsService: StateSolicitAnswerDetailsService,
private stateSolutionService: StateSolutionService,
private stateTopAnswersStatsBackendApiService: StateTopAnswersStatsBackendApiService,
private stateWrittenTranslationsService: StateWrittenTranslationsService,
private statesObjectFactory: StatesObjectFactory,
private statsReportingService: StatsReportingService,
private stopwatchObjectFactory: StopwatchObjectFactory,
private storyContentsObjectFactory: StoryContentsObjectFactory,
private storyNodeObjectFactory: StoryNodeObjectFactory,
private storyObjectFactory: StoryObjectFactory,
private storyPlaythroughObjectFactory: StoryPlaythroughObjectFactory,
private storyReferenceObjectFactory: StoryReferenceObjectFactory,
private storySummaryObjectFactory: StorySummaryObjectFactory,
private storyViewerBackendApiService: StoryViewerBackendApiService,
private subtitledHtmlObjectFactory: SubtitledHtmlObjectFactory,
private subtopicObjectFactory: SubtopicObjectFactory,
private subtopicPageContentsObjectFactory: SubtopicPageContentsObjectFactory,
private subtopicPageObjectFactory: SubtopicPageObjectFactory,
private subtopicViewerBackendApiService: SubtopicViewerBackendApiService,
private suggestionModalService: SuggestionModalService,
private suggestionObjectFactory: SuggestionObjectFactory,
private suggestionThreadObjectFactory: SuggestionThreadObjectFactory,
private suggestionsService: SuggestionsService,
private textInputPredictionService: TextInputPredictionService,
private textInputRulesService: TextInputRulesService,
private textInputTokenizer: TextInputTokenizer,
private textInputValidationService: TextInputValidationService,
private threadMessageObjectFactory: ThreadMessageObjectFactory,
private threadMessageSummaryObjectFactory: ThreadMessageSummaryObjectFactory,
private threadStatusDisplayService: ThreadStatusDisplayService,
private topicCreationBackendApiService: TopicCreationBackendApiService,
private topicObjectFactory: TopicObjectFactory,
private topicRightsObjectFactory: TopicRightsObjectFactory,
private topicsAndSkillsDashboardBackendApiService: TopicsAndSkillsDashboardBackendApiService,
private topicSummaryObjectFactory: TopicSummaryObjectFactory,
private topicsAndSkillsDashboardFilterObjectFactory: TopicsAndSkillsDashboardFilterObjectFactory,
private topicsAndSkillsDashboardPageService: TopicsAndSkillsDashboardPageService,
private topicViewerBackendApiService: TopicViewerBackendApiService,
private unitsObjectFactory: UnitsObjectFactory,
private urlInterpolationService: UrlInterpolationService,
private urlService: UrlService,
private userExplorationPermissionsService: UserExplorationPermissionsService,
private userInfoObjectFactory: UserInfoObjectFactory,
private utilsService: UtilsService,
private validatorsService: ValidatorsService,
private versionTreeService: VersionTreeService,
private voiceoverObjectFactory: VoiceoverObjectFactory,
private windowDimensionsService: WindowDimensionsService,
private windowRef: WindowRef,
private winnowingPreprocessingService: WinnowingPreprocessingService,
private workedExampleObjectFactory: WorkedExampleObjectFactory,
private writtenTranslationObjectFactory: WrittenTranslationObjectFactory,
private writtenTranslationsObjectFactory: WrittenTranslationsObjectFactory
  ) {}

  public ngAfterViewInit() {
    OppiaAngularRootComponent.adminDataService = this.adminDataService;
    OppiaAngularRootComponent.adminRouterService = this.adminRouterService;
    OppiaAngularRootComponent.adminTaskManagerService = this.adminTaskManagerService;
    OppiaAngularRootComponent.alertsService = this.alertsService;
    OppiaAngularRootComponent.angularNameService = this.angularNameService;
    OppiaAngularRootComponent.answerClassificationResultObjectFactory = this.answerClassificationResultObjectFactory;
    OppiaAngularRootComponent.answerClassificationService = this.answerClassificationService;
    OppiaAngularRootComponent.answerGroupsCacheService = this.answerGroupsCacheService;
    OppiaAngularRootComponent.answerGroupObjectFactory = this.answerGroupObjectFactory;
    OppiaAngularRootComponent.answerStatsObjectFactory = this.answerStatsObjectFactory;
    OppiaAngularRootComponent.appService = this.appService;
    OppiaAngularRootComponent.audioBarStatusService = this.audioBarStatusService;
    OppiaAngularRootComponent.audioFileObjectFactory = this.audioFileObjectFactory;
    OppiaAngularRootComponent.audioLanguageObjectFactory = this.audioLanguageObjectFactory;
    OppiaAngularRootComponent.audioTranslationLanguageService = this.audioTranslationLanguageService;
    OppiaAngularRootComponent.audioTranslationManagerService = this.audioTranslationManagerService;
    OppiaAngularRootComponent.autogeneratedAudioLanguageObjectFactory = this.autogeneratedAudioLanguageObjectFactory;
    OppiaAngularRootComponent.autogeneratedAudioPlayerService = this.autogeneratedAudioPlayerService;
    OppiaAngularRootComponent.autoplayedVideosService = this.autoplayedVideosService;
    OppiaAngularRootComponent.backgroundMaskService = this.backgroundMaskService;
    OppiaAngularRootComponent.baseInteractionValidationService = this.baseInteractionValidationService;
    OppiaAngularRootComponent.browserCheckerService = this.browserCheckerService;
    OppiaAngularRootComponent.camelCaseToHyphensPipe = this.camelCaseToHyphensPipe;
    OppiaAngularRootComponent.changeObjectFactory = this.changeObjectFactory;
    OppiaAngularRootComponent.classifierObjectFactory = this.classifierObjectFactory;
    OppiaAngularRootComponent.classroomBackendApiService = this.classroomBackendApiService;
    OppiaAngularRootComponent.codeNormalizerService = this.codeNormalizerService;
    OppiaAngularRootComponent.codeReplPredictionService = this.codeReplPredictionService;
    OppiaAngularRootComponent.codeReplRulesService = this.codeReplRulesService;
    OppiaAngularRootComponent.codeReplValidationService = this.codeReplValidationService;
    OppiaAngularRootComponent.collectionCreationBackendService = this.collectionCreationBackendService;
    OppiaAngularRootComponent.collectionCreationService = this.collectionCreationService;
    OppiaAngularRootComponent.collectionNodeObjectFactory = this.collectionNodeObjectFactory;
    OppiaAngularRootComponent.collectionObjectFactory = this.collectionObjectFactory;
    OppiaAngularRootComponent.collectionPlaythroughObjectFactory = this.collectionPlaythroughObjectFactory;
    OppiaAngularRootComponent.collectionRightsBackendApiService = this.collectionRightsBackendApiService;
    OppiaAngularRootComponent.collectionRightsObjectFactory = this.collectionRightsObjectFactory;
    OppiaAngularRootComponent.collectionValidationService = this.collectionValidationService;
    OppiaAngularRootComponent.computeGraphService = this.computeGraphService;
    OppiaAngularRootComponent.conceptCardObjectFactory = this.conceptCardObjectFactory;
    OppiaAngularRootComponent.contextService = this.contextService;
    OppiaAngularRootComponent.continueValidationService = this.continueValidationService;
    OppiaAngularRootComponent.contributionOpportunitiesBackendApiService = this.contributionOpportunitiesBackendApiService;
    OppiaAngularRootComponent.constructTranslationIdsService = this.constructTranslationIdsService;
    OppiaAngularRootComponent.countVectorizerService = this.countVectorizerService;
    OppiaAngularRootComponent.creatorDashboardBackendApiService = this.creatorDashboardBackendApiService;
    OppiaAngularRootComponent.csrfTokenService = this.csrfTokenService;
    OppiaAngularRootComponent.currentInteractionService = this.currentInteractionService;
    OppiaAngularRootComponent.dateTimeFormatService = this.dateTimeFormatService;
    OppiaAngularRootComponent.debouncerService = this.debouncerService;
    OppiaAngularRootComponent.deviceInfoService = this.deviceInfoService;
    OppiaAngularRootComponent.documentAttributeCustomizationService = this.documentAttributeCustomizationService;
    OppiaAngularRootComponent.dragAndDropSortInputRulesService = this.dragAndDropSortInputRulesService;
    OppiaAngularRootComponent.dragAndDropSortInputValidationService = this.dragAndDropSortInputValidationService;
    OppiaAngularRootComponent.editableCollectionBackendApiService = this.editableCollectionBackendApiService;
    OppiaAngularRootComponent.editabilityService = this.editabilityService;
    OppiaAngularRootComponent.editorFirstTimeEventsService = this.editorFirstTimeEventsService;
    OppiaAngularRootComponent.endExplorationValidationService = this.endExplorationValidationService;
    OppiaAngularRootComponent.emailDashboardDataService = this.emailDashboardDataService;
    OppiaAngularRootComponent.entityContextObjectFactory = this.entityContextObjectFactory;
    OppiaAngularRootComponent.explorationDiffService = this.explorationDiffService;
    OppiaAngularRootComponent.explorationDraftObjectFactory = this.explorationDraftObjectFactory;
    OppiaAngularRootComponent.explorationFeaturesBackendApiService = this.explorationFeaturesBackendApiService;
    OppiaAngularRootComponent.explorationFeaturesService = this.explorationFeaturesService;
    OppiaAngularRootComponent.explorationHtmlFormatterService = this.explorationHtmlFormatterService;
    OppiaAngularRootComponent.explorationMetadataObjectFactory = this.explorationMetadataObjectFactory;
    OppiaAngularRootComponent.explorationObjectFactory = this.explorationObjectFactory;
    OppiaAngularRootComponent.explorationOpportunitySummaryObjectFactory = this.explorationOpportunitySummaryObjectFactory;
    OppiaAngularRootComponent.expressionParserService = this.expressionParserService;
    OppiaAngularRootComponent.explorationRecommendationsService = this.explorationRecommendationsService;
    OppiaAngularRootComponent.expressionSyntaxTreeService = this.expressionSyntaxTreeService;
    OppiaAngularRootComponent.extensionTagAssemblerService = this.extensionTagAssemblerService;
    OppiaAngularRootComponent.extractImageFilenamesFromStateService = this.extractImageFilenamesFromStateService;
    OppiaAngularRootComponent.feedbackMessageSummaryObjectFactory = this.feedbackMessageSummaryObjectFactory;
    OppiaAngularRootComponent.feedbackThreadObjectFactory = this.feedbackThreadObjectFactory;
    OppiaAngularRootComponent.feedbackThreadSummaryObjectFactory = this.feedbackThreadSummaryObjectFactory;
    OppiaAngularRootComponent.fileDownloadRequestObjectFactory = this.fileDownloadRequestObjectFactory;
    OppiaAngularRootComponent.formatTimePipe = this.formatTimePipe;
    OppiaAngularRootComponent.fractionInputValidationService = this.fractionInputValidationService;
    OppiaAngularRootComponent.fractionObjectFactory = this.fractionObjectFactory;
    OppiaAngularRootComponent.generateContentIdService = this.generateContentIdService;
    OppiaAngularRootComponent.graphDetailService = this.graphDetailService;
    OppiaAngularRootComponent.graphInputValidationService = this.graphInputValidationService;
    OppiaAngularRootComponent.graphUtilsService = this.graphUtilsService;
    OppiaAngularRootComponent.guestCollectionProgressObjectFactory = this.guestCollectionProgressObjectFactory;
    OppiaAngularRootComponent.guestCollectionProgressService = this.guestCollectionProgressService;
    OppiaAngularRootComponent.hintObjectFactory = this.hintObjectFactory;
    OppiaAngularRootComponent.htmlEscaperService = this.htmlEscaperService;
    OppiaAngularRootComponent.i18nLanguageCodeService = this.i18nLanguageCodeService;
    OppiaAngularRootComponent.idGenerationService = this.idGenerationService;
    OppiaAngularRootComponent.imageClickInputValidationService = this.imageClickInputValidationService;
    OppiaAngularRootComponent.imageFileObjectFactory = this.imageFileObjectFactory;
    OppiaAngularRootComponent.improvementActionButtonObjectFactory = this.improvementActionButtonObjectFactory;
    OppiaAngularRootComponent.improvementsService = this.improvementsService;
    OppiaAngularRootComponent.interactionDetailsCacheService = this.interactionDetailsCacheService;
    OppiaAngularRootComponent.interactionObjectFactory = this.interactionObjectFactory;
    OppiaAngularRootComponent.interactionRulesRegistryService = this.interactionRulesRegistryService;
    OppiaAngularRootComponent.interactionSpecsService = this.interactionSpecsService;
    OppiaAngularRootComponent.interactiveMapValidationService = this.interactiveMapValidationService;
    OppiaAngularRootComponent.itemSelectionInputValidationService = this.itemSelectionInputValidationService;
    OppiaAngularRootComponent.languageUtilService = this.languageUtilService;
    OppiaAngularRootComponent.learnerActionObjectFactory = this.learnerActionObjectFactory;
    OppiaAngularRootComponent.learnerAnswerDetailsBackendApiService = this.learnerAnswerDetailsBackendApiService;
    OppiaAngularRootComponent.learnerAnswerDetailsObjectFactory = this.learnerAnswerDetailsObjectFactory;
    OppiaAngularRootComponent.learnerAnswerInfoObjectFactory = this.learnerAnswerInfoObjectFactory;
    OppiaAngularRootComponent.learnerDashboardActivityIdsObjectFactory = this.learnerDashboardActivityIdsObjectFactory;
    OppiaAngularRootComponent.learnerDashboardBackendApiService = this.learnerDashboardBackendApiService;
    OppiaAngularRootComponent.learnerDashboardIdsBackendApiService = this.learnerDashboardIdsBackendApiService;
    OppiaAngularRootComponent.learnerParamsService = this.learnerParamsService;
    OppiaAngularRootComponent.localStorageService = this.localStorageService;
    OppiaAngularRootComponent.loaderService = this.loaderService;
    OppiaAngularRootComponent.loggerService = this.loggerService;
    OppiaAngularRootComponent.logicProofValidationService = this.logicProofValidationService;
    OppiaAngularRootComponent.lostChangeObjectFactory = this.lostChangeObjectFactory;
    OppiaAngularRootComponent.mathExpressionInputValidationService = this.mathExpressionInputValidationService;
    OppiaAngularRootComponent.messengerService = this.messengerService;
    OppiaAngularRootComponent.metaTagCustomizationService = this.metaTagCustomizationService;
    OppiaAngularRootComponent.misconceptionObjectFactory = this.misconceptionObjectFactory;
    OppiaAngularRootComponent.multipleChoiceInputValidationService = this.multipleChoiceInputValidationService;
    OppiaAngularRootComponent.musicNotesInputValidationService = this.musicNotesInputValidationService;
    OppiaAngularRootComponent.musicPhrasePlayerService = this.musicPhrasePlayerService;
    OppiaAngularRootComponent.newlyCreatedTopicObjectFactory = this.newlyCreatedTopicObjectFactory;
    OppiaAngularRootComponent.normalizeWhitespacePipe = this.normalizeWhitespacePipe;
    OppiaAngularRootComponent.normalizeWhitespacePunctuationAndCasePipe = this.normalizeWhitespacePunctuationAndCasePipe;
    OppiaAngularRootComponent.numberAttemptsService = this.numberAttemptsService;
    OppiaAngularRootComponent.numericInputValidationService = this.numericInputValidationService;
    OppiaAngularRootComponent.numberWithUnitsObjectFactory = this.numberWithUnitsObjectFactory;
    OppiaAngularRootComponent.numberWithUnitsValidationService = this.numberWithUnitsValidationService;
    OppiaAngularRootComponent.outcomeObjectFactory = this.outcomeObjectFactory;
    OppiaAngularRootComponent.pageTitleService = this.pageTitleService;
    OppiaAngularRootComponent.paramChangeObjectFactory = this.paramChangeObjectFactory;
    OppiaAngularRootComponent.paramChangesObjectFactory = this.paramChangesObjectFactory;
    OppiaAngularRootComponent.paramMetadataObjectFactory = this.paramMetadataObjectFactory;
    OppiaAngularRootComponent.paramSpecObjectFactory = this.paramSpecObjectFactory;
    OppiaAngularRootComponent.paramSpecsObjectFactory = this.paramSpecsObjectFactory;
    OppiaAngularRootComponent.paramTypeObjectFactory = this.paramTypeObjectFactory;
    OppiaAngularRootComponent.pencilCodeEditorRulesService = this.pencilCodeEditorRulesService;
    OppiaAngularRootComponent.pencilCodeEditorValidationService = this.pencilCodeEditorValidationService;
    OppiaAngularRootComponent.playerCorrectnessFeedbackEnabledService = this.playerCorrectnessFeedbackEnabledService;
    OppiaAngularRootComponent.playerPositionService = this.playerPositionService;
    OppiaAngularRootComponent.playerTranscriptService = this.playerTranscriptService;
    OppiaAngularRootComponent.playthroughIssueObjectFactory = this.playthroughIssueObjectFactory;
    OppiaAngularRootComponent.playthroughIssuesBackendApiService = this.playthroughIssuesBackendApiService;
    OppiaAngularRootComponent.playthroughObjectFactory = this.playthroughObjectFactory;
    OppiaAngularRootComponent.playthroughService = this.playthroughService;
    OppiaAngularRootComponent.predictionAlgorithmRegistryService = this.predictionAlgorithmRegistryService;
    OppiaAngularRootComponent.predictionResultObjectFactory = this.predictionResultObjectFactory;
    OppiaAngularRootComponent.pretestQuestionBackendApiService = this.pretestQuestionBackendApiService;
    OppiaAngularRootComponent.profilePageBackendApiService = this.profilePageBackendApiService;
    OppiaAngularRootComponent.pythonProgramTokenizer = this.pythonProgramTokenizer;
    OppiaAngularRootComponent.questionBackendApiService = this.questionBackendApiService;
    OppiaAngularRootComponent.questionCreationService = this.questionCreationService;
    OppiaAngularRootComponent.questionSummaryForOneSkillObjectFactory = this.questionSummaryForOneSkillObjectFactory;
    OppiaAngularRootComponent.questionSummaryObjectFactory = this.questionSummaryObjectFactory;
    OppiaAngularRootComponent.readOnlyCollectionBackendApiService = this.readOnlyCollectionBackendApiService;
    OppiaAngularRootComponent.ratingComputationService = this.ratingComputationService;
    OppiaAngularRootComponent.readOnlyStoryNodeObjectFactory = this.readOnlyStoryNodeObjectFactory;
    OppiaAngularRootComponent.readOnlySubtopicPageObjectFactory = this.readOnlySubtopicPageObjectFactory;
    OppiaAngularRootComponent.readOnlyTopicObjectFactory = this.readOnlyTopicObjectFactory;
    OppiaAngularRootComponent.recordedVoiceoversObjectFactory = this.recordedVoiceoversObjectFactory;
    OppiaAngularRootComponent.reviewTestBackendApiService = this.reviewTestBackendApiService;
    OppiaAngularRootComponent.reviewTestEngineService = this.reviewTestEngineService;
    OppiaAngularRootComponent.rubricObjectFactory = this.rubricObjectFactory;
    OppiaAngularRootComponent.ruleObjectFactory = this.ruleObjectFactory;
    OppiaAngularRootComponent.schemaDefaultValueService = this.schemaDefaultValueService;
    OppiaAngularRootComponent.schemaUndefinedLastElementService = this.schemaUndefinedLastElementService;
    OppiaAngularRootComponent.searchExplorationsBackendApiService = this.searchExplorationsBackendApiService;
    OppiaAngularRootComponent.setInputValidationService = this.setInputValidationService;
    OppiaAngularRootComponent.sVMPredictionService = this.sVMPredictionService;
    OppiaAngularRootComponent.sidebarStatusService = this.sidebarStatusService;
    OppiaAngularRootComponent.siteAnalyticsService = this.siteAnalyticsService;
    OppiaAngularRootComponent.skillCreationBackendApiService = this.skillCreationBackendApiService;
    OppiaAngularRootComponent.skillDifficultyObjectFactory = this.skillDifficultyObjectFactory;
    OppiaAngularRootComponent.skillMasteryBackendApiService = this.skillMasteryBackendApiService;
    OppiaAngularRootComponent.skillObjectFactory = this.skillObjectFactory;
    OppiaAngularRootComponent.skillOpportunityObjectFactory = this.skillOpportunityObjectFactory;
    OppiaAngularRootComponent.skillRightsBackendApiService = this.skillRightsBackendApiService;
    OppiaAngularRootComponent.skillRightsObjectFactory = this.skillRightsObjectFactory;
    OppiaAngularRootComponent.skillSummaryObjectFactory = this.skillSummaryObjectFactory;
    OppiaAngularRootComponent.solutionObjectFactory = this.solutionObjectFactory;
    OppiaAngularRootComponent.solutionValidityService = this.solutionValidityService;
    OppiaAngularRootComponent.speechSynthesisChunkerService = this.speechSynthesisChunkerService;
    OppiaAngularRootComponent.stateCardObjectFactory = this.stateCardObjectFactory;
    OppiaAngularRootComponent.stateClassifierMappingService = this.stateClassifierMappingService;
    OppiaAngularRootComponent.stateContentService = this.stateContentService;
    OppiaAngularRootComponent.stateCustomizationArgsService = this.stateCustomizationArgsService;
    OppiaAngularRootComponent.stateEditorService = this.stateEditorService;
    OppiaAngularRootComponent.stateGraphLayoutService = this.stateGraphLayoutService;
    OppiaAngularRootComponent.stateHintsService = this.stateHintsService;
    OppiaAngularRootComponent.stateImprovementSuggestionService = this.stateImprovementSuggestionService;
    OppiaAngularRootComponent.stateInteractionIdService = this.stateInteractionIdService;
    OppiaAngularRootComponent.stateInteractionStatsService = this.stateInteractionStatsService;
    OppiaAngularRootComponent.stateNameService = this.stateNameService;
    OppiaAngularRootComponent.stateObjectFactory = this.stateObjectFactory;
    OppiaAngularRootComponent.stateParamChangesService = this.stateParamChangesService;
    OppiaAngularRootComponent.statePropertyService = this.statePropertyService;
    OppiaAngularRootComponent.stateRecordedVoiceoversService = this.stateRecordedVoiceoversService;
    OppiaAngularRootComponent.stateSolicitAnswerDetailsService = this.stateSolicitAnswerDetailsService;
    OppiaAngularRootComponent.stateSolutionService = this.stateSolutionService;
    OppiaAngularRootComponent.stateTopAnswersStatsBackendApiService = this.stateTopAnswersStatsBackendApiService;
    OppiaAngularRootComponent.stateWrittenTranslationsService = this.stateWrittenTranslationsService;
    OppiaAngularRootComponent.statesObjectFactory = this.statesObjectFactory;
    OppiaAngularRootComponent.statsReportingService = this.statsReportingService;
    OppiaAngularRootComponent.stopwatchObjectFactory = this.stopwatchObjectFactory;
    OppiaAngularRootComponent.storyContentsObjectFactory = this.storyContentsObjectFactory;
    OppiaAngularRootComponent.storyNodeObjectFactory = this.storyNodeObjectFactory;
    OppiaAngularRootComponent.storyObjectFactory = this.storyObjectFactory;
    OppiaAngularRootComponent.storyPlaythroughObjectFactory = this.storyPlaythroughObjectFactory;
    OppiaAngularRootComponent.storyReferenceObjectFactory = this.storyReferenceObjectFactory;
    OppiaAngularRootComponent.storySummaryObjectFactory = this.storySummaryObjectFactory;
    OppiaAngularRootComponent.storyViewerBackendApiService = this.storyViewerBackendApiService;
    OppiaAngularRootComponent.subtitledHtmlObjectFactory = this.subtitledHtmlObjectFactory;
    OppiaAngularRootComponent.subtopicObjectFactory = this.subtopicObjectFactory;
    OppiaAngularRootComponent.subtopicPageContentsObjectFactory = this.subtopicPageContentsObjectFactory;
    OppiaAngularRootComponent.subtopicPageObjectFactory = this.subtopicPageObjectFactory;
    OppiaAngularRootComponent.subtopicViewerBackendApiService = this.subtopicViewerBackendApiService;
    OppiaAngularRootComponent.suggestionModalService = this.suggestionModalService;
    OppiaAngularRootComponent.suggestionObjectFactory = this.suggestionObjectFactory;
    OppiaAngularRootComponent.suggestionThreadObjectFactory = this.suggestionThreadObjectFactory;
    OppiaAngularRootComponent.suggestionsService = this.suggestionsService;
    OppiaAngularRootComponent.textInputPredictionService = this.textInputPredictionService;
    OppiaAngularRootComponent.textInputRulesService = this.textInputRulesService;
    OppiaAngularRootComponent.textInputTokenizer = this.textInputTokenizer;
    OppiaAngularRootComponent.textInputValidationService = this.textInputValidationService;
    OppiaAngularRootComponent.threadMessageObjectFactory = this.threadMessageObjectFactory;
    OppiaAngularRootComponent.threadMessageSummaryObjectFactory = this.threadMessageSummaryObjectFactory;
    OppiaAngularRootComponent.threadStatusDisplayService = this.threadStatusDisplayService;
    OppiaAngularRootComponent.topicCreationBackendApiService = this.topicCreationBackendApiService;
    OppiaAngularRootComponent.topicObjectFactory = this.topicObjectFactory;
    OppiaAngularRootComponent.topicRightsObjectFactory = this.topicRightsObjectFactory;
    OppiaAngularRootComponent.topicsAndSkillsDashboardBackendApiService = this.topicsAndSkillsDashboardBackendApiService;
    OppiaAngularRootComponent.topicSummaryObjectFactory = this.topicSummaryObjectFactory;
    OppiaAngularRootComponent.topicsAndSkillsDashboardFilterObjectFactory = this.topicsAndSkillsDashboardFilterObjectFactory;
    OppiaAngularRootComponent.topicsAndSkillsDashboardPageService = this.topicsAndSkillsDashboardPageService;
    OppiaAngularRootComponent.topicViewerBackendApiService = this.topicViewerBackendApiService;
    OppiaAngularRootComponent.unitsObjectFactory = this.unitsObjectFactory;
    OppiaAngularRootComponent.urlInterpolationService = this.urlInterpolationService;
    OppiaAngularRootComponent.urlService = this.urlService;
    OppiaAngularRootComponent.userExplorationPermissionsService = this.userExplorationPermissionsService;
    OppiaAngularRootComponent.userInfoObjectFactory = this.userInfoObjectFactory;
    OppiaAngularRootComponent.utilsService = this.utilsService;
    OppiaAngularRootComponent.validatorsService = this.validatorsService;
    OppiaAngularRootComponent.versionTreeService = this.versionTreeService;
    OppiaAngularRootComponent.voiceoverObjectFactory = this.voiceoverObjectFactory;
    OppiaAngularRootComponent.windowDimensionsService = this.windowDimensionsService;
    OppiaAngularRootComponent.windowRef = this.windowRef;
    OppiaAngularRootComponent.winnowingPreprocessingService = this.winnowingPreprocessingService;
    OppiaAngularRootComponent.workedExampleObjectFactory = this.workedExampleObjectFactory;
    OppiaAngularRootComponent.writtenTranslationObjectFactory = this.writtenTranslationObjectFactory;
    OppiaAngularRootComponent.writtenTranslationsObjectFactory = this.writtenTranslationsObjectFactory;
    // This emit triggers ajs to start its app.
    this.initialized.emit();
  }
}
