from typing import Any, Dict, Optional, Text

class App:
    name: Text = ...
    credential: Optional[object] = ...
    options: Optional[Dict[Text, Any]] = ...
    project_id: Text = ...

def get_app(name: Optional[Text] = ...) -> App: ...

def initialize_app(
        credential: Optional[object] = ...,
        options: Optional[Dict[Text, Any]] = ...,
        name: Text = ...
) -> App: ...
