// Copyright 2025 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Unit tests for DisplaySolutionModalComponent.
 */

import {HttpClientTestingModule} from '@angular/common/http/testing';
import {ComponentFixture, TestBed, waitForAsync} from '@angular/core/testing';
import {NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';
import {StateCard} from '../../../../../domain/state_card/state-card.model';
import {AudioPlayerService} from '../../../../../services/audio-player.service';
import {AutogeneratedAudioPlayerService} from '../../../../../services/autogenerated-audio-player.service';
import {HintsAndSolutionManagerService} from '../../../services/hints-and-solution-manager.service';
import {PlayerPositionService} from '../../../services/player-position.service';
import {PlayerTranscriptService} from '../../../services/player-transcript.service';
import {DisplayNewSolutionModalComponent} from './display-new-solution-modal.component';
import {MockTranslatePipe} from '../../../../../tests/unit-test-utils';
import {Interaction} from '../../../../../domain/exploration/interaction.model';
import {InteractionDisplayComponent} from '../../../../../components/interaction-display/interaction-display.component';
import {NO_ERRORS_SCHEMA} from '@angular/core';
import {ResponsesService} from '../../../../exploration-editor-page/editor-tab/services/responses.service';
import {ShortAnswerResponse} from '../../../../../domain/exploration/solution.model';

describe('Display Solution Modal', () => {
  let fixture: ComponentFixture<DisplayNewSolutionModalComponent>;
  let componentInstance: DisplayNewSolutionModalComponent;
  let playerTranscriptService: PlayerTranscriptService;
  let audioPlayerService: AudioPlayerService;
  let autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService;
  let ngbActiveModal: NgbActiveModal;
  let responsesService: ResponsesService;
  let contentId = 'content_id';
  let solutionHtml: string = 'solution_html';
  let shortAnswerResponse: ShortAnswerResponse = {
    prefix: 'The only',
    answer: 'html',
  };

  class MockHintsAndSolutionManagerService {
    displaySolution(): object {
      return {
        explanation: {
          contentId: contentId,
          html: 'html',
        },
        getOppiaSolutionExplanationResponseHtml(): string {
          return solutionHtml;
        },
      };
    }
  }

  class MockMatBottomSheetRef {
    dismiss(): void {}
  }

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      declarations: [
        DisplayNewSolutionModalComponent,
        MockTranslatePipe,
        InteractionDisplayComponent,
      ],
      providers: [
        NgbActiveModal,
        AudioPlayerService,
        AutogeneratedAudioPlayerService,
        {
          provide: HintsAndSolutionManagerService,
          useClass: MockHintsAndSolutionManagerService,
        },
        PlayerPositionService,
        PlayerTranscriptService,
        ResponsesService,
      ],
      schemas: [NO_ERRORS_SCHEMA],
    }).compileComponents();
  }));

  beforeEach(() => {
    fixture = TestBed.createComponent(DisplayNewSolutionModalComponent);
    componentInstance = fixture.componentInstance;
    playerTranscriptService = TestBed.inject(PlayerTranscriptService);
    audioPlayerService = TestBed.inject(AudioPlayerService);
    autogeneratedAudioPlayerService = TestBed.inject(
      AutogeneratedAudioPlayerService
    );
    ngbActiveModal = TestBed.inject(NgbActiveModal);
    responsesService = TestBed.inject(ResponsesService);
  });

  it('should create', () => {
    expect(componentInstance).toBeDefined();
  });

  it('should intialize', () => {
    let contentId: string = 'content_id';
    let interaction = {} as Interaction;
    let displayedCard = new StateCard(
      'test_name',
      'content',
      'interaction',
      interaction,
      [],
      contentId
    );
    spyOn(playerTranscriptService, 'getCard').and.returnValue(displayedCard);
    spyOn(responsesService, 'getOppiaShortAnswerResponseHtml').and.returnValue(
      shortAnswerResponse
    );

    componentInstance.ngOnInit();

    expect(componentInstance.solutionContentId).toEqual(contentId);
    expect(componentInstance.displayedCard).toEqual(displayedCard);
    expect(componentInstance.interaction).toEqual(
      displayedCard.getInteraction()
    );
    expect(
      responsesService.getOppiaShortAnswerResponseHtml
    ).toHaveBeenCalledWith(interaction, componentInstance.solution);
    expect(componentInstance.shortAnswerHtml).toEqual(shortAnswerResponse);
    expect(componentInstance.solutionExplanationHtml).toEqual(solutionHtml);
  });

  it('should close modal with ngbActiveModal', () => {
    spyOn(audioPlayerService, 'stop');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(ngbActiveModal, 'dismiss');

    componentInstance.closeModal();

    expect(audioPlayerService.stop).toHaveBeenCalled();
    expect(autogeneratedAudioPlayerService.cancel).toHaveBeenCalled();
    expect(ngbActiveModal.dismiss).toHaveBeenCalledWith('cancel');
  });

  it('should close modal with bottomSheetRef', () => {
    let mockBottomSheetRef = new MockMatBottomSheetRef();
    spyOn(audioPlayerService, 'stop');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(mockBottomSheetRef, 'dismiss');
    spyOn(ngbActiveModal, 'dismiss');

    Object.defineProperty(componentInstance, 'bottomSheetRef', {
      value: mockBottomSheetRef,
      writable: true,
    });

    componentInstance.closeModal();

    expect(audioPlayerService.stop).toHaveBeenCalled();
    expect(autogeneratedAudioPlayerService.cancel).toHaveBeenCalled();
    expect(mockBottomSheetRef.dismiss).toHaveBeenCalled();
    expect(ngbActiveModal.dismiss).not.toHaveBeenCalled();
  });
});
