name: Feature request
description: Suggest an idea for this project
title: "[Feature Request]: "
labels: ["triage needed", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a new feature in the Oppia project.
  - type: markdown
    attributes:
      value: |
        Before filing a new issue, **please do a quick search** to check that it hasn't already been filed on the issue tracker. You can do this by going to [this link](https://github.com/oppia/oppia/issues) and typing some words related to the issue in the search box next to the "New issue" button.
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem? Please describe.
      description: A clear and concise description of what the problem is. **Example:** "I'm always frustrated when [...]"
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution (or solutions) you'd like
      description: A clear and concise description of what you want to happen. **Example:** "I would like to have [...]"
    validations:
      required: true
  - type: textarea
    id: rejected-alternatives
    attributes:
      label: Describe alternatives you've considered and rejected
      description: A clear and concise description of any alternative solutions you've considered and rejected, and why you rejected them. **Example:** "I have considered [...] but decided that the above solution is better because [...]"
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Add any other context or screenshots about the feature request here.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
