name: CI Flake report
description: Create a report to help us improve
title: "[Flake]: "
labels: [triage needed, bug]
body:
  - type: dropdown
    id: ci-test-type
    attributes:
      label: CI Test Type
      description: In which CI test did this Flake occur?
      options:
        - Frontend
        - E2E
        - Acceptance
        - Backend
        - Backend associated test file check
        - Lighthouse CI performance
        - Lighthouse CI accessibility
        - Other
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Stacktrace
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Add any other context about the flake here.
    validations:
      required: false
  - type: textarea
    id: occurrences
    attributes:
      label: Occurrences
      description: How many times has this flake occurred? Please provide a link to the flake report and the date of each occurrence.
    validations:
      required: true
  - type: input
    attributes:
      label: Debugging document link
      description: If you have started a debugging doc, please paste the link here. Make sure that the sharing settings are set to "Anyone with the link can comment".
    validations:
      required: false
