blank_issues_enabled: true
contact_links:
  - name: Oppia Community Support
    url: https://github.com/oppia/oppia/discussions
    about: Please ask and answer questions here.
  - name: Oppia Security Bug Report
    url: https://github.com/oppia/oppia/blob/develop/.github/SECURITY.md
    about: Please read how to report security bugs here.
