// Copyright 2014 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview A service that maintains a record of the objects exclusive to
 * a state.
 */

require('components/QuestionCreationService.ts');
require('components/RatingComputationService.ts');
require('components/StateGraphLayoutService.ts');
require('domain/classifier/AnswerClassificationResultObjectFactory.ts');
require('domain/classifier/ClassifierObjectFactory.ts');
require('domain/collection/GuestCollectionProgressService.ts');
require('domain/editor/undo_redo/UndoRedoService.ts');
require('domain/exploration/EditableExplorationBackendApiService.ts');
require('domain/exploration/ExplorationObjectFactory.ts');
require('domain/exploration/ParamChangeObjectFactory.ts');
require('domain/exploration/ReadOnlyExplorationBackendApiService.ts');
require('domain/exploration/RuleObjectFactory.ts');
require('domain/exploration/StatesObjectFactory.ts');
require('domain/exploration/SubtitledHtmlObjectFactory.ts');
require('domain/feedback_thread/FeedbackThreadObjectFactory.ts');
require('domain/question/EditableQuestionBackendApiService.ts');
require('domain/question/PretestQuestionBackendApiService.ts');
require('domain/question/QuestionObjectFactory.ts');
require('domain/skill/ConceptCardBackendApiService.ts');
require('domain/skill/ConceptCardObjectFactory.ts');
require('domain/skill/EditableSkillBackendApiService.ts');
require('domain/skill/MisconceptionObjectFactory.ts');
require('domain/skill/SkillObjectFactory.ts');
require('domain/skill/SkillRightsBackendApiService.ts');
require('domain/skill/SkillRightsObjectFactory.ts');
require('domain/skill/SkillUpdateService.ts');
require('domain/state/StateObjectFactory.ts');
require('domain/state_card/StateCardObjectFactory.ts');
require('domain/suggestion/SuggestionObjectFactory.ts');
require('domain/suggestion/SuggestionThreadObjectFactory.ts');
require('domain/summary/ExplorationSummaryBackendApiService.ts');
require('domain/utilities/BrowserCheckerService.ts');
require('domain/utilities/LanguageUtilService.ts');
require('domain/utilities/StopwatchObjectFactory.ts');
require('domain/utilities/UrlInterpolationService.ts');
require('expressions/ExpressionInterpolationService.ts');
require('pages/exploration_editor/EditorFirstTimeEventsService.ts');
require('pages/topic_editor/TopicEditorStateService.ts');
require('pages/skill_editor/SkillEditorRoutingService.ts');
require('pages/skill_editor/SkillEditorStateService.ts');
require('pages/state_editor/state_properties/StateEditorService.ts');
require('pages/state_editor/state_properties/StatePropertyService.ts');
require('pages/suggestion_editor/ShowSuggestionModalForEditorViewService.ts');
require('pages/suggestion_editor/ShowSuggestionModalForLearnerLocalViewService.ts');
require('services/AlertsService.ts');
require('services/AssetsBackendApiService.ts');
require('services/AudioPlayerService.ts');
require('services/AutogeneratedAudioPlayerService.ts');
require('services/ComputeGraphService.ts');
require('services/ContextService.ts');
require('services/DateTimeFormatService.ts');
require('services/EditabilityService.ts');
require('services/ExplorationFeaturesBackendApiService.ts');
require('services/ExplorationFeaturesService.ts');
require('services/ExplorationHtmlFormatterService.ts');
require('services/GenerateContentIdService.ts');
require('services/HtmlEscaperService.ts');
require('services/IdGenerationService.ts');
require('services/ImprovementCardService.ts');
require('services/ImprovementsService.ts');
require('services/LocalStorageService.ts');
require('services/MessengerService.ts');
require('services/PlaythroughIssuesService.ts');
require('services/PlaythroughService.ts');
require('services/SiteAnalyticsService.ts');
require('services/StateRulesStatsService.ts');
require('services/StateTopAnswersStatsService.ts');
require('services/UserService.ts');
require('services/UtilsService.ts');
require('services/ValidatorsService.ts');
require('services/contextual/DeviceInfoService.ts');
require('services/contextual/UrlService.ts');
require('services/contextual/WindowDimensionsService.ts');
require('services/stateful/BackgroundMaskService.ts');
require('services/stateful/FocusManagerService.ts');

oppia.factory('StateEditorService', [
  '$log', 'SolutionValidityService',
  function(
      $log, SolutionValidityService) {
    var activeStateName = null;
    var stateNames = [];
    var correctnessFeedbackEnabled = null;
    var inQuestionMode = null;
    // Currently, the only place where this is used in the state editor
    // is in solution verification. So, once the interaction is set in this
    // service, the given solutions would be automatically verified for the set
    // interaction.
    var interaction = null;
    var misconceptions = [];
    var explorationIsWhitelisted = false;

    return {
      getActiveStateName: function() {
        return activeStateName;
      },
      setActiveStateName: function(newActiveStateName) {
        if (newActiveStateName === '' || newActiveStateName === null) {
          $log.error('Invalid active state name: ' + newActiveStateName);
          return;
        }
        activeStateName = newActiveStateName;
      },
      isExplorationWhitelisted: function() {
        return explorationIsWhitelisted;
      },
      updateExplorationWhitelistedStatus: function(value) {
        explorationIsWhitelisted = value;
      },
      setMisconceptions: function(newMisconceptions) {
        misconceptions = newMisconceptions;
      },
      getMisconceptions: function() {
        return angular.copy(misconceptions);
      },
      setInteraction: function(newInteraction) {
        interaction = newInteraction;
      },
      setInteractionId: function(newId) {
        interaction.setId(newId);
      },
      setInteractionAnswerGroups: function(newAnswerGroups) {
        interaction.setAnswerGroups(newAnswerGroups);
      },
      setInteractionDefaultOutcome: function(newOutcome) {
        interaction.setDefaultOutcome(newOutcome);
      },
      setInteractionCustomizationArgs: function(newArgs) {
        interaction.setCustomizationArgs(newArgs);
      },
      setInteractionSolution: function(solution) {
        interaction.setSolution(solution);
      },
      setInteractionHints: function(hints) {
        interaction.setHints(hints);
      },
      getInteraction: function() {
        return angular.copy(interaction);
      },
      getAnswerChoices: function(interactionId, customizationArgs) {
        if (!interactionId) {
          return null;
        }
        // Special cases for multiple choice input and image click input.
        if (interactionId === 'MultipleChoiceInput') {
          return customizationArgs.choices.value.map(
            function(val, ind) {
              return {
                val: ind,
                label: val
              };
            }
          );
        } else if (interactionId === 'ImageClickInput') {
          var _answerChoices = [];
          var imageWithRegions =
            customizationArgs.imageAndRegions.value;
          for (
            var j = 0; j < imageWithRegions.labeledRegions.length; j++) {
            _answerChoices.push({
              val: imageWithRegions.labeledRegions[j].label,
              label: imageWithRegions.labeledRegions[j].label
            });
          }
          return _answerChoices;
        } else if (interactionId === 'ItemSelectionInput' ||
            interactionId === 'DragAndDropSortInput') {
          return customizationArgs.choices.value.map(function(val) {
            return {
              val: val,
              label: val
            };
          });
        } else {
          return null;
        }
      },
      setInQuestionMode: function(newModeValue) {
        inQuestionMode = newModeValue;
      },
      isInQuestionMode: function() {
        return inQuestionMode;
      },
      setCorrectnessFeedbackEnabled: function(newCorrectnessFeedbackEnabled) {
        correctnessFeedbackEnabled = newCorrectnessFeedbackEnabled;
      },
      getCorrectnessFeedbackEnabled: function() {
        return correctnessFeedbackEnabled;
      },
      setStateNames: function(newStateNames) {
        stateNames = newStateNames;
      },
      getStateNames: function() {
        return stateNames;
      },
      isCurrentSolutionValid: function() {
        return SolutionValidityService.isSolutionValid(activeStateName);
      },
      deleteCurrentSolutionValidity: function() {
        SolutionValidityService.deleteSolutionValidity(activeStateName);
      }
    };
  }]);
