# Copyright 2021 The Oppia Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Controllers for the oppia root page."""

from __future__ import annotations

import urllib

from core import feconf
from core.controllers import acl_decorators, base

import webapp2
from typing import Dict


class OppiaRootPage(base.BaseHandler[Dict[str, str], Dict[str, str]]):
    """Renders oppia root page (unified entry point) for all routes registered
    with angular router.
    """

    # Using type ignore[misc] here because untyped decorator makes function
    # "get" also untyped.
    # The '**kwargs' argument is needed because some routes pass keyword
    # arguments and even when we don't use them we need to allow them so that
    # there is no error in the callsite.
    @acl_decorators.open_access
    def get(self, **kwargs: Dict[str, str]) -> None:
        """Handles GET requests."""
        url = self.request.uri
        if 'explore' in url or 'embed' in url:
            self.render_template(
                'oppia-root.mainpage.html', iframe_restriction=None
            )
            return

        self.render_template('oppia-root.mainpage.html')


class OppiaLightweightRootPage(webapp2.RequestHandler):
    """Renders oppia root page (unified entry point) for all routes registered
    with angular router, without performing any user-specific work first.

    The HTML sent to the client is identical whether the requester is logged in
    or not; there is no user-specific content in it (the Angular app fetches
    all user data through the API handlers after it boots). However,
    BaseHandler verifies the session cookie against Firebase, looks up the user
    settings, updates the 'last logged in' timestamp and constructs the user
    actions info on every request, which adds ~155-470ms to the time-to-first
    byte for logged-in users. This handler deliberately skips the entire
    BaseHandler auth pipeline and streams the HTML immediately, so the auth and
    user lookups move to the first API call (e.g. /userinfohandler) made by the
    Angular app.
    """

    # The '**kwargs' argument is needed because some routes pass keyword
    # arguments and even when we don't use them we need to allow them so that
    # there is no error in the callsite. Here we use pylint disable because
    # the '**kwargs' argument is purposefully unused.
    def get(  # pylint: disable=unused-argument
        self, **kwargs: Dict[str, str]
    ) -> None:
        """Handles GET requests."""
        request_split = urllib.parse.urlsplit(self.request.uri)
        # If the request is to the old demo server, redirect it permanently to
        # the new demo server. (Unless it is a cron job or tasks request,
        # because cron job and tasks destination URLs are generated by
        # App Engine and we can't change their destination.)
        if (
            request_split.netloc == 'oppiaserver.appspot.com'
            and not request_split.path.startswith(('/cron/', '/task/'))
        ):
            self.redirect('https://oppiatestserver.appspot.com', permanent=True)
            return

        # In maintenance mode all HTTP requests (except the maintenance page
        # itself) are redirected to the maintenance page. Because this handler
        # skips authentication it cannot exempt logged-in site maintainers the
        # way BaseHandler does, so everyone is redirected.
        if (
            feconf.ENABLE_MAINTENANCE_MODE
            and self.request.path != '/maintenance'
        ):
            self.redirect('/maintenance')
            return

        url = self.request.uri
        if 'explore' in url or 'embed' in url:
            base.render_html_response(
                self.response,
                'oppia-root.mainpage.html',
                iframe_restriction=None,
            )
            return

        base.render_html_response(self.response, 'oppia-root.mainpage.html')
