FROM node:16.13.0-slim AS frontend

WORKDIR /app/oppia

RUN sed -i 's|deb.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    sed -i 's|security.debian.org|archive.debian.org|g' /etc/apt/sources.list && \
    apt-get update -y && apt-get install -y \
        chromium \
        curl \
        git \
        ca-certificates && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Installing packages from the package.json file.
COPY package.json .
COPY scripts/linters/custom_eslint_checks ./scripts/linters/custom_eslint_checks

COPY yarn.lock .
RUN npm install -g yarn@1.22.15 --force
RUN yarn install --pure-lockfile

# Clean up temporary files
RUN rm -rf /tmp/* /var/tmp/*
