name: 'Merge from Base Branch if Action Running on a PR'
description: 'Merge from the base branch the PR is being merged into.'
runs:
  using: 'composite'
  steps:
    - name: Debugging
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - id: merge
      name: Merge
      run: |
        if [[ ${{ github.event_name}} != "pull_request" ]]
        then
          echo "Skipping merge because not triggered by a PR event."
          exit 0
        fi
        echo "Base Repository: ${{ github.repository }}"
        echo "Base Branch: ${{ github.base_ref }}"
        echo "Head Repository: ${{ github.event.pull_request.head.repo.full_name }}"
        echo "Head Branch: $GITHUB_HEAD_REF"
        git remote add source "https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git"
        git fetch source $GITHUB_HEAD_REF
        git checkout source/$GITHUB_HEAD_REF
        git remote add base "https://github.com/${{ github.repository }}.git"
        git fetch base ${{ github.base_ref }}
        git merge base/${{ github.base_ref }}
      shell: bash
