name: 'Merge from Base Branch if Action Running on a PR'
description: 'Merge from the base branch the PR is being merged into.'
runs:
  using: 'composite'
  steps:
    - id: merge
      run: |
        if [[ ${{ github.event_name}} != "pull_request" && ${{ github.event_name }} != "pull_request_target" ]]
        then
          echo "Skipping merge because not triggered by a PR event."
          exit 0
        fi
        echo "Base Repository: ${{ github.repository }}"
        echo "Base Branch: ${{ github.base_ref }}"
        git remote add upstream "https://github.com/${{ github.repository }}.git"
        git fetch upstream ${{ github.base_ref }}
        git checkout ${{ github.base_ref }}
        git merge --ff-only upstream/${{ github.base_ref }}
        git show
      shell: bash
