name: 'Merge from Base Branch if Action Running on a PR'
description: 'Merge from the base branch the PR is being merged into.'
runs:
  using: 'composite'
  steps:
    - name: Debugging
      run: echo "$GITHUB_CONTEXT"
      shell: bash
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - id: merge
      name: Merge
      run: |
        if [[ ${{ github.event_name}} != "pull_request" && ${{ github.event_name }} != "pull_request_target" ]]
        then
          echo "Skipping merge because not triggered by a PR event."
          exit 0
        fi
        echo "Base Repository: ${{ github.repository }}"
        echo "Base Branch: ${{ github.base_ref }}"
        echo "Head Branch: $GITHUB_HEAD_REF"
        git checkout $GITHUB_HEAD_REF
        git remote add upstream "https://github.com/${{ github.repository }}.git"
        git fetch upstream ${{ github.base_ref }}
        git merge --ff-only upstream/${{ github.base_ref }}
      shell: bash
