// Copyright 2022 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Unit tests for Conversation skin component.
 */

import { HttpClientTestingModule } from '@angular/common/http/testing';
import { EventEmitter, NO_ERRORS_SCHEMA } from '@angular/core';
import { ComponentFixture, fakeAsync, TestBed, tick, waitForAsync } from '@angular/core/testing';
import { QuestionPlayerStateService } from 'components/question-directives/question-player/services/question-player-state.service';
import { Collection } from 'domain/collection/collection.model';
import { GuestCollectionProgressService } from 'domain/collection/guest-collection-progress.service';
import { ReadOnlyCollectionBackendApiService } from 'domain/collection/read-only-collection-backend-api.service';
import { Interaction } from 'domain/exploration/InteractionObjectFactory';
import { ExplorationRecommendationsBackendApiService } from 'domain/recommendations/exploration-recommendations-backend-api.service';
import { ConceptCardBackendApiService } from 'domain/skill/concept-card-backend-api.service';
import { StateCard } from 'domain/state_card/state-card.model';
import { StoryViewerBackendApiService } from 'domain/story_viewer/story-viewer-backend-api.service';
import { ExplorationSummaryBackendApiService } from 'domain/summary/exploration-summary-backend-api.service';
import { UserInfo } from 'domain/user/user-info.model';
import { UrlInterpolationService } from 'domain/utilities/url-interpolation.service';
import { CollectionPlayerBackendApiService } from 'pages/collection-player-page/services/collection-player-backend-api.service';
import { AlertsService } from 'services/alerts.service';
import { AudioPlayerService } from 'services/audio-player.service';
import { AutogeneratedAudioPlayerService } from 'services/autogenerated-audio-player.service';
import { ContextService } from 'services/context.service';
import { UrlService } from 'services/contextual/url.service';
import { WindowDimensionsService } from 'services/contextual/window-dimensions.service';
import { WindowRef } from 'services/contextual/window-ref.service';
import { I18nLanguageCodeService } from 'services/i18n-language-code.service';
import { LoaderService } from 'services/loader.service';
import { MessengerService } from 'services/messenger.service';
import { SiteAnalyticsService } from 'services/site-analytics.service';
import { FocusManagerService } from 'services/stateful/focus-manager.service';
import { UserService } from 'services/user.service';
import { MockTranslatePipe } from 'tests/unit-test-utils';
import { ExplorationPlayerConstants } from '../exploration-player-page.constants';
import { AudioTranslationLanguageService } from '../services/audio-translation-language.service';
import { ContentTranslationLanguageService } from '../services/content-translation-language.service';
import { ContentTranslationManagerService } from '../services/content-translation-manager.service';
import { CurrentInteractionService } from '../services/current-interaction.service';
import { ExplorationEngineService } from '../services/exploration-engine.service';
import { ExplorationPlayerStateService } from '../services/exploration-player-state.service';
import { ExplorationRecommendationsService } from '../services/exploration-recommendations.service';
import { FatigueDetectionService } from '../services/fatigue-detection.service';
import { HintsAndSolutionManagerService } from '../services/hints-and-solution-manager.service';
import { ImagePreloaderService } from '../services/image-preloader.service';
import { LearnerAnswerInfoService } from '../services/learner-answer-info.service';
import { LearnerParamsService } from '../services/learner-params.service';
import { NumberAttemptsService } from '../services/number-attempts.service';
import { PlayerCorrectnessFeedbackEnabledService } from '../services/player-correctness-feedback-enabled.service';
import { PlayerPositionService } from '../services/player-position.service';
import { PlayerTranscriptService } from '../services/player-transcript.service';
import { QuestionPlayerEngineService } from '../services/question-player-engine.service';
import { RefresherExplorationConfirmationModalService } from '../services/refresher-exploration-confirmation-modal.service';
import { StatsReportingService } from '../services/stats-reporting.service';
import { ConversationSkinComponent } from './conversation-skin.component';

class MockWindowRef {
  nativeWindow = {
    location: {
      pathname: '/path/name',
      reload: () => {}
    },
    addEventListener(event: string, callback) {
      callback('');
    }
  };
}

// eslint-disable-next-line oppia/no-test-blockers
fdescribe('Conversation skin component', () => {
  let fixture: ComponentFixture<ConversationSkinComponent>;
  let componentInstance: ConversationSkinComponent;
  let alertsService: AlertsService;
  let audioPlayerService: AudioPlayerService;
  let audioTranslationLanguageService: AudioTranslationLanguageService;
  let autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService;
  let collectionPlayerBackendApiService: CollectionPlayerBackendApiService;
  let conceptCardBackendApiService: ConceptCardBackendApiService;
  let contentTranslationLanguageService: ContentTranslationLanguageService;
  let contentTranslationManagerService: ContentTranslationManagerService;
  let contextService: ContextService;
  let currentInteractionService: CurrentInteractionService;
  let explorationEngineService: ExplorationEngineService;
  let explorationPlayerStateService: ExplorationPlayerStateService;
  let explorationRecommendationsService:
  ExplorationRecommendationsBackendApiService;
  let explorationSummaryBackendApiService: ExplorationSummaryBackendApiService;
  let fatigueDetectionService: FatigueDetectionService;
  let focusManagerService: FocusManagerService;
  let guestCollectionProgressService: GuestCollectionProgressService;
  let hintsAndSolutionManagerService: HintsAndSolutionManagerService;
  let i18nLanguageCodeService: I18nLanguageCodeService;
  let imagePreloaderService: ImagePreloaderService;
  let learnerAnswerInfoService: LearnerAnswerInfoService;
  let learnerParamsService: LearnerParamsService;
  let loaderService: LoaderService;
  let messengerService: MessengerService;
  let numberAttemptsService: NumberAttemptsService;
  let playerCorrectnessFeedbackEnabledService:
  PlayerCorrectnessFeedbackEnabledService;
  let playerPositionService: PlayerPositionService;
  let playerTranscriptService: PlayerTranscriptService;
  let questionPlayerEngineService: QuestionPlayerEngineService;
  let questionPlayerStateService: QuestionPlayerStateService;
  let readOnlyCollectionBackendApiService: ReadOnlyCollectionBackendApiService;
  let refresherExplorationConfirmationModalService:
  RefresherExplorationConfirmationModalService;
  let siteAnalyticsService: SiteAnalyticsService;
  let statsReportingService: StatsReportingService;
  let storyViewerBackendApiService: StoryViewerBackendApiService;
  let urlInterpolationService: UrlInterpolationService;
  let urlService: UrlService;
  let userService: UserService;
  let windowDimensionsService: WindowDimensionsService;
  let windowRef: WindowRef;

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      declarations: [
        ConversationSkinComponent,
        MockTranslatePipe
      ],
      providers: [
        {
          provide: WindowRef,
          useClass: MockWindowRef
        }
      ],
      schemas: [NO_ERRORS_SCHEMA]
    }).compileComponents();

    fixture = TestBed.createComponent(ConversationSkinComponent);
    componentInstance = fixture.componentInstance;

    alertsService = TestBed.inject(AlertsService);
    audioPlayerService = TestBed.inject(AudioPlayerService);
    audioTranslationLanguageService = TestBed.inject(
      AudioTranslationLanguageService);
    autogeneratedAudioPlayerService = TestBed.inject(
      AutogeneratedAudioPlayerService);
    collectionPlayerBackendApiService = TestBed.inject(
      CollectionPlayerBackendApiService);
    conceptCardBackendApiService = TestBed.inject(ConceptCardBackendApiService);
    contentTranslationLanguageService = TestBed.inject(
      ContentTranslationLanguageService);
    contentTranslationManagerService = TestBed.inject(
      ContentTranslationManagerService);
    contextService = TestBed.inject(ContextService);
    currentInteractionService = TestBed.inject(CurrentInteractionService);
    explorationEngineService = TestBed.inject(ExplorationEngineService);
    explorationPlayerStateService = TestBed.inject(
      ExplorationPlayerStateService);
    explorationRecommendationsService = TestBed.inject(
      ExplorationRecommendationsService);
    explorationSummaryBackendApiService = TestBed.inject(
      ExplorationSummaryBackendApiService);
    fatigueDetectionService = TestBed.inject(FatigueDetectionService);
    focusManagerService = TestBed.inject(FocusManagerService);
    guestCollectionProgressService = TestBed.inject(
      GuestCollectionProgressService);
    hintsAndSolutionManagerService = TestBed.inject(
      HintsAndSolutionManagerService);
    i18nLanguageCodeService = TestBed.inject(I18nLanguageCodeService);
    imagePreloaderService = TestBed.inject(ImagePreloaderService);
    learnerAnswerInfoService = TestBed.inject(LearnerAnswerInfoService);
    learnerParamsService = TestBed.inject(LearnerParamsService);
    loaderService = TestBed.inject(LoaderService);
    messengerService = TestBed.inject(MessengerService);
    numberAttemptsService = TestBed.inject(NumberAttemptsService);
    playerCorrectnessFeedbackEnabledService = TestBed.inject(
      PlayerCorrectnessFeedbackEnabledService);
    playerPositionService = TestBed.inject(PlayerPositionService);
    playerTranscriptService = TestBed.inject(PlayerTranscriptService);
    questionPlayerEngineService = TestBed.inject(QuestionPlayerEngineService);
    questionPlayerStateService = TestBed.inject(QuestionPlayerStateService);
    readOnlyCollectionBackendApiService = TestBed.inject(
      ReadOnlyCollectionBackendApiService);
    refresherExplorationConfirmationModalService = TestBed.inject(
      RefresherExplorationConfirmationModalService);
    siteAnalyticsService = TestBed.inject(SiteAnalyticsService);
    statsReportingService = TestBed.inject(StatsReportingService);
    storyViewerBackendApiService = TestBed.inject(StoryViewerBackendApiService);
    urlInterpolationService = TestBed.inject(UrlInterpolationService);
    urlService = TestBed.inject(UrlService);
    userService = TestBed.inject(UserService);
    windowDimensionsService = TestBed.inject(WindowDimensionsService);
    windowRef = TestBed.inject(WindowRef);
  }));

  it('should create', () => {
    expect(componentInstance).toBeDefined();
  });

  it('should initialize component', fakeAsync(() => {
    let collectionId = 'id';
    let expId = 'exp_id';
    let isInPreviewMode = false;
    let isIframed = true;
    let collectionSummary = {
      is_admin: true,
      summaries: [],
      user_email: '',
      is_topic_manager: false,
      username: true
    };
    spyOn(contextService, 'isInExplorationEditorPage');
    spyOn(userService, 'getUserInfoAsync').and.returnValue(
      Promise.resolve(new UserInfo(
        [], false, false,
        false, false, false, '', '', '', true)));
    spyOn(urlService, 'getCollectionIdFromExplorationUrl')
      .and.returnValue(collectionId);

    spyOn(readOnlyCollectionBackendApiService, 'loadCollectionAsync')
      .and.returnValue(Promise.resolve(new Collection(
        '', '', '', '', [], null, '', 6, 8, [])));
    spyOn(explorationEngineService, 'getExplorationId').and.returnValue(expId);
    spyOn(explorationEngineService, 'isInPreviewMode')
      .and.returnValue(isInPreviewMode);
    spyOn(urlService, 'isIframed').and.returnValue(isIframed);
    spyOn(loaderService, 'showLoadingScreen');
    spyOn(urlInterpolationService, 'getStaticImageUrl')
      .and.returnValue('oppia_avatar_url');
    spyOn(explorationPlayerStateService, 'isInQuestionPlayerMode')
      .and.returnValue(true);
    spyOn(componentInstance, 'initializePage');
    spyOn(collectionPlayerBackendApiService, 'fetchCollectionSummariesAsync')
      .and.returnValue(Promise.resolve(collectionSummary));
    spyOn(questionPlayerStateService, 'hintUsed');
    spyOn(questionPlayerEngineService, 'getCurrentQuestion');
    spyOn(questionPlayerStateService, 'solutionViewed');

    let mockOnHintConsumed = new EventEmitter();
    let mockOnSolutionViewedEventEmitter = new EventEmitter();
    let mockOnPlayerStateChange = new EventEmitter();

    componentInstance.ngOnInit();

    spyOnProperty(hintsAndSolutionManagerService, 'onHintConsumed')
      .and.returnValue(mockOnHintConsumed);
    spyOnProperty(
      hintsAndSolutionManagerService, 'onSolutionViewedEventEmitter')
      .and.returnValue(mockOnSolutionViewedEventEmitter);
    spyOnProperty(explorationPlayerStateService, 'onPlayerStateChange')
      .and.returnValue(mockOnPlayerStateChange);

    mockOnHintConsumed.emit();
    mockOnSolutionViewedEventEmitter.emit();
    mockOnPlayerStateChange.emit();
    tick();
    tick();
    tick();
    tick();
    tick();
    tick();
    tick();
  }));

  it('should tell if submit button is disabled', () => {
    let displayedCardIndex = 1;
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(
      displayedCardIndex);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValues(true, false);
    spyOn(currentInteractionService, 'isSubmitButtonDisabled').and.returnValue(
      true);

    expect(componentInstance.isSubmitButtonDisabled()).toBeTrue();
    expect(componentInstance.isSubmitButtonDisabled()).toBeFalse();
  });

  it('should change card', () => {
    spyOn(playerPositionService, 'recordNavigationButtonClick');
    spyOn(playerPositionService, 'setDisplayedCardIndex');
    spyOn(explorationEngineService.onUpdateActiveStateIfInEditor, 'emit');
    spyOn(playerPositionService, 'getCurrentStateName').and.returnValue(
      'state_name');
    spyOn(playerPositionService, 'changeCurrentQuestion');

    componentInstance.changeCard(1);

    expect(playerPositionService.recordNavigationButtonClick)
      .toHaveBeenCalled();
    expect(playerPositionService.setDisplayedCardIndex).toHaveBeenCalled();
    expect(explorationEngineService.onUpdateActiveStateIfInEditor.emit)
      .toHaveBeenCalled();
    expect(playerPositionService.getCurrentStateName).toHaveBeenCalled();
    expect(playerPositionService.changeCurrentQuestion).toHaveBeenCalled();
  });

  it('should unsubscribe on destroy', () => {
    spyOn(componentInstance.directiveSubscriptions, 'unsubscribe');

    componentInstance.ngOnDestroy();

    expect(componentInstance.directiveSubscriptions.unsubscribe)
      .toHaveBeenCalled();
  });

  it('should always ask learner for answer details', () => {
    spyOn(explorationEngineService, 'getAlwaysAskLearnerForAnswerDetails')
      .and.returnValues(true, false);

    expect(componentInstance.alwaysAskLearnerForAnswerDetails()).toBeTrue();
    expect(componentInstance.alwaysAskLearnerForAnswerDetails()).toBeFalse();
  });

  it('should get can ask learner for answer info', () => {
    spyOn(learnerAnswerInfoService, 'getCanAskLearnerForAnswerInfo')
      .and.returnValues(true, false);

    expect(componentInstance.getCanAskLearnerForAnswerInfo()).toBeTrue();
    expect(componentInstance.getCanAskLearnerForAnswerInfo()).toBeFalse();
  });

  it('should initialize learner answer info service', () => {
    spyOn(learnerAnswerInfoService, 'initLearnerAnswerInfoService');

    componentInstance.initLearnerAnswerInfoService(
      null, null, null, null, false);

    expect(learnerAnswerInfoService.initLearnerAnswerInfoService)
      .toHaveBeenCalled();
  });

  it('should tell if correctness feedback is enabled', () => {
    spyOn(playerCorrectnessFeedbackEnabledService, 'isEnabled');

    componentInstance.isCorrectnessFeedbackEnabled();

    expect(playerCorrectnessFeedbackEnabledService.isEnabled)
      .toHaveBeenCalled();
  });

  it('should tell if correctness footer is enabled', () => {
    componentInstance.answerIsCorrect = true;

    spyOn(componentInstance, 'isCorrectnessFeedbackEnabled').and.returnValue(
      true);
    spyOn(playerPositionService, 'hasLearnerJustSubmittedAnAnswer')
      .and.returnValue(true);

    expect(componentInstance.isCorrectnessFooterEnabled()).toBeTrue();
  });

  it('should tell if learn again button should be visible', () => {
    //
  });

  it('should get static image url', () => {
    let imageUrl = 'image_url';
    spyOn(urlInterpolationService, 'getStaticImageUrl').and.returnValue(
      imageUrl);

    expect(componentInstance.getStaticImageUrl('')).toEqual(imageUrl);
  });

  it('should get content focus label', () => {
    let index = 1;

    expect(componentInstance.getContentFocusLabel(index)).toEqual(
      ExplorationPlayerConstants.CONTENT_FOCUS_LABEL_PREFIX + index);
  });

  it('should tell if language is RTL', () => {
    spyOn(i18nLanguageCodeService, 'isCurrentLanguageRTL')
      .and.returnValue(true);

    expect(componentInstance.isLanguageRTL()).toBeTrue();
  });

  it('should reload exploration', () => {
    spyOn(windowRef.nativeWindow.location, 'reload');

    componentInstance.reloadExploration();

    expect(windowRef.nativeWindow.location.reload).toHaveBeenCalled();
  });

  it('should tell if display card is terminal', () => {
    componentInstance.displayedCard = new StateCard(
      null, null, null, new Interaction(
        [], [], null, null, [], 'EndExploration', null),
      [], null, null, '', null);

    expect(componentInstance.isOnTerminalCard()).toBeTrue();
  });

  it('should tell if supplemental card is non empty', () => {
    let stateCard = new StateCard(
      null, null, null, new Interaction(
        [], [], null, null, [], '', null),
      [], null, null, '', null);
    expect(componentInstance.isSupplementalCardNonempty(stateCard)).toBeFalse();
  });

  it('should return to exploration after concept card is compeleted', () => {
    let numCards = 20;
    spyOn(playerTranscriptService, 'addPreviousCard');
    spyOn(playerTranscriptService, 'getNumCards').and.returnValue(numCards);
    spyOn(playerPositionService, 'setDisplayedCardIndex');

    componentInstance.returnToExplorationAfterConceptCard();

    expect(playerTranscriptService.addPreviousCard).toHaveBeenCalled();
    expect(playerTranscriptService.getNumCards).toHaveBeenCalled();
    expect(playerPositionService.setDisplayedCardIndex)
      .toHaveBeenCalledOnceWith(numCards - 1);
  });

  it('should tell if current is at end of transcript', () => {
    let index = 1;
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(true);
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(
      index);

    expect(componentInstance.isCurrentCardAtEndOfTranscript()).toBeTrue();
    expect(playerTranscriptService.isLastCard).toHaveBeenCalledWith(index);
  });

  it('should hide loading screen if question are not available', () => {
    spyOn(loaderService, 'hideLoadingScreen');

    componentInstance.showQuestionAreNotAvailable();

    expect(loaderService.hideLoadingScreen).toHaveBeenCalled();
  });

  it('should initialize page', () => {
    spyOn(playerPositionService, 'init');
    componentInstance.questionPlayerConfig = {};
    spyOn(explorationPlayerStateService, 'initializeQuestionPlayer');

    componentInstance.initializePage();
    expect(componentInstance.hasInteractedAtLeastOnce).toBeFalse();
    expect(componentInstance.recommendedExplorationSummaries).toEqual([]);
    expect(playerPositionService.init).toHaveBeenCalled();

    componentInstance.questionPlayerConfig = null;
    spyOn(explorationPlayerStateService, 'initializePlayer');

    componentInstance.initializePage();

    expect(explorationPlayerStateService.initializePlayer).toHaveBeenCalled();
  });

  it('should tell if window can show two cards', () => {
    spyOn(windowDimensionsService, 'getWidth').and.returnValue(
      ExplorationPlayerConstants.TWO_CARD_THRESHOLD_PX + 1);

    expect(componentInstance.canWindowShowTwoCards()).toBeTrue();
  });

  it('should register analytics when user visit using iframe', () => {
    spyOn(siteAnalyticsService, 'registerVisitOppiaFromIframeEvent');

    componentInstance.onNavigateFromIframe();

    expect(siteAnalyticsService.registerVisitOppiaFromIframeEvent)
      .toHaveBeenCalled();
  });

  it('should submit answer from progress nav', () => {
    spyOn(currentInteractionService, 'submitAnswer');

    componentInstance.submitAnswerFromProgressNav();

    expect(currentInteractionService.submitAnswer).toHaveBeenCalled();
  });
});
