// Copyright 2021 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Component for display solution modal.
 */

import {Component, OnDestroy} from '@angular/core';
import {NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';
import {Interaction} from 'domain/exploration/InteractionObjectFactory';
import {RecordedVoiceovers} from 'domain/exploration/recorded-voiceovers.model';
import {
  ShortAnswerResponse,
  Solution,
} from 'domain/exploration/SolutionObjectFactory';
import {StateCard} from 'domain/state_card/state-card.model';
import {AudioPlayerService} from 'services/audio-player.service';
import {AutogeneratedAudioPlayerService} from 'services/autogenerated-audio-player.service';
import {HintsAndSolutionManagerService} from '../services/hints-and-solution-manager.service';
import {PlayerPositionService} from '../services/player-position.service';
import {PlayerTranscriptService} from '../services/player-transcript.service';
import {VoiceoverPlayerService} from '../services/voiceover-player.service';
import {AudioBarStatusService} from 'services/audio-bar-status.service';
import {AppConstants} from 'app.constants';
import {Subscription} from 'rxjs';

@Component({
  selector: 'oppia-display-modal',
  templateUrl: './display-solution-modal.component.html',
})
export class DisplaySolutionModalComponent implements OnDestroy {
  // These properties are initialized using Angular lifecycle hooks
  // and we need to do non-null assertion. For more information, see
  // https://github.com/oppia/oppia/wiki/Guide-on-defining-types#ts-7-1.
  COMPONENT_NAME_SOLUTION!: string;
  solution!: Solution;
  solutionContentId!: string;
  displayedCard!: StateCard;
  recordedVoiceovers!: RecordedVoiceovers;
  interaction!: Interaction;
  shortAnswerHtml!: ShortAnswerResponse;
  solutionExplanationHtml!: string;
  isPlaying: boolean = false;
  hasVoiceover: boolean = false;
  private directiveSubscriptions = new Subscription();

  constructor(
    private ngbActiveModal: NgbActiveModal,
    private audioPlayerService: AudioPlayerService,
    private autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService,
    private hintsAndSolutionManagerService: HintsAndSolutionManagerService,
    private playerPositionService: PlayerPositionService,
    private playerTranscriptService: PlayerTranscriptService,
    private voiceoverPlayerService: VoiceoverPlayerService,
    private audioBarStatusService: AudioBarStatusService
  ) {}

  ngOnInit(): void {
    let solution = this.hintsAndSolutionManagerService.displaySolution();
    if (solution === null) {
      throw new Error('Solution not found.');
    }
    this.solution = solution;
    this.displayedCard = this.playerTranscriptService.getCard(
      this.playerPositionService.getDisplayedCardIndex()
    );
    let contentId = this.solution.explanation.contentId;
    if (contentId === null) {
      throw new Error('Content id not found.');
    }
    this.solutionContentId = contentId;

    this.interaction = this.displayedCard.getInteraction();
    this.shortAnswerHtml = this.solution.getOppiaShortAnswerResponseHtml(
      this.interaction
    );
    this.solutionExplanationHtml =
      this.solution.getOppiaSolutionExplanationResponseHtml();

    // Check if voiceover exists for this solution.
    this.voiceoverPlayerService.setActiveVoiceover(this.solutionContentId);
    this.voiceoverPlayerService.setActiveComponentName(
      AppConstants.COMPONENT_NAME_SOLUTION
    );
    this.hasVoiceover =
      this.voiceoverPlayerService.getActiveVoiceover() !== undefined;

    this.audioPlayerService.onAutoplayAudio.emit();

    // Subscribe to audio player events.
    this.directiveSubscriptions.add(
      this.audioPlayerService.onAudioStop.subscribe(() => {
        this.isPlaying = false;
      })
    );

    // Subscribe to audio end event.
    this.directiveSubscriptions.add(
      this.audioPlayerService.onAudioEnd.subscribe(() => {
        this.isPlaying = false;
      })
    );
  }

  ngOnDestroy(): void {
    this.directiveSubscriptions.unsubscribe();
  }

  isAudioBarExpanded(): boolean {
    return this.audioBarStatusService.isAudioBarExpanded();
  }

  playVoiceover(): void {
    if (this.isPlaying) {
      // Stop and clear the audio.
      this.audioPlayerService.stop();
      this.audioPlayerService.clear();
      this.isPlaying = false;
    } else {
      if (this.hasVoiceover) {
        // Always load and play from the beginning.
        const voiceover = this.voiceoverPlayerService.getActiveVoiceover();
        if (voiceover) {
          // First stop and clear any existing audio.
          this.audioPlayerService.stop();
          this.audioPlayerService.clear();

          // Then load and play the audio.
          this.audioPlayerService.loadAsync(voiceover.filename).then(() => {
            // Set the current time to 0 before playing.
            this.audioPlayerService.setCurrentTime(0);
            this.audioPlayerService.play();
            this.isPlaying = true;
          });
        }
      }
    }
  }

  closeModal(): void {
    this.audioPlayerService.stop();
    this.autogeneratedAudioPlayerService.cancel();
    this.ngbActiveModal.dismiss('cancel');
  }
}
