name: 'Install Chrome'
description: 'Installs Chrome for use in tests'

runs:
  using: 'composite'
  steps:
    - id: install-chrome
      name: Install Chrome
      env:
        CHROME_VERSION: "102.0.5005.61-1"
      run: |
        sudo apt-get update
        sudo apt-get install libappindicator3-1
        curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/${CHROME_VERSION}/google-chrome-stable_${CHROME_VERSION}_amd64.deb'
        sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
        sudo dpkg -i google-chrome.deb
        # get version and assert if it's the same as the one we want to install
        [ "$(google-chrome --version 2>&1 | awk '{print $3}')" == "${CHROME_VERSION}" ] || { echo "Error: Chrome version does not match the desired version."; exit 1; }
      shell: bash
