name: 'Install Chrome'
description: 'Installs Chrome for use in tests'

runs:
  using: 'composite'
  steps:
    - id: install-chrome
      name: Install Chrome (retries on error)
      uses: nick-fields/retry@v3
      env:
        CHROME_VERSION: "145.0.7632.76"
        PLATFORM: "linux64"
      with:
        max_attempts: 3
        retry_on: error
        shell: bash
        timeout_minutes: 10
        command: |
          # Download Chrome for Testing
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${{ env.CHROME_VERSION }}/${{ env.PLATFORM }}/chrome-${{ env.PLATFORM }}.zip"
          unzip -q chrome-${{ env.PLATFORM }}.zip

          # Install Chrome
          sudo mkdir -p /opt/google/chrome
          sudo mv chrome-${{ env.PLATFORM }}/* /opt/google/chrome/
          sudo chmod +x /opt/google/chrome/chrome

          sudo mv /opt/google/chrome/chrome /opt/google/chrome/chrome-real
          printf '#!/bin/bash\nexec /opt/google/chrome/chrome-real --no-sandbox --disable-dev-shm-usage --disable-setuid-sandbox "$@"\n' | sudo tee /opt/google/chrome/chrome > /dev/null
          sudo chmod +x /opt/google/chrome/chrome

          printf '#!/bin/bash\nexec /opt/google/chrome/chrome-real --no-sandbox --disable-dev-shm-usage --disable-setuid-sandbox "$@"\n' | sudo tee /usr/bin/google-chrome > /dev/null
          sudo chmod +x /usr/bin/google-chrome

          # Download ChromeDriver
          wget -q "https://storage.googleapis.com/chrome-for-testing-public/${{ env.CHROME_VERSION }}/${{ env.PLATFORM }}/chromedriver-${{ env.PLATFORM }}.zip"
          unzip -q chromedriver-${{ env.PLATFORM }}.zip

          # Install ChromeDriver
          sudo mv chromedriver-${{ env.PLATFORM }}/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

          echo "CHROME_PATH=/opt/google/chrome/chrome" >> $GITHUB_ENV

          chrome_version=$(google-chrome --version 2>&1 | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Installed Chrome version: $chrome_version"
          [[ "${{ env.CHROME_VERSION }}" == "$chrome_version" ]] || { echo "Error: Version mismatch. Expected ${{ env.CHROME_VERSION }}, got $chrome_version"; exit 1; }
