// Copyright 2024 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Unit tests for conversation flow service.
 */

import {HttpClientTestingModule} from '@angular/common/http/testing';
import {NO_ERRORS_SCHEMA} from '@angular/core';
import {
  fakeAsync,
  TestBed,
  tick,
  waitForAsync,
  flushMicrotasks,
} from '@angular/core/testing';

import {ConversationFlowService} from './conversation-flow.service';
import {StateCard} from '../../../domain/state_card/state-card.model';
import {PlayerTranscriptService} from './player-transcript.service';
import {TranslateService} from '@ngx-translate/core';
import {MockTranslateService} from '../../../components/forms/schema-based-editors/integration-tests/schema-based-editors.integration.spec';
import {Interaction} from '../../../domain/exploration/InteractionObjectFactory';
import {ExplorationModeService} from './exploration-mode.service';
import {ExplorationEngineService} from './exploration-engine.service';
import {PageContextService} from '../../../services/page-context.service';
import {PlayerPositionService} from './player-position.service';
import {HintsAndSolutionManagerService} from './hints-and-solution-manager.service';
import {ProgressUrlService} from './progress-url.service';
import {Solution} from '../../../domain/exploration/SolutionObjectFactory';
import {ExplorationPlayerConstants} from '../current-lesson-player/exploration-player-page.constants';
import {CheckpointProgressService} from './checkpoint-progress.service';
import {EditableExplorationBackendApiService} from '../../../domain/exploration/editable-exploration-backend-api.service';
import {ReadOnlyExplorationBackendApiService} from '../../../domain/exploration/read-only-exploration-backend-api.service';
import {UrlService} from '../../../services/contextual/url.service';
import {AudioPlayerService} from '../../../services/audio-player.service';
import {AutogeneratedAudioPlayerService} from '../../../services/autogenerated-audio-player.service';
import {FocusManagerService} from '../../../services/stateful/focus-manager.service';
import {LoaderService} from '../../../services/loader.service';
import {I18nLanguageCodeService} from '../../../services/i18n-language-code.service';
import {WindowRef} from '../../../services/contextual/window-ref.service';
import {CardAnimationService} from './card-animation.service';
import {CurrentEngineService} from './current-engine.service';

describe('Conversation flow service', () => {
  let conversationFlowService: ConversationFlowService;
  let currentEngineService: CurrentEngineService;
  let hintsAndSolutionManagerService: HintsAndSolutionManagerService;
  let urlService: UrlService;
  let loaderService: LoaderService;
  let i18nLanguageCodeService: I18nLanguageCodeService;
  let cardAnimationService: CardAnimationService;
  let windowRef: WindowRef;
  let focusManagerService: FocusManagerService;
  let audioPlayerService: AudioPlayerService;
  let autogeneratedAudioPlayerService: AutogeneratedAudioPlayerService;
  let checkpointProgressService: CheckpointProgressService;
  let editableExplorationBackendApiService: EditableExplorationBackendApiService;
  let readOnlyExplorationBackendApiService: ReadOnlyExplorationBackendApiService;
  let playerTranscriptService: PlayerTranscriptService;
  let progressUrlService: ProgressUrlService;
  let explorationModeService: ExplorationModeService;
  let pageContextService: PageContextService;
  let playerPositionService: PlayerPositionService;
  let explorationEngineService: ExplorationEngineService;

  let createCard = function (interactionType: string): StateCard {
    return new StateCard(
      null,
      null,
      null,
      new Interaction([], [], null, null, [], interactionType, null),
      [],
      null,
      '',
      null
    );
  };
  let displayedCard = createCard('');

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientTestingModule],
      providers: [
        ConversationFlowService,
        {
          provide: TranslateService,
          useClass: MockTranslateService,
        },
      ],
      schemas: [NO_ERRORS_SCHEMA],
    });

    currentEngineService = TestBed.inject(CurrentEngineService);
    conversationFlowService = TestBed.inject(ConversationFlowService);
    playerTranscriptService = TestBed.inject(PlayerTranscriptService);
    pageContextService = TestBed.inject(PageContextService);
    progressUrlService = TestBed.inject(ProgressUrlService);
    hintsAndSolutionManagerService = TestBed.inject(
      HintsAndSolutionManagerService
    );
    loaderService = TestBed.inject(LoaderService);
    i18nLanguageCodeService = TestBed.inject(I18nLanguageCodeService);
    cardAnimationService = TestBed.inject(CardAnimationService);
    windowRef = TestBed.inject(WindowRef);
    editableExplorationBackendApiService = TestBed.inject(
      EditableExplorationBackendApiService
    );
    readOnlyExplorationBackendApiService = TestBed.inject(
      ReadOnlyExplorationBackendApiService
    );
    urlService = TestBed.inject(UrlService);
    audioPlayerService = TestBed.inject(AudioPlayerService);
    autogeneratedAudioPlayerService = TestBed.inject(
      AutogeneratedAudioPlayerService
    );
    checkpointProgressService = TestBed.inject(CheckpointProgressService);
    focusManagerService = TestBed.inject(FocusManagerService);
    editableExplorationBackendApiService = TestBed.inject(
      EditableExplorationBackendApiService
    );
    readOnlyExplorationBackendApiService = TestBed.inject(
      ReadOnlyExplorationBackendApiService
    );
    playerPositionService = TestBed.inject(PlayerPositionService);
    hintsAndSolutionManagerService = TestBed.inject(
      HintsAndSolutionManagerService
    );

    explorationModeService = TestBed.inject(ExplorationModeService);
    explorationEngineService = TestBed.inject(ExplorationEngineService);
    conversationFlowService = TestBed.inject(ConversationFlowService);
    playerTranscriptService = TestBed.inject(PlayerTranscriptService);

    spyOn(pageContextService, 'getExplorationId').and.returnValue('expId');
  }));

  it('should tell if supplemental card is non empty', () => {
    expect(
      conversationFlowService.isSupplementalCardNonempty(displayedCard)
    ).toBeFalse();

    let textInputCard = createCard('TextInput');
    expect(
      conversationFlowService.isSupplementalCardNonempty(textInputCard)
    ).toBeFalse();

    let supplementaryImageInputCard = createCard('ImageClickInput');
    expect(
      conversationFlowService.isSupplementalCardNonempty(
        supplementaryImageInputCard
      )
    ).toBeTrue();
  });

  it('should test getters', () => {
    expect(conversationFlowService.onPlayerStateChange).toBeDefined();
    expect(conversationFlowService.onOppiaFeedbackAvailable).toBeDefined();
    expect(conversationFlowService.onShowProgressModal).toBeDefined();
  });

  it('should record leaving for refresher exploration if not in editor', () => {
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(playerPositionService, 'getCurrentStateName').and.returnValue(
      'StateName'
    );
  });

  it('should move forward by one card when index is valid', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(2);
    spyOn(playerPositionService, 'setDisplayedCardIndex').and.callFake(
      () => {}
    );
    spyOn(playerPositionService, 'getCurrentStateName').and.returnValue(
      'StateName'
    );
    spyOn(playerTranscriptService, 'getNumCards').and.returnValue(5);
    conversationFlowService.moveForwardByOneCard();

    expect(playerPositionService.getDisplayedCardIndex).toHaveBeenCalled();
  });

  it('should set and get hasInteractedAtLeastOnce correctly', () => {
    conversationFlowService.setHasInteractedAtLeastOnce(true);
    // Since there is no getter, we can indirectly check expected behavior,
    // but here we just test the method does not throw.
    expect().nothing();

    conversationFlowService.setHasInteractedAtLeastOnce(false);
    expect().nothing();
  });

  it('should set and get explorationActuallyStarted correctly', () => {
    conversationFlowService.setExplorationActuallyStarted(true);
    expect(conversationFlowService.getExplorationActuallyStarted()).toBeTrue();

    conversationFlowService.setExplorationActuallyStarted(false);
    expect(conversationFlowService.getExplorationActuallyStarted()).toBeFalse();
  });

  it('should set and get showProgressClearanceMessage correctly', () => {
    conversationFlowService.setShowProgressClearanceMessage(true);
    expect(
      conversationFlowService.getShowProgressClearanceMessage()
    ).toBeTrue();

    conversationFlowService.setShowProgressClearanceMessage(false);
    expect(
      conversationFlowService.getShowProgressClearanceMessage()
    ).toBeFalse();
  });

  it('should set and get answerIsCorrect correctly', () => {
    conversationFlowService.setAnswerIsCorrect(true);
    expect(conversationFlowService.getAnswerIsCorrect()).toBeTrue();

    conversationFlowService.setAnswerIsCorrect(false);
    expect(conversationFlowService.getAnswerIsCorrect()).toBeFalse();
  });

  it('should set and get answerIsBeingProcessed correctly', () => {
    conversationFlowService.setAnswerIsBeingProcessed(true);
    expect(conversationFlowService.getAnswerIsBeingProcessed()).toBeTrue();

    conversationFlowService.setAnswerIsBeingProcessed(false);
    expect(conversationFlowService.getAnswerIsBeingProcessed()).toBeFalse();
  });

  it('should set and get hasInteractedAtLeastOnce correctly', () => {
    conversationFlowService.setHasInteractedAtLeastOnce(true);
    expect(conversationFlowService.getHasInteractedAtLeastOnce()).toBeTrue();

    conversationFlowService.setHasInteractedAtLeastOnce(false);
    expect(conversationFlowService.getHasInteractedAtLeastOnce()).toBeFalse();
  });

  it('should set and get hasFullyLoaded correctly', () => {
    conversationFlowService.setHasFullyLoaded(true);
    expect(conversationFlowService.getHasFullyLoaded()).toBeTrue();

    conversationFlowService.setHasFullyLoaded(false);
    expect(conversationFlowService.getHasFullyLoaded()).toBeFalse();
  });

  it('should set and get answerIsCorrect correctly', () => {
    conversationFlowService.setAnswerIsCorrect(true);
    expect(conversationFlowService.getAnswerIsCorrect()).toBeTrue();

    conversationFlowService.setAnswerIsCorrect(false);
    expect(conversationFlowService.getAnswerIsCorrect()).toBeFalse();
  });

  it('should set and get answerIsBeingProcessed correctly', () => {
    conversationFlowService.setAnswerIsBeingProcessed(true);
    expect(conversationFlowService.getAnswerIsBeingProcessed()).toBeTrue();

    conversationFlowService.setAnswerIsBeingProcessed(false);
    expect(conversationFlowService.getAnswerIsBeingProcessed()).toBeFalse();
  });

  it('should set and get hasInteractedAtLeastOnce correctly', () => {
    conversationFlowService.setHasInteractedAtLeastOnce(true);
    expect(conversationFlowService.getHasInteractedAtLeastOnce()).toBeTrue();

    conversationFlowService.setHasInteractedAtLeastOnce(false);
    expect(conversationFlowService.getHasInteractedAtLeastOnce()).toBeFalse();
  });

  it('should move backward by one card when index is valid', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(2);
    spyOn(playerPositionService, 'setDisplayedCardIndex').and.callFake(
      () => {}
    );
    spyOn(playerPositionService, 'getCurrentStateName').and.returnValue(
      'StateName'
    );
    spyOn(playerTranscriptService, 'getNumCards').and.returnValue(5);
    conversationFlowService.moveBackByOneCard();

    expect(playerPositionService.getDisplayedCardIndex).toHaveBeenCalled();
  });

  it('should skip checkpoint logic if index ≤ 0', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(0);
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
    expect(audioPlayerService.onAutoplayAudio.emit).toHaveBeenCalled();
    expect(autogeneratedAudioPlayerService.cancel).toHaveBeenCalled();
    expect(focusManagerService.setFocusIfOnDesktop).toHaveBeenCalled();
  });

  it('should skip when isIframed is true', () => {
    spyOn(urlService, 'isIframed').and.returnValue(true);
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
    expect(audioPlayerService.onAutoplayAudio.emit).toHaveBeenCalled();
    expect(autogeneratedAudioPlayerService.cancel).toHaveBeenCalled();
    expect(focusManagerService.setFocusIfOnDesktop).toHaveBeenCalled();
  });

  it('should skip when editor preview mode is true', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      true
    );
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
  });

  it('should skip when in question player mode', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      true
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
  });

  it('should skip when in diagnostic test player mode', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(true);
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
  });

  it('should return false when concept card is shown', () => {
    const conceptCard = new StateCard(
      null,
      null,
      null,
      new Interaction([], [], null, null, [], null, null),
      [],
      '',
      null
    );

    conversationFlowService.displayedCard = conceptCard;
    spyOn(explorationModeService, 'isInQuestionMode').and.returnValue(false);

    const result = conversationFlowService.isLearnAgainButton();
    expect(result).toBeFalse();
  });

  it('should return false when interaction id is missing', () => {
    const card = new StateCard(
      'State1',
      null,
      null,
      new Interaction([], [], null, null, [], null, null),
      [],
      '',
      null
    );

    conversationFlowService.displayedCard = card;

    const result = conversationFlowService.isLearnAgainButton();
    expect(result).toBeFalse();
  });

  it('should return false when interaction is linear', () => {
    const card = new StateCard(
      'State1',
      null,
      null,
      new Interaction([], [], null, null, [], 'Continue', null),
      [],
      '',
      null
    );

    conversationFlowService.displayedCard = card;

    const result = conversationFlowService.isLearnAgainButton();
    expect(result).toBeFalse();
  });

  it('should return true when all conditions met', () => {
    const card = new StateCard(
      'State1',
      null,
      null,
      new Interaction([], [], null, null, [], 'TextInput', null),
      [],
      '',
      null
    );

    conversationFlowService.displayedCard = card;
    conversationFlowService.pendingCardWasSeenBefore = true;
    spyOn(conversationFlowService, 'getAnswerIsCorrect').and.returnValue(false);

    const result = conversationFlowService.isLearnAgainButton();
    expect(result).toBeTrue();
  });

  it('should return false when answer is correct even if card seen before', () => {
    const card = new StateCard(
      'State1',
      null,
      null,
      new Interaction([], [], null, null, [], 'TextInput', null),
      [],
      '',
      null
    );

    conversationFlowService.displayedCard = card;
    conversationFlowService.pendingCardWasSeenBefore = true;
    spyOn(conversationFlowService, 'getAnswerIsCorrect').and.returnValue(true);

    const result = conversationFlowService.isLearnAgainButton();
    expect(result).toBeFalse();
  });

  it('should skip checkpoint logic when card is not checkpoint', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(explorationEngineService, 'getState').and.returnValue({
      name: 'State1',
      cardIsCheckpoint: false,
    });
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(null);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();

    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
  });

  it('should record checkpoint when card is checkpoint and not yet visited', fakeAsync(() => {
    const currentStateName = 'State1';
    const version = 1;

    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(explorationEngineService, 'getState').and.returnValue({
      name: currentStateName,
      cardIsCheckpoint: true,
    });
    spyOn(
      checkpointProgressService,
      'checkIfCheckpointIsVisited'
    ).and.returnValue(false);
    spyOn(
      playerTranscriptService,
      'getPrevSessionStatesProgress'
    ).and.returnValue([]);
    spyOn(progressUrlService, 'getUniqueProgressUrlId').and.returnValue(
      'uuid-123'
    );

    spyOn(
      readOnlyExplorationBackendApiService,
      'loadLatestExplorationAsync'
    ).and.returnValue(Promise.resolve({version}));

    const recordSpy = spyOn(
      editableExplorationBackendApiService,
      'recordMostRecentlyReachedCheckpointAsync'
    ).and.stub();

    conversationFlowService.navigateToDisplayedCard();
    flushMicrotasks();
    tick();

    expect(recordSpy).toHaveBeenCalledWith(
      'expId',
      version,
      currentStateName,
      conversationFlowService.isLoggedIn,
      'uuid-123'
    );
  }));

  it('should focus next focus label when last card', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(true);
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(
      'next-focus'
    );
    spyOn(explorationEngineService, 'getState').and.returnValue({
      name: 'State1',
      cardIsCheckpoint: false,
    });
    spyOn(playerTranscriptService, 'getLastStateName').and.returnValue(
      'State1'
    );
    const focusSpy = spyOn(
      focusManagerService,
      'setFocusIfOnDesktop'
    ).and.stub();

    conversationFlowService.navigateToDisplayedCard();

    expect(focusSpy).toHaveBeenCalledWith('next-focus');
  });

  it('should initialize directive components and set focus, scroll and emit', fakeAsync(() => {
    const card = createCard('TextInput');
    spyOn(playerPositionService, 'setDisplayedCardIndex').and.callFake(
      () => {}
    );
    spyOn(playerPositionService.onNewCardOpened, 'emit').and.callFake(() => {});
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(currentEngineService, 'getCurrentEngineService').and.returnValue(
      explorationEngineService
    );
    spyOn(explorationEngineService, 'getLanguageCode').and.returnValue('en');
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(focusManagerService, 'setFocusIfOnDesktop').and.callFake(() => {});
    spyOn(loaderService, 'hideLoadingScreen').and.callFake(() => {});
    spyOn(i18nLanguageCodeService, 'setI18nLanguageCode').and.callFake(
      () => {}
    );
    spyOn(cardAnimationService, 'adjustPageHeight').and.callFake(() => {});
    spyOn(windowRef.nativeWindow, 'scrollTo').and.callFake(() => {});

    conversationFlowService.initializeDirectiveComponents(card, 'focus-label');

    tick();
    expect(focusManagerService.setFocusIfOnDesktop).toHaveBeenCalledWith(
      'focus-label'
    );
  }));

  it('should throw when currentState.name is null', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(explorationEngineService, 'getState').and.returnValue({
      name: null,
      cardIsCheckpoint: true,
    });
    spyOn(
      playerTranscriptService,
      'getPrevSessionStatesProgress'
    ).and.returnValue([]);

    expect(() => {
      conversationFlowService.navigateToDisplayedCard();
    }).toThrowError(
      'Current state name cannot be null when navigating to displayed card.'
    );
  });

  it('should do full happy path with APIs and emit', fakeAsync(() => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(1);
    spyOn(urlService, 'isIframed').and.returnValue(false);
    spyOn(pageContextService, 'isInExplorationEditorPage').and.returnValue(
      false
    );
    spyOn(explorationModeService, 'isInQuestionPlayerMode').and.returnValue(
      false
    );
    spyOn(
      explorationModeService,
      'isInDiagnosticTestPlayerMode'
    ).and.returnValue(false);
    spyOn(explorationEngineService, 'getState').and.returnValue({
      name: 'State1',
      cardIsCheckpoint: true,
    });
    spyOn(
      playerTranscriptService,
      'getPrevSessionStatesProgress'
    ).and.returnValue([]);
    spyOn(
      checkpointProgressService,
      'checkIfCheckpointIsVisited'
    ).and.returnValue(false);
    spyOn(
      readOnlyExplorationBackendApiService,
      'loadLatestExplorationAsync'
    ).and.returnValue(Promise.resolve({version: 2}));
    spyOn(
      editableExplorationBackendApiService,
      'recordMostRecentlyReachedCheckpointAsync'
    );
    spyOn(checkpointProgressService, 'setMostRecentlyReachedCheckpoint');
    spyOn(checkpointProgressService, 'setVisitedCheckpointStateNames');
    spyOn(playerPositionService.onActiveCardChanged, 'emit');
    spyOn(audioPlayerService.onAutoplayAudio, 'emit');
    spyOn(autogeneratedAudioPlayerService, 'cancel');
    spyOn(conversationFlowService, 'getNextFocusLabel').and.returnValue(
      'focusLabel'
    );
    spyOn(playerTranscriptService, 'isLastCard').and.returnValue(true);
    spyOn(focusManagerService, 'setFocusIfOnDesktop');

    conversationFlowService.navigateToDisplayedCard();
    tick();

    expect(
      checkpointProgressService.setMostRecentlyReachedCheckpoint
    ).toHaveBeenCalledWith('State1');
    expect(
      editableExplorationBackendApiService.recordMostRecentlyReachedCheckpointAsync
    ).toHaveBeenCalled();
    expect(playerPositionService.onActiveCardChanged.emit).toHaveBeenCalled();
    expect(audioPlayerService.onAutoplayAudio.emit).toHaveBeenCalled();
    expect(autogeneratedAudioPlayerService.cancel).toHaveBeenCalled();
    expect(focusManagerService.setFocusIfOnDesktop).toHaveBeenCalledWith(
      'focusLabel'
    );
  }));

  it('should throw error when moving forward beyond last card', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(4);
    spyOn(playerTranscriptService, 'getNumCards').and.returnValue(5);

    // Moving to index 5 (equal to num cards) → out of bounds.
    expect(() => {
      conversationFlowService.moveForwardByOneCard();
    }).toThrowError('Target card index out of bounds.');
  });

  it('should throw error when moving backward before first card', () => {
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(0);
    spyOn(playerTranscriptService, 'getNumCards').and.returnValue(5);

    // Moving to index -1 → out of bounds.
    expect(() => {
      conversationFlowService.moveBackByOneCard();
    }).toThrowError('Target card index out of bounds.');
  });

  it('should return correct value for isRefresherExploration', () => {
    conversationFlowService.isRefresherExploration = true;
    expect(conversationFlowService.getIsRefresherExploration()).toBeTrue();

    conversationFlowService.isRefresherExploration = false;
    expect(conversationFlowService.getIsRefresherExploration()).toBeFalse();
  });

  it('should return correct parent exploration IDs', () => {
    const parentIds = ['exp1', 'exp2'];
    conversationFlowService.parentExplorationIds = parentIds;

    expect(conversationFlowService.getParentExplorationIds()).toEqual(
      parentIds
    );
  });

  it('should set and get nextCardIfStuck', () => {
    const mockCard = createCard('TextInput');
    conversationFlowService.setNextCardIfStuck(mockCard);
    expect(conversationFlowService.getNextCardIfStuck()).toBe(mockCard);
  });

  it('should set and get solution for state', () => {
    const mockSolution = {
      correctAnswer: true,
      explanationHtml: 'Html',
      answerIsExclusive: true,
      explanationContentId: 'content_id',
    } as Solution;

    conversationFlowService.setSolutionForState(mockSolution);
    expect(conversationFlowService.getSolutionForState()).toBe(mockSolution);
  });

  it('should defer stuck check when isDelayed is true', fakeAsync(() => {
    const mockCallback = jasmine.createSpy('onShowContinueToReviseButton');

    spyOn(
      playerTranscriptService,
      'getNumberOfIncorrectSubmissions'
    ).and.returnValue(
      ExplorationPlayerConstants.MAX_INCORRECT_ANSWERS_BEFORE_RELEASING_SOLUTION
    );
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(0);
    spyOn(playerTranscriptService, 'getCard').and.returnValue(
      createCard('TextInput')
    );
    spyOn(hintsAndSolutionManagerService, 'releaseSolution');

    const mockSolution = {
      correctAnswer: true,
      explanationHtml: 'Html',
      answerIsExclusive: true,
      explanationContentId: 'content_id',
    } as Solution;
    conversationFlowService.setSolutionForState(mockSolution);
    conversationFlowService.triggerIfLearnerStuckAction(true, mockCallback);
    tick(
      ExplorationPlayerConstants.WAIT_BEFORE_RESPONSE_FOR_STUCK_LEARNER_MSEC
    );

    expect(hintsAndSolutionManagerService.releaseSolution).toHaveBeenCalled();
  }));

  it('should defer stuck check when isDelayed is false', fakeAsync(() => {
    conversationFlowService.responseTimeout = 100;
    const mockCallback = jasmine.createSpy('onShowContinueToReviseButton');
    spyOn(playerPositionService, 'getDisplayedCardIndex').and.returnValue(0);

    const nextCardIfStuck = new StateCard(
      'StuckCard',
      null,
      null,
      new Interaction([], [], null, null, [], 'EndExploration', null),
      [],
      '',
      null
    );

    let displayedCard = new StateCard(
      'CurrentCard',
      null,
      null,
      new Interaction([], [], null, null, [], '', null),
      [],
      '',
      null
    );

    spyOn(playerTranscriptService, 'getCard').and.returnValue(displayedCard);
    conversationFlowService.nextCardIfStuck = nextCardIfStuck;
    conversationFlowService.triggerIfLearnerStuckAction(false, mockCallback);
  }));

  it('should set and get next state card', () => {
    const nextCard = new StateCard(
      'NextCard',
      null,
      null,
      new Interaction([], [], null, null, [], 'TextInput', null),
      [],
      '',
      null
    );

    conversationFlowService.setNextStateCard(nextCard);

    expect(conversationFlowService.getNextStateCard()).toBe(nextCard);
  });
});
