// Copyright 2014 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Service for recommending explorations at the end of an
 * exploration.
 */

import {Injectable} from '@angular/core';

import {PageContextService} from 'services/page-context.service';
import {ServicesConstants} from 'services/services.constants';
import {UrlService} from 'services/contextual/url.service';

import {ExplorationRecommendationsBackendApiService} from 'domain/recommendations/exploration-recommendations-backend-api.service';
import {LearnerExplorationSummary} from 'domain/summary/learner-exploration-summary.model';

@Injectable({
  providedIn: 'root',
})
export class ExplorationRecommendationsService {
  isIframed: boolean = false;
  recommendedStoryNodeId!: string;
  isInEditorPage: boolean = false;
  isInEditorPreviewMode: boolean = false;
  // This property is initialized using Angular lifecycle hooks
  // and we need to do non-null assertion. For more information, see
  // https://github.com/oppia/oppia/wiki/Guide-on-defining-types#ts-7-1
  explorationId!: string;

  constructor(
    private pageContextService: PageContextService,
    private urlService: UrlService,
    private expRecommendationBackendApiService: ExplorationRecommendationsBackendApiService
  ) {
    this.isIframed = this.urlService.isIframed();
    this.isInEditorPage =
      this.pageContextService.getPageContext() ===
      ServicesConstants.PAGE_CONTEXT.EXPLORATION_EDITOR;
    this.isInEditorPreviewMode =
      this.isInEditorPage &&
      this.pageContextService.getEditorTabContext() ===
        ServicesConstants.EXPLORATION_EDITOR_TAB_CONTEXT.PREVIEW;
  }

  getRecommendedSummaryDicts(
    authorRecommendedExpIds: string[],
    includeAutogeneratedRecommendations: boolean,
    successCallback: (value: LearnerExplorationSummary[]) => void
  ): void {
    let collectionId = this.urlService.getCollectionIdFromExplorationUrl();
    let storyId = this.urlService.getUrlParams().story_id;
    let currentNodeId = this.urlService.getUrlParams().node_id;
    this.explorationId = this.pageContextService.getExplorationId();

    let includeSystemRecommendations = 'false';

    if (includeAutogeneratedRecommendations && !this.isInEditorPage) {
      includeSystemRecommendations = 'true';
    }

    this.expRecommendationBackendApiService
      .getRecommendedSummaryDictsAsync(
        authorRecommendedExpIds,
        includeSystemRecommendations,
        collectionId,
        storyId,
        currentNodeId,
        this.explorationId
      )
      .then(expSummaries => {
        successCallback(expSummaries);
      });
  }

  /**
   * Generates a navigable URL to a recommended exploration, including
   * optional context parameters like collection ID, topic, classroom, and story.
   *
   * This method is typically used to construct the link to the next
   * recommended exploration in the learner view, preserving context
   * from the current exploration if available.
   *
   * @param {LearnerExplorationSummary[]} recommendedExplorationSummaries
   *   An array of recommended exploration summaries. The method uses the
   *   first element (index 0) to get the exploration ID and related metadata.
   *
   * @returns {string} A complete exploration URL with appropriate query
   *   parameters, or `'#'` if no valid exploration ID is found.
   *
   * Example Output:
   *   "/explore/exp123?topic_url_fragment=fractions&classroom_url_fragment=math&story_url_fragment=story-fractions&node_id=node_3"
   */
  getExplorationLink(
    recommendedExplorationSummaries: LearnerExplorationSummary[]
  ): string {
    const collectionId = this.urlService.getCollectionIdFromExplorationUrl();

    if (recommendedExplorationSummaries && recommendedExplorationSummaries[0]) {
      const explorationId = recommendedExplorationSummaries[0].id;
      if (!explorationId) {
        return '#';
      }

      let result = '/explore/' + explorationId;
      const urlParams = this.urlService.getUrlParams();

      let collectionIdToAdd = collectionId;
      let storyUrlFragmentToAdd: string | null = null;
      let topicUrlFragment: string | null = null;
      let classroomUrlFragment: string | null = null;

      if (
        urlParams.hasOwnProperty('story_url_fragment') &&
        urlParams.hasOwnProperty('node_id') &&
        urlParams.hasOwnProperty('topic_url_fragment') &&
        urlParams.hasOwnProperty('classroom_url_fragment')
      ) {
        topicUrlFragment = urlParams.topic_url_fragment;
        classroomUrlFragment = urlParams.classroom_url_fragment;
        storyUrlFragmentToAdd = urlParams.story_url_fragment;
      }

      if (collectionIdToAdd) {
        result = this.urlService.addField(
          result,
          'collection_id',
          collectionIdToAdd
        );
      }

      if (
        classroomUrlFragment &&
        topicUrlFragment &&
        storyUrlFragmentToAdd &&
        this.recommendedStoryNodeId
      ) {
        result = this.urlService.addField(
          result,
          'topic_url_fragment',
          topicUrlFragment
        );
        result = this.urlService.addField(
          result,
          'classroom_url_fragment',
          classroomUrlFragment
        );
        result = this.urlService.addField(
          result,
          'story_url_fragment',
          storyUrlFragmentToAdd
        );
        result = this.urlService.addField(
          result,
          'node_id',
          this.recommendedStoryNodeId
        );
      }

      return result;
    }

    return '#';
  }

  /**
   * Sets the recommended story node ID for the exploration recommendations.
   *
   * This ID is used to construct the URL for the recommended exploration
   * when the learner is navigating through a story.
   *
   * @param recommendedStoryNodeId - The ID of the recommended story node.
   */
  setRecommendedStoryNodeId(recommendedStoryNodeId: string): void {
    this.recommendedStoryNodeId = recommendedStoryNodeId;
  }
}
