// Copyright 2014 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Service for recommending explorations at the end of an
 * exploration.
 */

import { downgradeInjectable } from '@angular/upgrade/static';
import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';

import { ContextService } from 'services/context.service';
import { ServicesConstants } from 'services/services.constants';
import { UrlService } from 'services/contextual/url.service';

export interface ISummary {
  category: string;
  // eslint-disable-next-line camelcase
  community_owned: boolean;
  id: string;
  // eslint-disable-next-line camelcase
  language_code: string;
  // eslint-disable-next-line camelcase
  num_views: number;
  objective: string;
  status: string;
  tags: string[];
  // eslint-disable-next-line camelcase
  thumbnail_bg_color: string;
  // eslint-disable-next-line camelcase
  thumbnail_icon_url: string;
  title: string;
}
export interface ISummaries {
  summaries: ISummary[];
}

@Injectable({
  providedIn: 'root'
})
export class ExplorationRecommendationsService {
  constructor(
    private contextService: ContextService,
    private http: HttpClient,
    private urlService: UrlService) {
    ExplorationRecommendationsService.isIframed = this.urlService.isIframed();
    ExplorationRecommendationsService.isInEditorPage = (
      this.contextService.getPageContext() ===
      ServicesConstants.PAGE_CONTEXT.EXPLORATION_EDITOR);
    ExplorationRecommendationsService.isInEditorPreviewMode = (
      ExplorationRecommendationsService.isInEditorPage && (
        this.contextService.getEditorTabContext() ===
        ServicesConstants.EXPLORATION_EDITOR_TAB_CONTEXT.PREVIEW));
    ExplorationRecommendationsService.explorationId = (
      this.contextService.getExplorationId());
  }
  static isIframed: boolean = null;
  static isInEditorPage: boolean = null;
  static isInEditorPreviewMode: boolean = null;
  static explorationId: string = null;

  getRecommendedSummaryDicts(
      authorRecommendedExpIds: string[],
      includeAutogeneratedRecommendations: boolean,
      successCallback: (value?: Object | PromiseLike<Object>) => void): void {
    var recommendationsUrlParams = {
      stringified_author_recommended_ids: JSON.stringify(
        authorRecommendedExpIds),
      collection_id: this.urlService.getCollectionIdFromExplorationUrl(),
      story_id: this.urlService.getUrlParams().story_id,
      current_node_id: this.urlService.getUrlParams().node_id,
      include_system_recommendations: null
    };

    if (
      includeAutogeneratedRecommendations &&
      !ExplorationRecommendationsService.isInEditorPage) {
      recommendationsUrlParams.include_system_recommendations = 'true';
    }

    this.http.get(
      '/explorehandler/recommendations/' +
      ExplorationRecommendationsService.explorationId, {
        params: recommendationsUrlParams
      }).toPromise().then((data: ISummaries) => {
      successCallback(data.summaries);
    });
  }
}
angular.module('oppia').factory('ExplorationRecommendationsService',
  downgradeInjectable(ExplorationRecommendationsService));
