// Copyright 2020 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Index file for all angular2+ services
 */

/**
 * No changes should be made to this file. Treat this as a read-only
 * file. This is just to provide angular2+ services to 11 specs listed below.
 * No more specs should be added to the list. The only edit that is allowed
 * to this file is removing the file names from list.
 *
 * Filenames:
 *   01. stewards-landing-page.component.spec.ts
 *   02. topic-landing-page.component.spec.ts
 *   03. notifications-dashboard-page.component.spec.ts
 *   04. splash-page.component.spec.ts
 *   05. teach-page.component.spec.ts
 *   06. nested-directives-recursion-timeout-prevention.service.spec.ts
 *   07. question-validation.service.spec.ts
 *   08. rte-helper-modal.controller.spec.ts
 *   09. svg-filename-editor.component.spec.ts
 *   10. preview-summary-tile-modal.controller.spec.ts
 *   11. registration-session-expired-modal.controller.spec.ts
 */

/* eslint-disable max-len */
import { AdminDataService } from
  'pages/admin-page/services/admin-data.service';
import { AdminRouterService } from
  'pages/admin-page/services/admin-router.service.ts';
import { AdminTaskManagerService } from
  'pages/admin-page/services/admin-task-manager.service';
import { AlertsService } from 'services/alerts.service';
import { AngularNameService } from
  'pages/exploration-editor-page/services/angular-name.service';
import { AnswerClassificationResultObjectFactory } from
  'domain/classifier/AnswerClassificationResultObjectFactory';
import { AnswerClassificationService } from
  'pages/exploration-player-page/services/answer-classification.service';
import { AnswerGroupsCacheService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/editor-tab/services/answer-groups-cache.service';
import { AnswerGroupObjectFactory } from
  'domain/exploration/AnswerGroupObjectFactory';
import { AnswerStatsObjectFactory } from
  'domain/exploration/AnswerStatsObjectFactory';
import { AppService } from 'services/app.service';
import { AudioBarStatusService } from 'services/audio-bar-status.service';
import { AudioFileObjectFactory } from
  'domain/utilities/AudioFileObjectFactory';
import { AudioLanguageObjectFactory } from
  'domain/utilities/AudioLanguageObjectFactory';
import { AudioTranslationLanguageService } from
  'pages/exploration-player-page/services/audio-translation-language.service';
import { AudioTranslationManagerService } from
  'pages/exploration-player-page/services/audio-translation-manager.service';
import { AutogeneratedAudioLanguageObjectFactory } from
  'domain/utilities/AutogeneratedAudioLanguageObjectFactory';
import { AutogeneratedAudioPlayerService } from
  'services/autogenerated-audio-player.service';
import { AutoplayedVideosService } from 'services/autoplayed-videos.service';
import { BackgroundMaskService } from
  'services/stateful/background-mask.service';
import { baseInteractionValidationService } from
  'interactions/base-interaction-validation.service';
import { BrowserCheckerService } from
  'domain/utilities/browser-checker.service';
import { CamelCaseToHyphensPipe } from
  'filters/string-utility-filters/camel-case-to-hyphens.pipe';
import { ChangeObjectFactory } from
  'domain/editor/undo_redo/ChangeObjectFactory';
import { ClassifierObjectFactory } from
  'domain/classifier/ClassifierObjectFactory';
import { ClassroomBackendApiService } from
  'domain/classroom/classroom-backend-api.service';
import { CodeNormalizerService } from 'services/code-normalizer.service';
import { CodeReplPredictionService } from
  'interactions/CodeRepl/code-repl-prediction.service';
import { CodeReplRulesService } from
  'interactions/CodeRepl/directives/code-repl-rules.service';
import { CodeReplValidationService } from
  'interactions/CodeRepl/directives/code-repl-validation.service';
import { CollectionCreationBackendService } from
  'components/entity-creation-services/collection-creation-backend-api.service';
import { CollectionCreationService } from
  'components/entity-creation-services/collection-creation.service';
import { CollectionNodeObjectFactory } from
  'domain/collection/collection-node-object.factory';
import { CollectionObjectFactory } from
  'domain/collection/CollectionObjectFactory';
import { CollectionPlaythroughObjectFactory } from
  'domain/collection/CollectionPlaythroughObjectFactory';
import { CollectionRightsBackendApiService } from
  'domain/collection/collection-rights-backend-api.service';
import { CollectionRightsObjectFactory } from
  'domain/collection/CollectionRightsObjectFactory';
import { CollectionValidationService } from
  'domain/collection/collection-validation.service';
import { ComputeGraphService } from 'services/compute-graph.service';
import { ConceptCardObjectFactory } from
  'domain/skill/ConceptCardObjectFactory';
import { ContextService } from 'services/context.service';
import { ContinueValidationService } from
  'interactions/Continue/directives/continue-validation.service';
import { ContributionOpportunitiesBackendApiService } from
  // eslint-disable-next-line max-len
  'pages/community-dashboard-page/services/contribution-opportunities-backend-api.service';
import { ConstructTranslationIdsService } from
  'services/construct-translation-ids.service';
import { CountVectorizerService } from 'classifiers/count-vectorizer.service';
import { CreatorDashboardBackendApiService } from
  'domain/creator_dashboard/creator-dashboard-backend-api.service';
import { CsrfTokenService } from 'services/csrf-token.service';
import { CurrentInteractionService } from
  'pages/exploration-player-page/services/current-interaction.service';
import { DateTimeFormatService } from 'services/date-time-format.service';
import { DebouncerService } from 'services/debouncer.service';
import { DeviceInfoService } from 'services/contextual/device-info.service';
import { DocumentAttributeCustomizationService } from
  'services/contextual/document-attribute-customization.service';
import { DragAndDropSortInputRulesService } from
  // eslint-disable-next-line max-len
  'interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-rules.service';
import { DragAndDropSortInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/DragAndDropSortInput/directives/drag-and-drop-sort-input-validation.service';
import { EditableCollectionBackendApiService } from
  'domain/collection/editable-collection-backend-api.service';
import { EditabilityService } from 'services/editability.service';
import { EditorFirstTimeEventsService } from
  'pages/exploration-editor-page/services/editor-first-time-events.service';
import { EndExplorationValidationService } from
  'interactions/EndExploration/directives/end-exploration-validation.service';
import { EmailDashboardDataService } from
  'pages/email-dashboard-pages/email-dashboard-data.service';
import { EntityContextObjectFactory } from
  'domain/utilities/EntityContextObjectFactory';
import { ExplorationDiffService } from
  'pages/exploration-editor-page/services/exploration-diff.service';
import { ExplorationDraftObjectFactory } from
  'domain/exploration/ExplorationDraftObjectFactory';
import { ExplorationFeaturesBackendApiService } from
  'services/exploration-features-backend-api.service';
import { ExplorationFeaturesService } from
  'services/exploration-features.service';
import { ExplorationHtmlFormatterService } from
  'services/exploration-html-formatter.service';
import { ExplorationMetadataObjectFactory } from
  'domain/exploration/ExplorationMetadataObjectFactory';
import { ExplorationObjectFactory } from
  'domain/exploration/ExplorationObjectFactory';
import { ExplorationOpportunitySummaryObjectFactory } from
  'domain/opportunity/ExplorationOpportunitySummaryObjectFactory';
import { ExpressionParserService } from 'expressions/expression-parser.service';
import { ExplorationRecommendationsService } from
  'pages/exploration-player-page/services/exploration-recommendations.service';
import { ExpressionSyntaxTreeService } from
  'expressions/expression-syntax-tree.service';
import { ExtensionTagAssemblerService } from
  'services/extension-tag-assembler.service';
import { ExtractImageFilenamesFromStateService } from
  // eslint-disable-next-line max-len
  'pages/exploration-player-page/services/extract-image-filenames-from-state.service';
import { FeedbackMessageSummaryObjectFactory } from
  'domain/feedback_message/FeedbackMessageSummaryObjectFactory';
import { FeedbackThreadObjectFactory } from
  'domain/feedback_thread/FeedbackThreadObjectFactory';
import { FeedbackThreadSummaryObjectFactory } from
  'domain/feedback_thread/FeedbackThreadSummaryObjectFactory';
import { FileDownloadRequestObjectFactory } from
  'domain/utilities/FileDownloadRequestObjectFactory';
import { FormatTimePipe } from 'filters/format-timer.pipe';
import { FractionInputValidationService } from
  'interactions/FractionInput/directives/fraction-input-validation.service';
import { FractionObjectFactory } from 'domain/objects/FractionObjectFactory';
import { GenerateContentIdService } from 'services/generate-content-id.service';
import { GraphDetailService } from
  'interactions/GraphInput/directives/graph-detail.service';
import { GraphInputValidationService } from
  'interactions/GraphInput/directives/graph-input-validation.service';
import { GraphUtilsService } from
  'interactions/GraphInput/directives/graph-utils.service';
import { GuestCollectionProgressObjectFactory } from
  'domain/collection/GuestCollectionProgressObjectFactory';
import { GuestCollectionProgressService } from
  'domain/collection/guest-collection-progress.service';
import { HintObjectFactory } from 'domain/exploration/HintObjectFactory';
import { HtmlEscaperService } from 'services/html-escaper.service';
import { I18nLanguageCodeService } from 'services/i18n-language-code.service';
import { IdGenerationService } from 'services/id-generation.service';
import { ImageClickInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/ImageClickInput/directives/image-click-input-validation.service';
import { ImageFileObjectFactory } from
  'domain/utilities/ImageFileObjectFactory';
import { ImprovementsService } from 'services/improvements.service';
import { InteractionDetailsCacheService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/editor-tab/services/interaction-details-cache.service';
import { InteractionObjectFactory } from
  'domain/exploration/InteractionObjectFactory';
import { InteractionRulesRegistryService } from
  'services/interaction-rules-registry.service';
import { InteractionSpecsService } from 'services/interaction-specs.service';
import { InteractiveMapValidationService } from
  'interactions/InteractiveMap/directives/interactive-map-validation.service';
import { ItemSelectionInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/ItemSelectionInput/directives/item-selection-input-validation.service';
import { LanguageUtilService } from 'domain/utilities/language-util.service';
import { LearnerActionObjectFactory } from
  'domain/statistics/LearnerActionObjectFactory';
import { LearnerAnswerDetailsBackendApiService } from
  'domain/statistics/learner-answer-details-backend-api.service';
import { LearnerAnswerDetailsObjectFactory } from
  'domain/statistics/LearnerAnswerDetailsObjectFactory';
import { LearnerAnswerInfoObjectFactory } from
  'domain/statistics/LearnerAnswerInfoObjectFactory';
import { LearnerDashboardActivityIdsObjectFactory } from
  'domain/learner_dashboard/LearnerDashboardActivityIdsObjectFactory';
import { LearnerDashboardBackendApiService } from
  'domain/learner_dashboard/learner-dashboard-backend-api.service';
import { LearnerDashboardIdsBackendApiService } from
  'domain/learner_dashboard/learner-dashboard-ids-backend-api.service';
import { LearnerParamsService } from
  'pages/exploration-player-page/services/learner-params.service';
import { LocalStorageService } from 'services/local-storage.service';
import { LoaderService } from 'services/loader.service';
import { LoggerService } from 'services/contextual/logger.service';
import { LogicProofValidationService } from
  'interactions/LogicProof/directives/logic-proof-validation.service';
import { LostChangeObjectFactory } from
  'domain/exploration/LostChangeObjectFactory';
import { MathExpressionInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MathExpressionInput/directives/math-expression-input-validation.service';
import { MessengerService } from 'services/messenger.service';
import { MetaTagCustomizationService } from
  'services/contextual/meta-tag-customization.service';
import { MisconceptionObjectFactory } from
  'domain/skill/MisconceptionObjectFactory';
import { MultipleChoiceInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MultipleChoiceInput/directives/multiple-choice-input-validation.service';
import { MusicNotesInputValidationService } from
  // eslint-disable-next-line max-len
  'interactions/MusicNotesInput/directives/music-notes-input-validation.service';
import { MusicPhrasePlayerService } from
  // eslint-disable-next-line max-len
  'interactions/MusicNotesInput/directives/music-phrase-player.service';
import { NewlyCreatedTopicObjectFactory } from
  'domain/topics_and_skills_dashboard/NewlyCreatedTopicObjectFactory';
import { NormalizeWhitespacePipe } from
  'filters/string-utility-filters/normalize-whitespace.pipe';
import { NormalizeWhitespacePunctuationAndCasePipe } from
  // eslint-disable-next-line max-len
  'filters/string-utility-filters/normalize-whitespace-punctuation-and-case.pipe';
import { NumberAttemptsService } from
  'pages/exploration-player-page/services/number-attempts.service';
import { NumericInputValidationService } from
  'interactions/NumericInput/directives/numeric-input-validation.service';
import { NumberWithUnitsObjectFactory } from
  'domain/objects/NumberWithUnitsObjectFactory';
import { NumberWithUnitsValidationService } from
  // eslint-disable-next-line max-len
  'interactions/NumberWithUnits/directives/number-with-units-validation.service.ts';
import { OutcomeObjectFactory } from 'domain/exploration/OutcomeObjectFactory';
import { PageTitleService } from 'services/page-title.service';
import { ParamChangeObjectFactory } from
  'domain/exploration/ParamChangeObjectFactory';
import { ParamChangesObjectFactory } from
  'domain/exploration/ParamChangesObjectFactory';
import { ParamMetadataObjectFactory } from
  'domain/exploration/ParamMetadataObjectFactory';
import { ParamSpecObjectFactory } from
  'domain/exploration/ParamSpecObjectFactory';
import { ParamSpecsObjectFactory } from
  'domain/exploration/ParamSpecsObjectFactory';
import { ParamTypeObjectFactory } from
  'domain/exploration/ParamTypeObjectFactory';
import { PencilCodeEditorRulesService } from
  'interactions/PencilCodeEditor/directives/pencil-code-editor-rules.service';
import { PencilCodeEditorValidationService } from
  'interactions/PencilCodeEditor/directives/pencil-code-editor-validation.service';
import { PlayerCorrectnessFeedbackEnabledService } from
  'pages/exploration-player-page/services/player-correctness-feedback-enabled.service';
import { PlayerPositionService } from
  'pages/exploration-player-page/services/player-position.service';
import { PlayerTranscriptService } from
  'pages/exploration-player-page/services/player-transcript.service';
import { PlaythroughIssueObjectFactory } from
  'domain/statistics/PlaythroughIssueObjectFactory';
import { PlaythroughIssuesBackendApiService } from
  'services/playthrough-issues-backend-api.service';
import { PlaythroughObjectFactory } from
  'domain/statistics/PlaythroughObjectFactory';
import { PlaythroughService } from 'services/playthrough.service';
import { PredictionAlgorithmRegistryService } from
  'pages/exploration-player-page/services/prediction-algorithm-registry.service';
import { PredictionResultObjectFactory } from
  'domain/classifier/PredictionResultObjectFactory';
import { PretestQuestionBackendApiService } from
  'domain/question/pretest-question-backend-api.service';
import { ProfilePageBackendApiService } from
  'pages/profile-page/profile-page-backend-api.service';
import { PythonProgramTokenizer } from 'classifiers/python-program.tokenizer';
import { QuestionBackendApiService } from
  'domain/question/question-backend-api.service.ts';
import { QuestionSummaryForOneSkillObjectFactory }
  from 'domain/question/QuestionSummaryForOneSkillObjectFactory';
import { QuestionSummaryObjectFactory } from
  'domain/question/QuestionSummaryObjectFactory';
import { ReadOnlyCollectionBackendApiService } from
  'domain/collection/read-only-collection-backend-api.service';
import { RatingComputationService } from
  'components/ratings/rating-computation/rating-computation.service';
import { ReadOnlyStoryNodeObjectFactory } from
  'domain/story_viewer/ReadOnlyStoryNodeObjectFactory';
import { ReadOnlySubtopicPageObjectFactory } from
  'domain/subtopic_viewer/ReadOnlySubtopicPageObjectFactory';
import { ReadOnlyTopicObjectFactory } from
  'domain/topic_viewer/read-only-topic-object.factory';
import { RecordedVoiceoversObjectFactory } from
  'domain/exploration/RecordedVoiceoversObjectFactory';
import { ReviewTestBackendApiService } from
  'domain/review_test/review-test-backend-api.service';
import { ReviewTestEngineService } from
  'pages/review-test-page/review-test-engine.service.ts';
import { RubricObjectFactory } from
  'domain/skill/RubricObjectFactory';
import { RuleObjectFactory } from 'domain/exploration/RuleObjectFactory';
import { SchemaDefaultValueService } from
  'services/schema-default-value.service';
import { SchemaUndefinedLastElementService } from
  'services/schema-undefined-last-element.service';
import { SearchExplorationsBackendApiService } from
  'domain/collection/search-explorations-backend-api.service';
import { SetInputValidationService } from
  'interactions/SetInput/directives/set-input-validation.service';
import { SVMPredictionService } from 'classifiers/svm-prediction.service';
import { SidebarStatusService } from 'domain/sidebar/sidebar-status.service';
import { SiteAnalyticsService } from 'services/site-analytics.service';
import { SkillCreationBackendApiService } from
  'domain/skill/skill-creation-backend-api.service';
import { SkillDifficultyObjectFactory } from
  'domain/skill/SkillDifficultyObjectFactory';
import { SkillMasteryBackendApiService } from
  'domain/skill/skill-mastery-backend-api.service';
import { SkillObjectFactory } from 'domain/skill/SkillObjectFactory';
import { SkillOpportunityObjectFactory } from
  'domain/opportunity/SkillOpportunityObjectFactory';
import { SkillRightsBackendApiService} from
  'domain/skill/skill-rights-backend-api.service.ts';
import { SkillRightsObjectFactory } from
  'domain/skill/SkillRightsObjectFactory';
import { SkillSummaryObjectFactory } from
  'domain/skill/SkillSummaryObjectFactory';
import { SolutionObjectFactory } from
  'domain/exploration/SolutionObjectFactory';
import { SolutionValidityService } from
  'pages/exploration-editor-page/editor-tab/services/solution-validity.service';
import { SpeechSynthesisChunkerService } from
  'services/speech-synthesis-chunker.service';
import { StateCardObjectFactory } from
  'domain/state_card/StateCardObjectFactory';
import { StateClassifierMappingService } from
  'pages/exploration-player-page/services/state-classifier-mapping.service';
import { StateContentService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-content.service';
import { StateCustomizationArgsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-customization-args.service';
import { StateEditorService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-editor.service';
import { StateGraphLayoutService } from
  'components/graph-services/graph-layout.service';
import { StateHintsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-hints.service';
import { StateInteractionIdService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-interaction-id.service';
import { StateInteractionStatsService } from
  'services/state-interaction-stats.service';
import { StateNameService } from
  'components/state-editor/state-editor-properties-services/state-name.service';
import { StateObjectFactory } from 'domain/state/StateObjectFactory';
import { StateParamChangesService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-param-changes.service';
import { StatePropertyService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-property.service';
import { StateRecordedVoiceoversService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-recorded-voiceovers.service';
import { StateSolicitAnswerDetailsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-solicit-answer-details.service';
import { StateSolutionService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-solution.service';
import { StateTopAnswersStatsBackendApiService } from
  'services/state-top-answers-stats-backend-api.service';
import { StateWrittenTranslationsService } from
  // eslint-disable-next-line max-len
  'components/state-editor/state-editor-properties-services/state-written-translations.service';
import { StatesObjectFactory } from 'domain/exploration/StatesObjectFactory';
import { StatsReportingService } from
  'pages/exploration-player-page/services/stats-reporting.service';
import { StopwatchObjectFactory } from
  'domain/utilities/StopwatchObjectFactory';
import { StoryContentsObjectFactory } from
  'domain/story/StoryContentsObjectFactory';
import { StoryNodeObjectFactory } from
  'domain/story/StoryNodeObjectFactory';
import { StoryObjectFactory } from 'domain/story/StoryObjectFactory';
import { StoryPlaythroughObjectFactory } from
  'domain/story_viewer/StoryPlaythroughObjectFactory';
import { StoryReferenceObjectFactory } from
  'domain/topic/StoryReferenceObjectFactory';
import { StorySummaryObjectFactory } from
  'domain/story/StorySummaryObjectFactory';
import { StoryViewerBackendApiService } from
  'domain/story_viewer/story-viewer-backend-api.service';
import { SubtitledHtmlObjectFactory } from
  'domain/exploration/SubtitledHtmlObjectFactory';
import { SubtopicObjectFactory } from 'domain/topic/SubtopicObjectFactory';
import { SubtopicPageContentsObjectFactory } from
  'domain/topic/SubtopicPageContentsObjectFactory';
import { SubtopicPageObjectFactory } from
  'domain/topic/SubtopicPageObjectFactory';
import { SubtopicViewerBackendApiService } from
  'domain/subtopic_viewer/subtopic-viewer-backend-api.service';
import { SuggestionModalService } from 'services/suggestion-modal.service';
import { SuggestionObjectFactory } from
  'domain/suggestion/SuggestionObjectFactory';
import { SuggestionThreadObjectFactory } from
  'domain/suggestion/SuggestionThreadObjectFactory';
import { SuggestionsService } from 'services/suggestions.service';
import { TextInputPredictionService } from
  'interactions/TextInput/text-input-prediction.service';
import { TextInputRulesService } from
  'interactions/TextInput/directives/text-input-rules.service';
import { TextInputTokenizer } from 'classifiers/text-input.tokenizer';
import { TextInputValidationService } from
  'interactions/TextInput/directives/text-input-validation.service';
import { ThreadMessageObjectFactory } from
  'domain/feedback_message/ThreadMessageObjectFactory';
import { ThreadMessageSummaryObjectFactory } from
  'domain/feedback_message/ThreadMessageSummaryObjectFactory';
import { ThreadStatusDisplayService } from
  // eslint-disable-next-line max-len
  'pages/exploration-editor-page/feedback-tab/services/thread-status-display.service';
import { TopicCreationBackendApiService } from
  'domain/topic/topic-creation-backend-api.service.ts';
import { TopicObjectFactory } from 'domain/topic/TopicObjectFactory';
import { TopicRightsObjectFactory } from
  'domain/topic/TopicRightsObjectFactory';
import { TopicsAndSkillsDashboardBackendApiService } from
  // eslint-disable-next-line max-len
  'domain/topics_and_skills_dashboard/topics-and-skills-dashboard-backend-api.service';
import { TopicSummaryObjectFactory } from
  'domain/topic/TopicSummaryObjectFactory';
import { TopicsAndSkillsDashboardFilterObjectFactory } from
  // eslint-disable-next-line max-len
  'domain/topics_and_skills_dashboard/TopicsAndSkillsDashboardFilterObjectFactory';
import { TopicsAndSkillsDashboardPageService } from
  // eslint-disable-next-line max-len
  'pages/topics-and-skills-dashboard-page/topics-and-skills-dashboard-page.service';
import { TopicViewerBackendApiService } from
  'domain/topic_viewer/topic-viewer-backend-api.service';
import { UnitsObjectFactory } from 'domain/objects/UnitsObjectFactory';
import { UrlInterpolationService } from
  'domain/utilities/url-interpolation.service';
import { UrlService } from 'services/contextual/url.service';
import { UserExplorationPermissionsService } from
  'pages/exploration-editor-page/services/user-exploration-permissions.service';
import { UserInfoObjectFactory } from 'domain/user/UserInfoObjectFactory';
import { UtilsService } from 'services/utils.service';
import { ValidatorsService } from 'services/validators.service';
import { VersionTreeService } from
  'pages/exploration-editor-page/history-tab/services/version-tree.service';
import { VoiceoverObjectFactory } from
  'domain/exploration/VoiceoverObjectFactory';
import { WindowDimensionsService } from
  'services/contextual/window-dimensions.service';
import { WindowRef } from 'services/contextual/window-ref.service';
import { WinnowingPreprocessingService } from
  'classifiers/winnowing-preprocessing.service';
import { WorkedExampleObjectFactory } from
  'domain/skill/WorkedExampleObjectFactory';
import { WrittenTranslationObjectFactory } from
  'domain/exploration/WrittenTranslationObjectFactory';
import { WrittenTranslationsObjectFactory } from
  'domain/exploration/WrittenTranslationsObjectFactory';
import { ConceptCardBackendApiService } from 'domain/skill/concept-card-backend-api.service';
import { StateStatsObjectFactory } from 'domain/statistics/StateStatsObjectFactory';
import { TaskEntryObjectFactory } from 'domain/improvements/TaskEntryObjectFactory';
import { ExplorationStatsService } from 'services/exploration-stats.service';
import { ExplorationStatsBackendApiService } from 'services/exploration-stats-backend-api.service';
import { ExplorationStatsObjectFactory } from 'domain/statistics/ExplorationStatsObjectFactory';
import { HighBounceRateTaskObjectFactory } from 'domain/improvements/HighBounceRateTaskObjectFactory';

export const ANGULAR_SERVICES = [
  AdminDataService, AdminRouterService, AdminTaskManagerService, AlertsService,
  AngularNameService, AnswerClassificationResultObjectFactory,
  AnswerClassificationService, AnswerGroupsCacheService,
  AnswerGroupObjectFactory, AnswerStatsObjectFactory, AppService,
  AudioBarStatusService, AudioFileObjectFactory, AudioLanguageObjectFactory,
  AudioTranslationLanguageService, AudioTranslationManagerService,
  AutogeneratedAudioLanguageObjectFactory, AutogeneratedAudioPlayerService,
  AutoplayedVideosService, BackgroundMaskService,
  baseInteractionValidationService, BrowserCheckerService,
  CamelCaseToHyphensPipe, ChangeObjectFactory, ClassifierObjectFactory,
  ClassroomBackendApiService, CodeNormalizerService, CodeReplPredictionService,
  CodeReplRulesService, CodeReplValidationService,
  CollectionCreationBackendService, CollectionCreationService,
  CollectionNodeObjectFactory, CollectionObjectFactory,
  CollectionPlaythroughObjectFactory, CollectionRightsBackendApiService,
  CollectionRightsObjectFactory, CollectionValidationService,
  ComputeGraphService, ConceptCardBackendApiService, ConceptCardObjectFactory,
  ContextService, ContinueValidationService,
  ContributionOpportunitiesBackendApiService, ConstructTranslationIdsService,
  CountVectorizerService, CreatorDashboardBackendApiService, CsrfTokenService,
  CurrentInteractionService, DateTimeFormatService, DebouncerService,
  DeviceInfoService, DocumentAttributeCustomizationService,
  DragAndDropSortInputRulesService, DragAndDropSortInputValidationService,
  EditableCollectionBackendApiService, EditabilityService,
  EditorFirstTimeEventsService, EndExplorationValidationService,
  EmailDashboardDataService, EntityContextObjectFactory, ExplorationDiffService,
  ExplorationDraftObjectFactory, ExplorationFeaturesBackendApiService,
  ExplorationFeaturesService, ExplorationHtmlFormatterService,
  ExplorationMetadataObjectFactory, ExplorationObjectFactory,
  ExplorationOpportunitySummaryObjectFactory, ExplorationStatsBackendApiService,
  ExplorationStatsObjectFactory, ExplorationStatsService,
  ExpressionParserService, ExplorationRecommendationsService,
  ExpressionSyntaxTreeService, ExtensionTagAssemblerService,
  ExtractImageFilenamesFromStateService, FeedbackMessageSummaryObjectFactory,
  FeedbackThreadObjectFactory, FeedbackThreadSummaryObjectFactory,
  FileDownloadRequestObjectFactory, FractionInputValidationService,
  FractionObjectFactory, GenerateContentIdService, GraphDetailService,
  GraphInputValidationService, GraphUtilsService,
  GuestCollectionProgressObjectFactory, GuestCollectionProgressService,
  HighBounceRateTaskObjectFactory, HintObjectFactory, HtmlEscaperService,
  I18nLanguageCodeService, IdGenerationService, ImageClickInputValidationService,
  ImageFileObjectFactory,
  ImprovementsService, InteractionDetailsCacheService, InteractionObjectFactory,
  InteractionRulesRegistryService, InteractionSpecsService,
  InteractiveMapValidationService, ItemSelectionInputValidationService,
  LanguageUtilService, LearnerActionObjectFactory,
  LearnerAnswerDetailsBackendApiService, LearnerAnswerDetailsObjectFactory,
  LearnerAnswerInfoObjectFactory, LearnerDashboardActivityIdsObjectFactory,
  LearnerDashboardBackendApiService, LearnerDashboardIdsBackendApiService,
  LearnerParamsService, LocalStorageService, LoaderService, LoggerService,
  LogicProofValidationService, LostChangeObjectFactory,
  MathExpressionInputValidationService, MessengerService,
  MetaTagCustomizationService, MisconceptionObjectFactory,
  MultipleChoiceInputValidationService, MusicNotesInputValidationService,
  MusicPhrasePlayerService, NewlyCreatedTopicObjectFactory,
  NormalizeWhitespacePipe, NormalizeWhitespacePunctuationAndCasePipe,
  NumberAttemptsService, NumericInputValidationService,
  NumberWithUnitsObjectFactory, NumberWithUnitsValidationService,
  OutcomeObjectFactory, PageTitleService, ParamChangeObjectFactory,
  ParamChangesObjectFactory, ParamMetadataObjectFactory, ParamSpecObjectFactory,
  ParamSpecsObjectFactory, ParamTypeObjectFactory, PencilCodeEditorRulesService,
  PencilCodeEditorValidationService, PlayerCorrectnessFeedbackEnabledService,
  PlayerPositionService, PlayerTranscriptService, PlaythroughIssueObjectFactory,
  PlaythroughIssuesBackendApiService, PlaythroughObjectFactory,
  PlaythroughService, PredictionAlgorithmRegistryService,
  PredictionResultObjectFactory, PretestQuestionBackendApiService,
  ProfilePageBackendApiService, PythonProgramTokenizer,
  QuestionBackendApiService,
  QuestionSummaryForOneSkillObjectFactory, QuestionSummaryObjectFactory,
  RatingComputationService, ReadOnlyCollectionBackendApiService,
  ReadOnlyStoryNodeObjectFactory, ReadOnlySubtopicPageObjectFactory,
  ReadOnlyTopicObjectFactory, RecordedVoiceoversObjectFactory,
  ReviewTestBackendApiService, ReviewTestEngineService, RubricObjectFactory,
  RuleObjectFactory, SchemaDefaultValueService,
  SchemaUndefinedLastElementService, SearchExplorationsBackendApiService,
  SetInputValidationService, SVMPredictionService, SidebarStatusService,
  SiteAnalyticsService, SkillCreationBackendApiService,
  SkillDifficultyObjectFactory, SkillMasteryBackendApiService,
  SkillObjectFactory, SkillOpportunityObjectFactory,
  SkillRightsBackendApiService, SkillRightsObjectFactory,
  SkillSummaryObjectFactory, SolutionObjectFactory, SolutionValidityService,
  SpeechSynthesisChunkerService, StateCardObjectFactory,
  StateClassifierMappingService, StateContentService,
  StateCustomizationArgsService, StateEditorService, StateGraphLayoutService,
  StateHintsService,
  StateInteractionIdService, StateInteractionStatsService, StateNameService,
  StateObjectFactory, StateParamChangesService, StatePropertyService,
  StateRecordedVoiceoversService, StateSolicitAnswerDetailsService,
  StateSolutionService, StateStatsObjectFactory,
  StateTopAnswersStatsBackendApiService, StateWrittenTranslationsService,
  StatesObjectFactory, StatsReportingService, StopwatchObjectFactory,
  StoryContentsObjectFactory, StoryNodeObjectFactory, StoryObjectFactory,
  StoryPlaythroughObjectFactory, StoryReferenceObjectFactory,
  StorySummaryObjectFactory, StoryViewerBackendApiService,
  SubtitledHtmlObjectFactory, SubtopicObjectFactory,
  SubtopicPageContentsObjectFactory, SubtopicPageObjectFactory,
  SubtopicViewerBackendApiService, SuggestionModalService,
  SuggestionObjectFactory, SuggestionThreadObjectFactory, SuggestionsService,
  TaskEntryObjectFactory, TextInputPredictionService, TextInputRulesService,
  TextInputTokenizer, TextInputValidationService, ThreadMessageObjectFactory,
  ThreadMessageSummaryObjectFactory, ThreadStatusDisplayService,
  TopicCreationBackendApiService, TopicObjectFactory, TopicRightsObjectFactory,
  TopicsAndSkillsDashboardBackendApiService, TopicSummaryObjectFactory,
  TopicsAndSkillsDashboardFilterObjectFactory,
  TopicsAndSkillsDashboardPageService, TopicViewerBackendApiService,
  UnitsObjectFactory, UrlInterpolationService, UrlService,
  UserExplorationPermissionsService, UserInfoObjectFactory, UtilsService,
  ValidatorsService, VersionTreeService, VoiceoverObjectFactory,
  WindowDimensionsService, WindowRef, WinnowingPreprocessingService,
  WorkedExampleObjectFactory, WrittenTranslationObjectFactory
];

export const ANGULAR_SERVICES_NAMES = [
  'AdminDataService', 'AdminRouterService', 'AdminTaskManagerService',
  'AlertsService', 'AngularNameService',
  'AnswerClassificationResultObjectFactory', 'AnswerClassificationService',
  'AnswerGroupsCacheService', 'AnswerGroupObjectFactory',
  'AnswerStatsObjectFactory', 'AppService', 'AudioBarStatusService',
  'AudioFileObjectFactory', 'AudioLanguageObjectFactory',
  'AudioTranslationLanguageService', 'AudioTranslationManagerService',
  'AutogeneratedAudioLanguageObjectFactory', 'AutogeneratedAudioPlayerService',
  'AutoplayedVideosService', 'BackgroundMaskService',
  'baseInteractionValidationService', 'BrowserCheckerService',
  'CamelCaseToHyphensPipe', 'ChangeObjectFactory', 'ClassifierObjectFactory',
  'ClassroomBackendApiService', 'CodeNormalizerService',
  'CodeReplPredictionService', 'CodeReplRulesService',
  'CodeReplValidationService', 'CollectionCreationBackendService',
  'CollectionCreationService', 'CollectionNodeObjectFactory',
  'CollectionObjectFactory', 'CollectionPlaythroughObjectFactory',
  'CollectionRightsBackendApiService', 'CollectionRightsObjectFactory',
  'CollectionValidationService', 'ComputeGraphService',
  'ConceptCardBackendApiService', 'ConceptCardObjectFactory', 'ContextService',
  'ContinueValidationService', 'ContributionOpportunitiesBackendApiService',
  'ConstructTranslationIdsService', 'CountVectorizerService',
  'CreatorDashboardBackendApiService', 'CsrfTokenService',
  'CurrentInteractionService', 'DateTimeFormatService', 'DebouncerService',
  'DeviceInfoService', 'DocumentAttributeCustomizationService',
  'DragAndDropSortInputRulesService', 'DragAndDropSortInputValidationService',
  'EditableCollectionBackendApiService', 'EditabilityService',
  'EditorFirstTimeEventsService', 'EndExplorationValidationService',
  'EmailDashboardDataService', 'EntityContextObjectFactory',
  'ExplorationDiffService', 'ExplorationDraftObjectFactory',
  'ExplorationFeaturesBackendApiService', 'ExplorationFeaturesService',
  'ExplorationHtmlFormatterService', 'ExplorationMetadataObjectFactory',
  'ExplorationObjectFactory', 'ExplorationOpportunitySummaryObjectFactory',
  'ExplorationStatsBackendApiService', 'ExplorationStatsObjectFactory',
  'ExplorationStatsService', 'ExpressionParserService',
  'ExplorationRecommendationsService', 'ExpressionSyntaxTreeService',
  'ExtensionTagAssemblerService', 'ExtractImageFilenamesFromStateService',
  'FeedbackMessageSummaryObjectFactory', 'FeedbackThreadObjectFactory',
  'FeedbackThreadSummaryObjectFactory', 'FileDownloadRequestObjectFactory',
  'FractionInputValidationService', 'FractionObjectFactory',
  'GenerateContentIdService', 'GraphDetailService',
  'GraphInputValidationService', 'GraphUtilsService',
  'GuestCollectionProgressObjectFactory', 'GuestCollectionProgressService',
  'HighBounceRateTaskObjectFactory', 'HintObjectFactory', 'HtmlEscaperService',
  'I18nLanguageCodeService', 'IdGenerationService',
  'ImageClickInputValidationService', 'ImageFileObjectFactory',
  'ImprovementsService',
  'InteractionDetailsCacheService', 'InteractionObjectFactory',
  'InteractionRulesRegistryService', 'InteractionSpecsService',
  'InteractiveMapValidationService', 'ItemSelectionInputValidationService',
  'LanguageUtilService', 'LearnerActionObjectFactory',
  'LearnerAnswerDetailsBackendApiService', 'LearnerAnswerDetailsObjectFactory',
  'LearnerAnswerInfoObjectFactory', 'LearnerDashboardActivityIdsObjectFactory',
  'LearnerDashboardBackendApiService', 'LearnerDashboardIdsBackendApiService',
  'LearnerParamsService', 'LocalStorageService', 'LoaderService',
  'LoggerService', 'LogicProofValidationService', 'LostChangeObjectFactory',
  'MathExpressionInputValidationService', 'MessengerService',
  'MetaTagCustomizationService', 'MisconceptionObjectFactory',
  'MultipleChoiceInputValidationService', 'MusicNotesInputValidationService',
  'MusicPhrasePlayerService', 'NewlyCreatedTopicObjectFactory',
  'NormalizeWhitespacePipe', 'NormalizeWhitespacePunctuationAndCasePipe',
  'NumberAttemptsService', 'NumericInputValidationService',
  'NumberWithUnitsObjectFactory', 'NumberWithUnitsValidationService',
  'OutcomeObjectFactory', 'PageTitleService', 'ParamChangeObjectFactory',
  'ParamChangesObjectFactory', 'ParamMetadataObjectFactory',
  'ParamSpecObjectFactory', 'ParamSpecsObjectFactory', 'ParamTypeObjectFactory',
  'PencilCodeEditorRulesService', 'PencilCodeEditorValidationService',
  'PlayerCorrectnessFeedbackEnabledService', 'PlayerPositionService',
  'PlayerTranscriptService', 'PlaythroughIssueObjectFactory',
  'PlaythroughIssuesBackendApiService', 'PlaythroughObjectFactory',
  'PlaythroughService', 'PredictionAlgorithmRegistryService',
  'PredictionResultObjectFactory', 'PretestQuestionBackendApiService',
  'ProfilePageBackendApiService', 'PythonProgramTokenizer',
  'QuestionBackendApiService',
  'QuestionSummaryForOneSkillObjectFactory', 'QuestionSummaryObjectFactory',
  'RatingComputationService', 'ReadOnlyCollectionBackendApiService',
  'ReadOnlyStoryNodeObjectFactory', 'ReadOnlySubtopicPageObjectFactory',
  'ReadOnlyTopicObjectFactory', 'RecordedVoiceoversObjectFactory',
  'ReviewTestBackendApiService', 'ReviewTestEngineService',
  'RubricObjectFactory', 'RuleObjectFactory', 'SchemaDefaultValueService',
  'SchemaUndefinedLastElementService', 'SearchExplorationsBackendApiService',
  'SetInputValidationService', 'SVMPredictionService', 'SidebarStatusService',
  'SiteAnalyticsService', 'SkillCreationBackendApiService',
  'SkillDifficultyObjectFactory', 'SkillMasteryBackendApiService',
  'SkillObjectFactory', 'SkillOpportunityObjectFactory',
  'SkillRightsBackendApiService', 'SkillRightsObjectFactory',
  'SkillSummaryObjectFactory', 'SolutionObjectFactory',
  'SolutionValidityService', 'SpeechSynthesisChunkerService',
  'StateCardObjectFactory', 'StateClassifierMappingService',
  'StateContentService', 'StateCustomizationArgsService', 'StateEditorService',
  'StateGraphLayoutService', 'StateHintsService',
  'StateInteractionIdService',
  'StateInteractionStatsService', 'StateNameService', 'StateObjectFactory',
  'StateParamChangesService', 'StatePropertyService',
  'StateRecordedVoiceoversService', 'StateSolicitAnswerDetailsService',
  'StateSolutionService', 'StateStatsObjectFactory',
  'StateTopAnswersStatsBackendApiService', 'StateWrittenTranslationsService',
  'StatesObjectFactory', 'StatsReportingService', 'StopwatchObjectFactory',
  'StoryContentsObjectFactory', 'StoryNodeObjectFactory', 'StoryObjectFactory',
  'StoryPlaythroughObjectFactory', 'StoryReferenceObjectFactory',
  'StorySummaryObjectFactory', 'StoryViewerBackendApiService',
  'SubtitledHtmlObjectFactory', 'SubtopicObjectFactory',
  'SubtopicPageContentsObjectFactory', 'SubtopicPageObjectFactory',
  'SubtopicViewerBackendApiService', 'SuggestionModalService',
  'SuggestionObjectFactory', 'SuggestionThreadObjectFactory',
  'SuggestionsService', 'TaskEntryObjectFactory', 'TextInputPredictionService',
  'TextInputRulesService', 'TextInputTokenizer', 'TextInputValidationService',
  'ThreadMessageObjectFactory', 'ThreadMessageSummaryObjectFactory',
  'ThreadStatusDisplayService', 'TopicCreationBackendApiService',
  'TopicObjectFactory', 'TopicRightsObjectFactory',
  'TopicsAndSkillsDashboardBackendApiService', 'TopicSummaryObjectFactory',
  'TopicsAndSkillsDashboardFilterObjectFactory',
  'TopicsAndSkillsDashboardPageService', 'TopicViewerBackendApiService',
  'UnitsObjectFactory', 'UrlInterpolationService', 'UrlService',
  'UserExplorationPermissionsService', 'UserInfoObjectFactory', 'UtilsService',
  'ValidatorsService', 'VersionTreeService', 'VoiceoverObjectFactory',
  'WindowDimensionsService', 'WindowRef', 'WinnowingPreprocessingService',
  'WorkedExampleObjectFactory', 'WrittenTranslationObjectFactory',
];
