# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_classifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='text_classifier.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x15text_classifier.proto\":\n\x19TextClassifierFrozenModel\x12\x1d\n\nmodel_json\x18\x01 \x01(\tR\tmodelJsonb\x06proto3'
)




_TEXTCLASSIFIERFROZENMODEL = _descriptor.Descriptor(
  name='TextClassifierFrozenModel',
  full_name='TextClassifierFrozenModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='model_json', full_name='TextClassifierFrozenModel.model_json', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, json_name='modelJson', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['TextClassifierFrozenModel'] = _TEXTCLASSIFIERFROZENMODEL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextClassifierFrozenModel = _reflection.GeneratedProtocolMessageType('TextClassifierFrozenModel', (_message.Message,), {
  'DESCRIPTOR' : _TEXTCLASSIFIERFROZENMODEL,
  '__module__' : 'text_classifier_pb2'
  # @@protoc_insertion_point(class_scope:TextClassifierFrozenModel)
  })
_sym_db.RegisterMessage(TextClassifierFrozenModel)


# @@protoc_insertion_point(module_scope)
