// Copyright 2017 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Service to operate the playback of autogenerated audio
 * using the SpeechSynthesis API.
 */

oppia.factory('AutogeneratedAudioPlayerService', [
  'SpeechSynthesisChunkerService',
  function(SpeechSynthesisChunkerService) {
    var DEFAULT_PLAYBACK_RATE = 0.92;

    var _speechSynthesis = window.speechSynthesis;
    // Not all browsers support SpeechSynthesisUtterance, so we need the
    // fallback to prevent a "SpeechSynthesisUtterance is not defined" error.
    var utterance = (
      SpeechSynthesisUtterance ? new SpeechSynthesisUtterance() : null);
    // The paused property of speech synthesis seems to return false
    // no matter what, so we manually define our own property to track.
    var _isPlaying = false;

    var _play = function(html, language, audioFinishedCallback) {
      message = SpeechSynthesisChunkerService.convertToSpeakableText(html);
      utterance.text = message;
      utterance.lang = language;
      utterance.rate = DEFAULT_PLAYBACK_RATE;
      _isPlaying = true;
      SpeechSynthesisChunkerService.speak(
        utterance,
        function() {
          _isPlaying = false;
          audioFinishedCallback();
        }
      );
    };

    return {
      play: function(html, language, audioFinishedCallback) {
        return _play(html, language, audioFinishedCallback);
      },
      pause: function() {
        // Pause and resume don't seem to work well. When an utterance is
        // paused and an attempt to resume is made more than approximately 15
        // seconds later, nothing happens. Avoid using for now.
        _speechSynthesis.pause();
        _isPlaying = false;
      },
      resume: function() {
        _speechSynthesis.resume();
        _isPlaying = true;
      },
      cancel: function() {
        SpeechSynthesisChunkerService.cancel();
        _isPlaying = false;
      },
      isPlaying: function() {
        return _isPlaying;
      }
    }
  }
]);
