// Copyright 2018 The Oppia Authors. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS-IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * @fileoverview Primary controller for the skill editor page.
 */

//vvv this block of requires should be removed vvv
require('components/CkEditorRteDirective.ts');
require('components/CkEditorWidgetsInitializer.ts');
require('components/state/AnswerGroupEditorDirective.ts');
require('components/state/OutcomeEditorDirective.ts');
require('components/state/OutcomeDestinationEditorDirective.ts');
require('components/state/OutcomeFeedbackEditorDirective.ts');
require('components/state/RuleEditorDirective.ts');
require('components/state/RuleTypeSelectorDirective.ts');
require('components/state/SolutionEditorDirective.ts');
require('components/state/SolutionExplanationEditorDirective.ts');
require('components/forms/HtmlSelectDirective.ts');
require('components/forms/ConvertUnicodeWithParamsToHtmlFilter.ts');
require('components/forms/ConvertHtmlToUnicodeFilter.ts');
require('components/forms/ConvertUnicodeToHtmlFilter.ts');
require('components/forms/validators/IsAtLeastFilter.ts');
require('components/forms/validators/IsAtMostFilter.ts');
require('components/forms/validators/IsFloatFilter.ts');
require('components/forms/validators/IsIntegerFilter.ts');
require('components/forms/validators/IsNonemptyFilter.ts');
require('components/forms/ApplyValidationDirective.ts');
require('components/forms/RequireIsFloatDirective.ts');
require('components/forms/schema_editors/SchemaBasedCustomEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedDictEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedExpressionEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedFloatEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedHtmlEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedIntEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedListEditorDirective.ts');
require('components/forms/schema_editors/SchemaBasedUnicodeEditorDirective.ts');
require('components/forms/schema_viewers/SchemaBasedCustomViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedDictViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedHtmlViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedListViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedPrimitiveViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedUnicodeViewerDirective.ts');
require('components/forms/schema_viewers/SchemaBasedViewerDirective.ts');
require('directives/MathjaxBindDirective.ts');
//^^^ this block of requires should be removed ^^^

require('pages/skill_editor/SkillEditorNavbarDirective.ts');
require('pages/skill_editor/SkillEditorNavbarBreadcrumbDirective.ts');
require('pages/skill_editor/editor_tab/SkillEditorMainTabDirective.ts');
require('pages/skill_editor/questions_tab/QuestionsTabDirective.ts');

require('domain/utilities/LanguageUtilService.ts');
require('domain/utilities/AudioLanguageObjectFactory.ts');
require('domain/utilities/AutogeneratedAudioLanguageObjectFactory.ts');
require('domain/utilities/BrowserCheckerService.ts');

oppia.constant('INTERACTION_SPECS', GLOBALS.INTERACTION_SPECS);
oppia.constant(
  'SKILL_RIGHTS_URL_TEMPLATE',
  '/skill_editor_handler/rights/<skill_id>');

oppia.constant(
  'SKILL_PUBLISH_URL_TEMPLATE',
  '/skill_editor_handler/publish_skill/<skill_id>');

oppia.controller('SkillEditor', [
  'SkillEditorStateService', 'UrlService',
  function(SkillEditorStateService, UrlService) {
    SkillEditorStateService.loadSkill(UrlService.getSkillIdFromUrl());
  }
]);
