# coding: utf-8
#
# Copyright 2020 The Oppia Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Models related to Oppia improvement tasks."""

from __future__ import absolute_import  # pylint: disable=import-only-modules
from __future__ import unicode_literals  # pylint: disable=import-only-modules

from core.domain import user_services
from core.platform import models
import python_utils
import utils

(improvements_models,) = (
    models.Registry.import_models([models.NAMES.improvements]))


class TaskEntry(python_utils.OBJECT):
    """Domain object representing a task entry model in storage.

    Attributes:
        entity_type: str. The type of entity the task entry refers to.
            For example, "exploration".
        entity_id: str. The ID of the entity the task entry refers to.
            For example, an exploration ID.
        entity_version: int. The version of the entity the task entry refers to.
            For example, an exploration's version.
        task_type: str. The type of task the task entry tracks.
        target_type: str. The type of sub-entity the task entry refers to.
            For example, "state" when entity type is "exploration".
        target_id: str. The ID of the sub-entity the task entry refers to.
            For example, the state name of an exploration.
        issue_description: str. The sentence generated by Oppia to describe why
            the task was created.
        status: str. Tracks the state/progress of the task entry.
        resolver_id: str or None. The user who resolved the task, if applicable.
        resolver_id: str or None. The time at which the task was resolved, if
            applicable.
    """

    def __init__(
            self, entity_type, entity_id, entity_version, task_type,
            target_type, target_id, issue_description, status, resolver_id,
            resolved_on):
        self.entity_type = entity_type
        self.entity_id = entity_id
        self.entity_version = entity_version
        self.task_type = task_type
        self.target_type = target_type
        self.target_id = target_id
        self.issue_description = issue_description
        self.status = status
        self.resolver_id = resolver_id
        self.resolved_on = resolved_on

    @property
    def task_id(self):
        """Returns the unique identifier of this task.

        Returns:
            str. The ID of this task.
        """
        return improvements_models.TaskEntryModel.generate_task_id(
            self.entity_type, self.entity_id, self.entity_version,
            self.task_type, self.target_type, self.target_id)

    @property
    def composite_entity_id(self):
        """Returns value of helper field for identifying the task's target
        entity.

        Returns:
            str. The value of the helper field.
        """
        return improvements_models.TaskEntryModel.generate_composite_entity_id(
            self.entity_type, self.entity_id, self.entity_version)

    @classmethod
    def from_payload_dict(
            cls, payload_dict, resolver_id=None, resolved_on=None):
        """Returns a new TaskEntry domain object from the given payload dict and
        optional resolver ID.

        Args:
            payload_dict: dict. Contains the following keys:
                entity_type: str. The type of entity the task entry refers to.
                    For example, "exploration".
                entity_id: str. The ID of the entity the task entry refers to.
                    For example, an exploration ID.
                entity_version: int. The version of the entity the task entry
                    refers to. For example, an exploration's version.
                task_type: str. The type of task the task entry tracks.
                target_type: str. The type of sub-entity the task entry refers
                    to. For example, "state" when entity type is "exploration".
                target_id: str. The ID of the sub-entity the task entry refers
                    to. For example, the state name of an exploration.
                issue_description: str. The sentence generated by Oppia to
                    describe why the task was created.
                status: str. Tracks the state/progress of the task entry.
            resolver_id: str or None. The corresponding user who resolved this
                task. Only used when payload dict's status is resolved.
            resolved_on: datetime or None. The datetime at which this task was
                resolved. Only used when payload dict's status is resolved.

        Returns:
            improvements_domain.TaskEntry.

        Raises:
            Exception. When payload's status is resolved, but the resolver_id
            is missing.
        """
        if payload_dict['status'] == improvements_models.TASK_STATUS_RESOLVED:
            if resolver_id is None or resolved_on is None:
                raise Exception('Missing resolution arguments for the task')
        else:
            resolver_id = None
            resolved_on = None
        return cls(
            payload_dict['entity_type'], payload_dict['entity_id'],
            payload_dict['entity_version'], payload_dict['task_type'],
            payload_dict['target_type'], payload_dict['target_id'],
            payload_dict['issue_description'], payload_dict['status'],
            resolver_id, resolved_on)

    def to_dict(self):
        """Returns a dict-representation of the task.

        Returns:
            dict. Contains the following keys:
                entity_type: str. The type of entity the task entry refers to.
                    For example, "exploration".
                entity_id: str. The ID of the entity the task entry refers to.
                    For example, an exploration ID.
                entity_version: int. The version of the entity the task entry
                    refers to. For example, an exploration's version.
                task_type: str. The type of task the task entry tracks.
                target_type: str. The type of sub-entity the task entry refers
                    to. For example, "state" when entity type is "exploration".
                target_id: str. The ID of the sub-entity the task entry refers
                    to. For example, the state name of an exploration.
                issue_description: str. The sentence generated by Oppia to
                    describe why the task was created.
                status: str. Tracks the state/progress of the task entry.
                resolver_username: str. Username of the user who resolved the
                    task, if applicable.
                resolver_profile_picture_data_url: str. URL to profile picture
                    of the user who resolved the task, if applicable.
                resolved_on_msecs: float. Time in milliseconds since epoch at
                    which the task was resolved, if applicable.
        """
        resolver_settings = (
            self.resolver_id and
            user_services.get_user_settings(self.resolver_id, strict=True))
        return {
            'entity_type': self.entity_type,
            'entity_id': self.entity_id,
            'entity_version': self.entity_version,
            'task_type': self.task_type,
            'target_type': self.target_type,
            'target_id': self.target_id,
            'issue_description': self.issue_description,
            'status': self.status,
            'resolver_username': (
                resolver_settings and resolver_settings.username),
            'resolver_profile_picture_data_url': (
                resolver_settings and
                resolver_settings.profile_picture_data_url),
            'resolved_on_msecs': (
                self.resolved_on and
                utils.get_time_in_millisecs(self.resolved_on)),
        }
