# coding: utf-8
#
# Copyright 2024 The Oppia Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS-IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Tests for voiecover service methods."""

from __future__ import annotations

import json
import os

from core import feconf
from core import schema_utils
from core import utils
from core.domain import state_domain
from core.domain import user_services
from core.domain import voiceover_services
from core.platform import models
from core.tests import test_utils

from typing import Dict

MYPY = False
if MYPY: # pragma: no cover
    from mypy_imports import voiceover_models


(voiceover_models,) = models.Registry.import_models([
    models.Names.VOICEOVER])


class EntityVoiceoversServicesTests(test_utils.GenericTestBase):
    def test_get_entity_voiceovers_returns_correctly(self) -> None:
        dummy_manual_voiceover_dict: state_domain.VoiceoverDict = {
            'filename': 'filename1.mp3',
            'file_size_bytes': 3000,
            'needs_update': False,
            'duration_secs': 6.1
        }
        dummy_autogenerated_voiceover_dict: state_domain.VoiceoverDict = {
            'filename': 'filename2.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.9
        }
        voiceover_models.EntityVoiceoversModel.create_new(
            feconf.ENTITY_TYPE_EXPLORATION, 'exp_id', 1, 'en-US', {
                'content_0': {
                    feconf.VoiceoverType.MANUAL.value: (
                        dummy_manual_voiceover_dict),
                    feconf.VoiceoverType.AUTO.value: (
                        dummy_autogenerated_voiceover_dict)
                }
            }
        ).put()

        entity_voiceovers_instance = (
            voiceover_services.get_voiceovers_for_given_language_accent_code(
                'exploration', 'exp_id', 1, 'en-US'))

        self.assertEqual(entity_voiceovers_instance.entity_id, 'exp_id')
        self.assertEqual(entity_voiceovers_instance.entity_type, 'exploration')
        self.assertEqual(entity_voiceovers_instance.entity_version, 1)
        self.assertEqual(
            entity_voiceovers_instance.language_accent_code, 'en-US')
        self.assertDictEqual(
            entity_voiceovers_instance.voiceovers['content_0'][
                feconf.VoiceoverType.MANUAL].to_dict(),
            dummy_manual_voiceover_dict)
        self.assertDictEqual(
            entity_voiceovers_instance.voiceovers['content_0'][
                feconf.VoiceoverType.AUTO].to_dict(),
            dummy_autogenerated_voiceover_dict)

    def test_get_entity_voiceovers_creates_new_entity(self) -> None:
        entity_voiceovers_instance = (
            voiceover_services.get_voiceovers_for_given_language_accent_code(
                'exploration', 'exp_id', 1, 'en-US'))

        self.assertEqual(entity_voiceovers_instance.entity_id, 'exp_id')
        self.assertEqual(entity_voiceovers_instance.entity_type, 'exploration')
        self.assertEqual(entity_voiceovers_instance.entity_version, 1)
        self.assertEqual(
            entity_voiceovers_instance.language_accent_code, 'en-US')
        self.assertDictEqual(entity_voiceovers_instance.voiceovers, {})


class VoiceoverAutogenerationPolicyTests(test_utils.GenericTestBase):
    """Unit tests to validate the saving and fetching behavior in the
    VoiceoverAutogenerationPolicyModel.
    """

    def test_save_and_get_language_accent_codes_works_correctly(self) -> None:
        language_codes_mapping: Dict[str, Dict[str, bool]] = {
            'en': {
                'en-US': True
            },
            'hi': {
                'hi-IN': False
            }
        }
        retrieved_language_codes_mapping: Dict[str, Dict[str, bool]] = (
            voiceover_services.get_all_language_accent_codes_for_voiceovers())
        expected_language_codes_mapping: Dict[str, Dict[str, bool]] = {}
        self.assertDictEqual(
            retrieved_language_codes_mapping, expected_language_codes_mapping)

        voiceover_services.save_language_accent_support(
            language_codes_mapping=language_codes_mapping)

        retrieved_language_codes_mapping = (
            voiceover_services.get_all_language_accent_codes_for_voiceovers())
        self.assertDictEqual(
            retrieved_language_codes_mapping, language_codes_mapping)


class VoiceoversLanguageAccentConstantsTests(test_utils.GenericTestBase):
    """Unit tests to validate the language-accent information saved as
    constants in the JSON files.
    """

    def test_get_language_accent_master_list_works_correctly(self) -> None:
        file_path = os.path.join(
            feconf.VOICEOVERS_DATA_DIR, 'language_accent_master_list.json')
        with utils.open_file(file_path, 'r') as f:
            language_accent_master_list: Dict[str, Dict[str, str]] = (
                json.loads(f.read()))
            expected_language_accent_master_list = (
                voiceover_services.get_language_accent_master_list())

            self.assertDictEqual(
                language_accent_master_list,
                expected_language_accent_master_list)

    def test_get_autogeneratable_language_accent_list_works_correctly(
        self
    ) -> None:
        file_path = os.path.join(
            feconf.VOICEOVERS_DATA_DIR,
            'autogeneratable_language_accent_list.json')
        with utils.open_file(file_path, 'r') as f:
            autogeneratable_language_accent_list: Dict[str, Dict[str, str]] = (
                json.loads(f.read()))
            expected_autogeneratable_language_accent_list = (
                voiceover_services.get_autogeneratable_language_accent_list())

            self.assertDictEqual(
                autogeneratable_language_accent_list,
                expected_autogeneratable_language_accent_list)

    def test_validate_data_format_stored_in_master_list_is_correct(
        self
    ) -> None:
        valid_schema = {
            'type': 'variable_keys_dict',
            'keys': {
                'schema': {
                    'type': 'basestring'
                }
            },
            'values': {
                'schema': {
                    'type': 'variable_keys_dict',
                    'keys': {
                        'schema': {
                            'type': 'basestring'
                        }
                    },
                    'values': {
                        'schema': {
                            'type': 'basestring'
                        }
                    }
                }
            }
        }
        try:
            schema_utils.normalize_against_schema(
                voiceover_services.get_language_accent_master_list(),
                valid_schema)
        except Exception:
            self.fail(
                'get_language_accent_master_list() raised '
                'ExceptionType unexpectedly!')

    def test_validate_data_format_stored_in_autogeneratable_list_is_correct(
        self
    ) -> None:
        valid_schema = {
            'type': 'variable_keys_dict',
            'keys': {
                'schema': {
                    'type': 'basestring'
                }
            },
            'values': {
                'schema': {
                    'type': 'dict',
                    'properties': [{
                        'name': 'service',
                        'schema': {
                            'type': 'basestring'
                        }
                    }, {
                        'name': 'voice_code',
                        'schema': {
                            'type': 'basestring'
                        }
                    }]
                }
            }
        }
        try:
            schema_utils.normalize_against_schema(
                voiceover_services.get_autogeneratable_language_accent_list(),
                valid_schema)
        except Exception:
            self.fail(
                'get_autogeneratable_language_accent_list() raised '
                'ExceptionType unexpectedly!')

    def test_validate_autogeneratable_list_is_subset_of_master_list(
        self
    ) -> None:
        language_accent_master_list = []
        for accent_code_to_description in (
                voiceover_services.get_language_accent_master_list().values()):
            for lang_accent_code in accent_code_to_description.keys():
                language_accent_master_list.append(lang_accent_code)
        autogeneratable_langauge_accent_codes = list(
            voiceover_services.
            get_autogeneratable_language_accent_list().keys())

        self.assertTrue(
            set(language_accent_master_list).issuperset(
                set(autogeneratable_langauge_accent_codes)))


class VoiceArtistMetadataTests(test_utils.GenericTestBase):
    """Unit test to validate voice artists metadata informations."""

    def setUp(self) -> None:
        super().setUp()
        self.voice_artist_id = 'voice_artist_id'
        self.language_code_to_accent = {
            'en': 'en-US',
            'hi': 'hi-IN'
        }

    def test_should_create_and_put_new_voice_artist_model(self) -> None:
        initial_retrieved_model = voiceover_models.VoiceArtistMetadataModel.get(
            self.voice_artist_id, strict=False)
        self.assertIsNone(initial_retrieved_model)

        voiceover_services.update_voice_artist_metadata(
            self.voice_artist_id,
            self.language_code_to_accent
        )

        final_retrieved_model = voiceover_models.VoiceArtistMetadataModel.get(
            self.voice_artist_id, strict=False)
        self.assertIsNotNone(final_retrieved_model)

    def test_should_update_and_put_existing_voice_artist_model(self) -> None:
        voiceover_services.update_voice_artist_metadata(
            self.voice_artist_id, {})
        retrieved_model = voiceover_models.VoiceArtistMetadataModel.get(
            self.voice_artist_id, strict=False)
        assert retrieved_model is not None

        self.assertDictEqual(
            retrieved_model.language_code_to_accent, {})

        voiceover_services.update_voice_artist_metadata(
            self.voice_artist_id, self.language_code_to_accent)

        retrieved_model = voiceover_models.VoiceArtistMetadataModel.get(
            self.voice_artist_id, strict=False)
        assert retrieved_model is not None

        self.assertDictEqual(
            retrieved_model.language_code_to_accent,
            self.language_code_to_accent)

    def test_update_voice_artist_language_mapping(self) -> None:
        language_code = 'en'
        initial_language_accent_code = 'en-US'
        final_language_accent_code = 'en-IN'
        voiceover_services.update_voice_artist_metadata(
            self.voice_artist_id, self.language_code_to_accent)

        voice_artist_metadata_model = (
            voiceover_models.VoiceArtistMetadataModel.get(
                self.voice_artist_id, strict=False))
        assert voice_artist_metadata_model is not None

        self.assertEqual(
            voice_artist_metadata_model.language_code_to_accent[language_code],
            initial_language_accent_code
        )

        voiceover_services.update_voice_artist_language_mapping(
            self.voice_artist_id, language_code, final_language_accent_code)

        voice_artist_metadata_model = (
            voiceover_models.VoiceArtistMetadataModel.get(
                self.voice_artist_id, strict=False))
        assert voice_artist_metadata_model is not None

        self.assertEqual(
            voice_artist_metadata_model.language_code_to_accent[language_code],
            final_language_accent_code)

    def test_should_create_and_update_voice_artist_language_mapping(
        self
    ) -> None:
        language_code = 'en'
        language_accent_code = 'en-US'

        voice_artist_metadata_model = (
            voiceover_models.VoiceArtistMetadataModel.get(
                self.voice_artist_id, strict=False))

        self.assertIsNone(voice_artist_metadata_model)

        voiceover_services.update_voice_artist_language_mapping(
            self.voice_artist_id, language_code, language_accent_code)

        voice_artist_metadata_model = (
            voiceover_models.VoiceArtistMetadataModel.get(
                self.voice_artist_id, strict=False))
        assert voice_artist_metadata_model is not None

        self.assertEqual(
            voice_artist_metadata_model.language_code_to_accent[language_code],
            language_accent_code)

    def test_should_create_voice_artist_metadata_model_successfully(
        self
    ) -> None:
        voice_artist_metadata_model = (
            voiceover_services.create_voice_artist_metadata_model_instance(
                self.voice_artist_id,
                self.language_code_to_accent
            )
        )

        self.assertEqual(voice_artist_metadata_model.id, self.voice_artist_id)
        self.assertDictEqual(
            voice_artist_metadata_model.language_code_to_accent,
            self.language_code_to_accent)


class ExplorationVoiceArtistLinkTests(test_utils.GenericTestBase):
    """Unit test to validate exploration voice artists link informations."""

    def setUp(self) -> None:
        super().setUp()
        self.voiceover1: state_domain.VoiceoverDict = {
            'filename': 'filename1.mp3',
            'file_size_bytes': 3000,
            'needs_update': False,
            'duration_secs': 6.1
        }
        self.voiceover2: state_domain.VoiceoverDict = {
            'filename': 'filename2.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.9
        }
        self.voiceover3: state_domain.VoiceoverDict = {
            'filename': 'filename3.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.0
        }
        self.voiceover4: state_domain.VoiceoverDict = {
            'filename': 'filename4.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 3.0
        }
        self.voiceover5: state_domain.VoiceoverDict = {
            'filename': 'filename5.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 7.0
        }
        self.voiceover6: state_domain.VoiceoverDict = {
            'filename': 'filename6.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.0
        }
        self.voiceover7: state_domain.VoiceoverDict = {
            'filename': 'filename7.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.0
        }
        self.voiceover8: state_domain.VoiceoverDict = {
            'filename': 'filename8.mp3',
            'file_size_bytes': 3500,
            'needs_update': False,
            'duration_secs': 5.0
        }
        self.exploration_id = 'exploration_id'
        self.content_id_to_voiceovers_mapping = {
            'content_0': {
                'en': ('voice_artist_0', self.voiceover1)
            },
            'content_1': {
                'hi': ('voice_artist_1', self.voiceover2)
            }
        }

    def test_should_create_exploration_voice_artists_link_model_successfully(
        self
    ) -> None:
        exploration_voice_artists_link_model = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                self.exploration_id,
                self.content_id_to_voiceovers_mapping
            )
        )

        self.assertEqual(
            exploration_voice_artists_link_model.id, self.exploration_id)
        self.assertDictEqual(
            exploration_voice_artists_link_model.
            content_id_to_voiceovers_mapping,
            self.content_id_to_voiceovers_mapping
        )

    def test_should_get_all_voice_artist_language_accent_mapping(self) -> None:

        voiceover_services.update_voice_artist_metadata(
            voice_artist_id='voice_artist_1',
            language_code_to_accent={
                'en': 'en-US',
                'hi': 'hi-IN'
            }
        )

        exploration_voice_artists_link_model1 = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                exploration_id='exploration_id_1',
                content_id_to_voiceovers_mapping={
                    'content_0': {
                        'en': ('voice_artist_1', self.voiceover1),
                    },
                    'content_1': {
                        'ar': ('voice_artist_2', self.voiceover3)
                    }
                }
            )
        )
        exploration_voice_artists_link_model1.put()

        exploration_voice_artists_link_model2 = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                exploration_id='exploration_id_2',
                content_id_to_voiceovers_mapping={
                    'content_0': {
                        'hi': ('voice_artist_1', self.voiceover2)
                    }
                }
            )
        )
        exploration_voice_artists_link_model2.put()

        expected_voice_artist_to_language_mapping = {
            'voice_artist_1': {
                'en': 'en-US',
                'hi': 'hi-IN'
            },
            'voice_artist_2': {
                'ar': ''
            }
        }

        retrieved_voice_artist_to_language_mapping = (
            voiceover_services.get_all_voice_artist_language_accent_mapping()
        )

        self.assertDictEqual(
            expected_voice_artist_to_language_mapping,
            retrieved_voice_artist_to_language_mapping
        )

    def test_get_all_voice_artist_id_to_username(self) -> None:
        auth_id = 'someUser'
        username = 'username'
        user_settings = user_services.create_new_user(
            auth_id, 'user@example.com')
        voice_artist_id = user_settings.user_id
        user_services.set_username(voice_artist_id, username)

        expected_voice_artist_id_to_username = {
            voice_artist_id: username
        }

        exploration_voice_artists_link_model2 = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                exploration_id='exploration_id_2',
                content_id_to_voiceovers_mapping={
                    'content_0': {
                        'hi': (voice_artist_id, self.voiceover1)
                    },
                    'content_1': {
                        'en': (voice_artist_id, self.voiceover2)
                    }
                }
            )
        )
        exploration_voice_artists_link_model2.put()

        self.assertDictEqual(
            voiceover_services.get_voice_artist_ids_to_voice_artist_names(),
            expected_voice_artist_id_to_username
        )

    def test_should_get_exploration_id_to_filenames(self) -> None:
        exploration_voice_artists_link_model1 = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                exploration_id='exploration_id_1',
                content_id_to_voiceovers_mapping={
                    'content_0': {
                        'en': ('voice_artist_1', self.voiceover1),
                    },
                    'content_1': {
                        'ar': ('voice_artist_2', self.voiceover3),
                        'en': ('voice_artist_1', self.voiceover4)
                    },
                    'content_2': {
                        'en': ('voice_artist_1', self.voiceover6),
                    },
                    'content_3': {
                        'en': ('voice_artist_1', self.voiceover5)
                    }
                }
            )
        )
        exploration_voice_artists_link_model1.put()

        exploration_voice_artists_link_model2 = (
            voiceover_services.
            create_exploration_voice_artists_link_model_instance(
                exploration_id='exploration_id_2',
                content_id_to_voiceovers_mapping={
                    'content_0': {
                        'en': ('voice_artist_1', self.voiceover2),
                    },
                    'content_1': {
                        'en': ('voice_artist_1', self.voiceover7),
                        'ar': ('voice_artist_1', self.voiceover8)
                    }
                }
            )
        )
        exploration_voice_artists_link_model2.put()

        exploration_id_to_filenames = (
            voiceover_services.get_voiceover_filenames(
                voice_artist_id='voice_artist_1', language_code='en'))

        total_files = 0
        for filnames in exploration_id_to_filenames.values():
            total_files += len(filnames)

        self.assertEqual(total_files, 5)

        exploration_id_to_filenames = (
            voiceover_services.get_voiceover_filenames(
                voice_artist_id='voice_artist_2', language_code='ar'))

        total_files = 0
        for filnames in exploration_id_to_filenames.values():
            total_files += len(filnames)

        self.assertEqual(total_files, 1)
