import datetime
from typing import Any, Dict, Optional, Text

from .. import App

class UserRecord: ...

class ImportUserRecord: ...

class UserImportResult: ...

class ListUsersPage: ...

def create_session_cookie(
        id_token: Optional[Text],
        expires_in: Optional[datetime.timedelta],
        app: Optional[App] = ...
) -> Text: ...

def update_user(uid: Text, **kwargs: Any) -> None: ...

def delete_user(uid: Text) -> None: ...

def get_user(uid: Text) -> UserRecord: ...

def set_custom_user_claims(
        uid: Text,
        custom_claims: Optional[Text],
        app: Optional[App] = ...
) -> None: ...

def revoke_refresh_tokens(
        uid: Text,
        app: Optional[App] = ...
) -> None: ...

def verify_session_cookie(
    session_cookie: Text,
    check_revoked: bool = ...,
    app: Optional[App] = ...
) -> Dict[Text, Any]: ...

class UserNotFoundError(Exception): ...

class ExpiredSessionCookieError(Exception): ...

class RevokedSessionCookieError(Exception): ...
