from typing import Any, Optional, Union

class Blob(type):
    def __init__(*args: Any, **kwds: Any) -> None: ...
    def download_as_bytes(self) -> bytes: ...
    def upload_from_string(
            self, data: Union[bytes, str], content_type: Optional[str]
    ) -> None: ...
    def delete(self) -> None: ...
