from google.cloud.storage.blob import Blob

from typing import Any, Optional

class Bucket(type):
    def __init__(*args: Any, **kwds: Any) -> None: ...
    def get_blob(self, blob_name: str) -> Blob: ...
    def blob(self, blob_name: str) -> Blob: ...
    def copy_blob(
            self, blob: Blob, bucket: Bucket, new_name: Optional[str]
    ) -> None: ...
