name: Setup
on: [push]

jobs:
  lint:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Install third party
        run: python -m scripts.install_third_party_libs
      - name: Third party size check
        run: python -m scripts.third_party_size_check
      - name: run lint
        run: python -m scripts.pre_commit_linter --path=. --verbose
