name: Comment on CI Workflows

on:
  pull_request_target:
    types: [opened, synchronized, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  comment_on_ci_results:
    name: Comment On CI Workflows
    runs-on: ubuntu-22.04
    permissions:
      pull-requests: write
    strategy:
      matrix:
        test_name: ["Full-Stack Tests", "Backend Unit Test Suite", "Frontend Unit Test Suite"]
        include:
          - test_name: "Full-Stack Tests"
            workflow_file: "full_stack_tests.yml"
          - test_name: "Backend Unit Test Suite"
            workflow_file: "backend_unit_tests.yml"
          - test_name: "Frontend Unit Test Suite"
            workflow_file: "frontend_unit_tests.yml"
    steps:
      - name: Await Test Workflow Completion
        id: wait
        uses: ArcticLampyrid/action-wait-for-workflow@v1.2.0
        with:
          workflow: ${{ matrix.workflow_file }}
          sha: ${{ github.event.pull_request.head.sha }}
          allowed-conclusions: |
            success
            failure
            action_required

      - name: Verify Manual Approval Requirement
        if: ${{ steps.wait.outputs.run-conclusion == 'action_required' }}
        run: |
          echo "::error::First-time contributor workflows require manual approval. After approval, please re-run the comment workflows to post the report."
          exit 1

      - name: Notify on Test Failure
        if: ${{ steps.wait.outputs.run-conclusion == 'failure' && !cancelled() }}
        uses: peter-evans/create-or-update-comment@v3
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🛠️ Hi @${{ github.event.pull_request.user.login }}, it looks like the **${{ matrix.test_name }}** are failing on your PR.
            Please check the logs and follow [these instructions](https://github.com/oppia/oppia/wiki/If-CI-checks-fail-on-your-PR#introduction)
            to fix the issues, or report the error as a flake. Thanks!
