name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_history_statistics_tabs_and_extensions:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - uses: ./.github/actions/merge
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: /home/runner/work/oppia/yarn_cache
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - uses: ./.github/actions/install-oppia-dependencies
      - id: check-risk
        name: Check if PR is low-risk
        uses: ./.github/actions/check-if-pr-is-low-risk
      - name: Install chrome
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: python -m scripts.install_chrome_for_ci
      - name: Install ffmpeg
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: sudo apt install ffmpeg
      - name: Build Webpack
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: python -m scripts.build --prod_env
      - name: Run History Tab E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationHistoryTab" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 1
      - name: Run Statistics Tab E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationStatisticsTab" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 1
      - name: Run Extensions E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a --server-args="-screen 0, 1285x1000x24" python -m scripts.run_e2e_tests --skip-build --skip-install --suite="extensions" --prod_env
        env: 
          VIDEO_RECORDING_IS_ENABLED: 1
      - name: Uploading protractor-video as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: protractor-video
          path: /home/runner/work/oppia/protractor-video
      - name: Uploading protractor screenshots as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: protractor-screenshots
          path: /home/runner/work/oppia/protractor-screenshots
      - name: Uploading webpack bundles as an artifact
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: webpack-bundles
          path: /home/runner/work/oppia/oppia/build
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "An E2E test failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
