name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_history_statistics_tabs_and_extensions:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup python by installing wheel
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: pip install wheel==0.35.0
      - name: Install third party
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: python -m scripts.install_third_party_libs
      - name: Install chrome version 88.0.4324.96-1
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: |
          sudo apt-get update
          sudo apt-get install libappindicator3-1
          curl -L -o google-chrome.deb https://github.com/webnicer/chrome-downloads/raw/master/x64.deb/google-chrome-stable_88.0.4324.96-1_amd64.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          sudo dpkg -i google-chrome.deb
          google-chrome --version
      - name: Run History Tab E2E Test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --suite="explorationHistoryTab" --prod_env
      - name: Run Statistics Tab E2E Test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationStatisticsTab" --prod_env
      - name: Run Extensions E2E Test
        if: startsWith(github.head_ref, 'update-changelog-for-release') == false
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="extensions" --prod_env
