name: End-to-End tests
on:
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_history_statistics_tabs_and_extensions:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '2.x'
          architecture: 'x64'
      - name: Setup python by installing wheel
        run: pip install wheel==0.35.0
      - name: Install third party
        run: python -m scripts.install_third_party_libs
      - id: check-risk
        name: Check if PR is low-risk
        uses: ./.github/actions/check-if-pr-is-low-risk
      - name: Install chrome
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: python -m scripts.install_chrome_for_ci
      - name: Run History Tab E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --suite="explorationHistoryTab" --prod_env
      - name: Run Statistics Tab E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="explorationStatisticsTab" --prod_env
      - name: Run Extensions E2E Test
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 }}
        run: xvfb-run -a python -m scripts.run_e2e_tests --skip-build --skip-install --suite="extensions" --prod_env
      - name: Uploading protractor-screenshots as Artifacts
        if: ${{ steps.check-risk.outputs.is-low-risk != 0 && always() }}
        uses: actions/upload-artifact@v2
        with:
          name: protractor-screenshots
          path: /home/runner/work/oppia/protractor-screenshots
