name: Full Stack Test Comment

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  full_stack_tests_completed:
    name: Full Stack Tests Completed
    runs-on: ubuntu-22.04
    outputs:
      conclusion: ${{ steps.wait-for-full-stack-test.outputs.run-conclusion }}
    steps:
      - name: Wait for Full Stack Tests to Complete
        id: wait-for-full-stack-test
        uses: ArcticLampyrid/action-wait-for-workflow@v1.2.0
        with:
          workflow: full_stack_tests.yml
          sha: auto
          allowed-conclusions: |
            success
            failure
            action_required

      - name: Conclusion Analysis
        if: ${{ steps.wait-for-full-stack-test.outputs.run-conclusion == 'action_required' }}
        run: |
          echo "::error::First-time contributor workflows require manual approval. After approval, please re-run the comment workflows to post the report."
          exit 1

  full_stack_test_report:
    name: Full Stack Test Report
    needs: full_stack_tests_completed
    if: ${{ needs.full_stack_tests_completed.outputs.conclusion == 'failure' && !cancelled() }}
    permissions:
      pull-requests: write
    runs-on: ubuntu-22.04
    steps:
      - name: Find CI Workflow Run for PR
        id: find-workflow-run
        uses: actions/github-script@v7
        continue-on-error: true
        with:
          script: |
            // Find the last run of the full_stack_tests.yml workflow for the current PR's head
            const { owner, repo } = context.repo;
            const runsResponse = await github.rest.actions.listWorkflowRuns({
              owner,
              repo,
              workflow_id: 'full_stack_tests.yml',
              event: 'pull_request',
              head_sha: context.payload.pull_request.head.sha,
            });
            const runs = runsResponse.data.workflow_runs;
            runs.sort((a, b) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime());
            const run = runs[0];
            if (!run) {
              core.setFailed('Could not find a workflow run for the PR');
            } else {
              core.setOutput('run-id', run.id);
            }
      - name: Leave a Comment on the PR
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            🛠️ Hi @${{ github.event.pull_request.user.login }}, it looks like the CI checks are failing on your PR.
            Please look at the logs and follow [these instructions](https://github.com/oppia/oppia/wiki/If-CI-checks-fail-on-your-PR#introduction)
            to fix them, or report the error as a flake. Thanks!
