name: Full-stack tests
permissions: read-all

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the app
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies
      - name: Generate build files
        uses: ./.github/actions/generate-build-files

  e2e_test_collections:
    needs: [build]
    runs-on: ubuntu-22.04
    name: E2E (collections)
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies
      - name: Generate build files
        uses: ./.github/actions/generate-build-files
      - name: Install Chrome
        uses: ./.github/actions/install-chrome
      - name: Install ffmpeg
        run: |
          sudo apt-get update
          sudo apt install ffmpeg
      - name: Run E2E Test (collections)
        run: |
          set -o pipefail
          VIDEO_RECORDING_IS_ENABLED=0
          xvfb-run -a --server-args="-screen 0, 1285x1000x24" \
          python -m scripts.run_e2e_tests --skip-install --skip-build --suite=collections --prod_env --server_log_level=info \
          | tee e2e_test_collections.log
      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-logs-collections
          path: e2e_test_collections.log
