name: Full-stack tests

permissions:
  contents: read

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build the app, and store build files as an artifact
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies

      - name: Generate build files
        uses: ./.github/actions/generate-build-files

  acceptance_test_with_python_installation:
    needs: build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - run: 1
            suite: exploration-editor/create-an-exploration-with-all-interactions
            mobile_args: "--mobile"
          - run: 2
            suite: exploration-editor/preview-all-exploration-interactions
            mobile_args: "--mobile"
          - run: 3
            suite: exploration-editor/exploration-settings
            mobile_args: "--mobile"
          - run: 4
            suite: exploration-editor/exploration-history
            mobile_args: "--mobile"
          - run: 5
            suite: exploration-editor/exploration-feedback
            mobile_args: "--mobile"
          - run: 6
            suite: exploration-editor/exploration-help
            mobile_args: "--mobile"
          - run: 7
            suite: exploration-editor/exploration-navbar-header
            mobile_args: "--mobile"
          - run: 8
            suite: exploration-editor/create-an-exploration-with-all-interactions
            mobile_args: ""
          - run: 9
            suite: exploration-editor/preview-all-exploration-interactions
            mobile_args: ""
          - run: 10
            suite: exploration-editor/exploration-settings
            mobile_args: ""

    name: Acceptance (${{ matrix.suite }}) (Run ${{ matrix.run }}, ${{ matrix.mobile_args != '' && 'Mobile' || 'Desktop' }})
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Merge develop and set up dependencies
        uses: ./.github/actions/merge-develop-and-set-up-dependencies

      - name: Generate build files
        uses: ./.github/actions/generate-build-files

      - name: Generate suite name for artifacts
        id: generate_suite_name_for_artifacts
        run: |
          SUITE_NAME="${{ matrix.suite }}-${{ matrix.mobile_args != '' && 'mobile' || 'desktop' }}-${{ matrix.run }}"
          MODIFIED_SUITE_NAME="${SUITE_NAME//\//_}"
          echo "MODIFIED_SUITE_NAME=$MODIFIED_SUITE_NAME" >> "$GITHUB_OUTPUT"

      - name: Run Acceptance Test
        id: run_tests
        run: |
          set -o pipefail
          VIDEO_RECORDING_IS_ENABLED=1 xvfb-run -a --server-args="-screen 0, 1920x1080x24" \
          python -m scripts.run_acceptance_tests \
          --skip-build --suite="${{ matrix.suite }}" --prod_env ${{ matrix.mobile_args }} \
          | tee "acceptance_test_${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}.log"
        continue-on-error: true

      - name: Upload acceptance test logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: acceptance-test-logs-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: acceptance_test_${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}.log

      - name: Upload failure screenshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: failure-screenshot-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia_full_stack_test_failure_screenshots/acceptance

      - name: Upload diff snapshots
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: diff-snapshots-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia/core/tests/puppeteer-acceptance-tests/diff-snapshots

      - name: Upload video recordings
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-video-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia_full_stack_test_video_recordings/acceptance

      - name: Upload test-to-angular-module mapping
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-to-angular-module-mapping-${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}
          path: /home/runner/work/oppia/oppia/core/tests/test-modules-mappings/acceptance/${{ steps.generate_suite_name_for_artifacts.outputs.MODIFIED_SUITE_NAME }}.txt
