name: Test coverage and Typescript test
on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - develop
      - release-*
  pull_request:
    branches:
      - develop
      - release-*

jobs:
  e2e_acceptance_coverage_and_typescript_tests:
    runs-on:  ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.15'
          architecture: 'x64'
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" 
      - name: Merge develop branch into the current branch
        uses: ./.github/actions/merge
      - name: Install Chrome
        uses: ./.github/actions/install-chrome
      - name: Initialize Containers
        run: |
          make build
          sudo make run-devserver
          make stop
      - name: Check that all e2e test files are captured in wdio.conf.js
        run: make run_tests.check_tests_are_captured_in_ci
      - name: Run typescript tests
        run: make run_tests.typescript
      - name: Run typescript tests in strict mode
        run: make run_tests.typescript PYTHON_ARGS="--strict_checks"
      - name: Report failure if failed on oppia/oppia develop branch
        if: ${{ failure() && github.event_name == 'push' && github.repository == 'oppia/oppia' && github.ref == 'refs/heads/develop'}}
        uses: ./.github/actions/send-webhook-notification
        with:
          message: "A typescript test failed on the upstream develop branch."
          webhook-url: ${{ secrets.BUILD_FAILURE_ROOM_WEBHOOK_URL }}
